In [178]:
import numpy as np
import pandas as pd

In [179]:
# pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)
# pd.reset_option("display.max_rows")

In [180]:
df = pd.read_csv("D:\\CODING\\Virtual_py\\PROJECTS\\real_estate_ml\\backend\\kolkata.csv\\kolkata_cleaned_v1.csv")

In [181]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8797 entries, 0 to 8796
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PREFERENCE                  8797 non-null   str
 1   DESCRIPTION                 8797 non-null   str
 2   PROPERTY_TYPE               8797 non-null   str
 3   CITY                        8797 non-null   str
 4   TRANSACT_TYPE               7058 non-null   float64
 5   OWNTYPE                     8797 non-null   int64
 6   BEDROOM_NUM                 8311 non-null   float64
 7   FURNISH                     8797 non-null   int64
 8   FACING                      8797 non-null   int64
 9   AGE                         8797 non-null   int64
 10  TOTAL_FLOOR                 8745 non-null   float64
 11  FEATURES                    8797 non-null   str
 12  PROP_NAME                   8162 non-null   str
 13  AMENITIES                   6744 non-null   str
 14  PROP_HEADING                8797 non-null   str
 15  SECONDARY_TAGS              8797 non-null   str
 16  TOTAL_LANDMARK_COUNT        8574 non-null   float64
 17  FORMATTED_LANDMARK_DETAILS  8574 non-null   str
 18  location                    8797 non-null   str
 19  BALCONY_NUM                 6653 non-null   float64
 20  FLOOR_NUM                   7817 non-null   str
 21  PRICE_Cr                    8762 non-null   float64
 22  AREA_SQFT                   8797 non-null   float64
 23  PRICE_PER_SQFT(INR)         8762 non-null   float64
 24  OWNTYPE_label               8797 non-null   str
 25  FURNISH_label               8797 non-null   str
 26  FACING_label                8797 non-null   str
 27  LATITUDE                    8797 non-null   float64
 28  LONGITUDE                   8797 non-null   float64
dtypes: float64(10), int64(4), str(15)
memory usage: 16.1 MB

In [182]:
df.head()

,PREFERENCE,DESCRIPTION,PROPERTY_TYPE,CITY,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,AMENITIES,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT,PRICE_PER_SQFT(INR),OWNTYPE_label,FURNISH_label,FACING_label,LATITUDE,LONGITUDE
0,S,Book your 2 BHK flat in Srijan Star Swapno Pur...,Residential Apartment,Kolkata South,2.0,1,2.0,0,0,5,3.0,N,srijan star swapno puron,NaN,2 BHK Flat in Amtala,"['UNDER CONSTRUCTION', 'NEW BOOKING', 'RERA | ...",2.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.191000,570.5,3347.94,Cooperative Society,Unfurnished,East,22.364447,88.274642
1,S,Make Natural Quest your next home. This projec...,Residential Apartment,Kolkata South,2.0,1,3.0,0,0,5,11.0,N,natural quest,NaN,3 BHK Flat in EM Bypass,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",9.0,"[{'category': 'MetroStation', 'text': '1 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.590000,1115.5,5289.11,Cooperative Society,Unfurnished,East,22.518795,88.388439
2,S,"Book your 3 BHK apartment in Garia, Kolkata So...",Residential Apartment,Kolkata South,2.0,1,3.0,0,0,5,20.0,N,ganguly 4sight eminence,NaN,3 BHK Flat in Garia,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",6.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.675000,1446.0,4668.05,Cooperative Society,Unfurnished,East,22.513765,88.366680
3,S,"Dev bhumi in joka, kolkata south by ocean land...",Residential Land,Kolkata South,2.0,1,NaN,0,0,0,0.0,N,dev bhumi,NaN,Residential land / Plot in Joka,"['READY TO MOVE', 'NEW BOOKING']",13.0,"[{'category': 'MetroStation', 'text': '2 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,NaN,0.029950,1800.0,166.39,Cooperative Society,Unfurnished,East,22.453830,88.249572
4,S,Let your dream of owning a flat come true with...,Residential Apartment,Kolkata South,2.0,1,3.0,0,0,5,19.0,N,dtc sojon,NaN,3 BHK Flat in Joka,"['UNDER CONSTRUCTION', 'NEW BOOKING']",11.0,"[{'category': 'MetroStation', 'text': '1 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.375003,1295.0,2895.78,Cooperative Society,Unfurnished,East,22.442130,88.295510

In [183]:
df[["OWNTYPE", "OWNTYPE_label"]].sample(10)

      OWNTYPE        OWNTYPE_label
8428        1  Cooperative Society
8383        1  Cooperative Society
5513        1  Cooperative Society
3675        1  Cooperative Society
3033        1  Cooperative Society
5582        0             Freehold
2108        1  Cooperative Society
6611        1  Cooperative Society
4465        1  Cooperative Society
8088        1  Cooperative Society

In [184]:
df["OWNTYPE_label"].unique()

<ArrowStringArray>
['Cooperative Society', 'Freehold', 'Power of Attorney', 'Other', 'Leasehold']
Length: 5, dtype: str

In [185]:
# owntype

new_cols = ['Cooperative Society', 'Power of Attorney', 'Other', 'Leasehold']

for col in new_cols:
    df[col] = df["OWNTYPE_label"].str.contains(col).astype(int)

In [186]:
df.sample(5)

,PREFERENCE,DESCRIPTION,PROPERTY_TYPE,CITY,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,AMENITIES,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT,PRICE_PER_SQFT(INR),OWNTYPE_label,FURNISH_label,FACING_label,LATITUDE,LONGITUDE,Cooperative Society,Power of Attorney,Other,Leasehold
5479,S,Located in the popular residential address of ...,Residential Apartment,Kolkata South,1.0,1,3.0,2,2,5,8.0,"23,12,24,25,47,26,17,28,29,19,1,3,5,6,9,40,41,...",sucasa valley,"17,5,20,21,32,23,24,47,28,29,19,1,6,9,40,41,43...",3 BHK Flat in Narendrapur,"['UNDER CONSTRUCTION', 'RESALE']",18.0,"[{'category': 'ReligiousPlace', 'text': '6 Rel...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",1.0,7,0.3543,1042.0,3400.19,Cooperative Society,Fully furnished,North,22.447920,88.403890,1,0,0,0
5077,S,Located in the popular residential address of ...,Residential Apartment,Kolkata East,1.0,1,2.0,2,7,2,24.0,"44,23,45,24,46,25,26,28,29,30,31,10,32,33,12,1...",uniworld city,"10,32,17,2,5,8,20,21,44,23,45,24,46,28,29,30,3...",2 BHK Flat in New Town,"['READY TO MOVE', 'RESALE']",13.0,"[{'category': 'ATM', 'text': '2 ATMs', 'classN...","{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'L...",1.0,12,0.9500,1464.0,6489.07,Cooperative Society,Fully furnished,North-West,22.559944,88.495769,1,0,0,0
4462,S,Located in the popular residential address of ...,Residential Apartment,Kolkata East,1.0,1,2.0,2,5,1,4.0,"5,17,21",on request,"5,17,21,101,102",2 BHK Flat in Chinar Park,"['READY TO MOVE', 'RESALE']",41.0,"[{'category': 'MetroStation', 'text': '1 Metro...","{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'L...",1.0,2,0.5000,850.0,5882.35,Cooperative Society,Fully furnished,South-East,22.587850,88.454834,1,0,0,0
4052,S,3bhk new flat sale near new garia metro statio...,Residential Apartment,Kolkata South,1.0,1,3.0,0,7,1,4.0,"23,19,21",riyang apartment,"21,23,19,101,102",3 BHK Flat in New Garia,"['READY TO MOVE', 'RESALE']",41.0,"[{'category': 'MetroStation', 'text': '2 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",1.0,4,0.6500,1250.0,5200.00,Cooperative Society,Unfurnished,North-West,22.473349,88.405040,1,0,0,0
453,S,"5 min to metro station , within 100m 3 atms, w...",Residential Apartment,Kolkata South,1.0,1,2.0,2,5,5,4.0,24,north view apartment,"24,102,103",2 BHK Flat in Parnasree Palli,"['UNDER CONSTRUCTION', 'RESALE']",38.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",1.0,1,0.3650,810.0,4506.17,Cooperative Society,Fully furnished,South-East,22.509326,88.301471,1,0,0,0

In [187]:
df[["FACING", "FACING_label"]].sample(10)

      FACING FACING_label
3738       5   South-East
2290       2        North
574        0         East
5512       8        Other
8717       7   North-West
7865       7   North-West
5016       7   North-West
6180       8        Other
547        4   North-East
5704       2        North

In [188]:
df["FACING_LABEL"] = df["FACING_label"]
df = pd.get_dummies(df, columns=["FACING_label"], drop_first=True, dtype=int)

df["FURNISH_LABEL"] = df["FURNISH_label"]
df = pd.get_dummies(df, columns=["FURNISH_label"], drop_first=True, dtype=int)

In [189]:
df.head(1)

,PREFERENCE,DESCRIPTION,PROPERTY_TYPE,CITY,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,AMENITIES,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT,PRICE_PER_SQFT(INR),OWNTYPE_label,LATITUDE,LONGITUDE,Cooperative Society,Power of Attorney,Other,Leasehold,FACING_LABEL,FACING_label_North,FACING_label_North-East,FACING_label_North-West,FACING_label_Other,FACING_label_South,FACING_label_South-East,FACING_label_South-West,FACING_label_West,FURNISH_LABEL,FURNISH_label_Other,FURNISH_label_Semi-furnished,FURNISH_label_Unfurnished
0,S,Book your 2 BHK flat in Srijan Star Swapno Pur...,Residential Apartment,Kolkata South,2.0,1,2.0,0,0,5,3.0,N,srijan star swapno puron,NaN,2 BHK Flat in Amtala,"['UNDER CONSTRUCTION', 'NEW BOOKING', 'RERA | ...",2.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.191,570.5,3347.94,Cooperative Society,22.364447,88.274642,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1

In [190]:
df["CITY"].unique()

<ArrowStringArray>
[  'Kolkata South',   'Kolkata North', 'Kolkata Central',    'Kolkata East',
    'Kolkata West']
Length: 5, dtype: str

In [191]:
df["PROPERTY_type"] = df["PROPERTY_TYPE"]
df = pd.get_dummies(df, columns=["PROPERTY_TYPE"], drop_first=True, dtype=int)

df["CITY_LABELS"] = df["CITY"]
df = pd.get_dummies(df, columns=["CITY"], drop_first=True, dtype=int)

In [192]:
df.head()

,PREFERENCE,DESCRIPTION,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,AMENITIES,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT,PRICE_PER_SQFT(INR),OWNTYPE_label,LATITUDE,LONGITUDE,Cooperative Society,Power of Attorney,Other,Leasehold,FACING_LABEL,FACING_label_North,FACING_label_North-East,FACING_label_North-West,FACING_label_Other,FACING_label_South,FACING_label_South-East,FACING_label_South-West,FACING_label_West,FURNISH_LABEL,FURNISH_label_Other,FURNISH_label_Semi-furnished,FURNISH_label_Unfurnished,PROPERTY_type,PROPERTY_TYPE_Independent/Builder Floor,PROPERTY_TYPE_Residential Apartment,PROPERTY_TYPE_Residential Land,CITY_LABELS,CITY_Kolkata East,CITY_Kolkata North,CITY_Kolkata South,CITY_Kolkata West
0,S,Book your 2 BHK flat in Srijan Star Swapno Pur...,2.0,1,2.0,0,0,5,3.0,N,srijan star swapno puron,NaN,2 BHK Flat in Amtala,"['UNDER CONSTRUCTION', 'NEW BOOKING', 'RERA | ...",2.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.191000,570.5,3347.94,Cooperative Society,22.364447,88.274642,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0
1,S,Make Natural Quest your next home. This projec...,2.0,1,3.0,0,0,5,11.0,N,natural quest,NaN,3 BHK Flat in EM Bypass,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",9.0,"[{'category': 'MetroStation', 'text': '1 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.590000,1115.5,5289.11,Cooperative Society,22.518795,88.388439,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0
2,S,"Book your 3 BHK apartment in Garia, Kolkata So...",2.0,1,3.0,0,0,5,20.0,N,ganguly 4sight eminence,NaN,3 BHK Flat in Garia,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",6.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.675000,1446.0,4668.05,Cooperative Society,22.513765,88.366680,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0
3,S,"Dev bhumi in joka, kolkata south by ocean land...",2.0,1,NaN,0,0,0,0.0,N,dev bhumi,NaN,Residential land / Plot in Joka,"['READY TO MOVE', 'NEW BOOKING']",13.0,"[{'category': 'MetroStation', 'text': '2 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,NaN,0.029950,1800.0,166.39,Cooperative Society,22.453830,88.249572,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Land,0,0,1,Kolkata South,0,0,1,0
4,S,Let your dream of owning a flat come true with...,2.0,1,3.0,0,0,5,19.0,N,dtc sojon,NaN,3 BHK Flat in Joka,"['UNDER CONSTRUCTION', 'NEW BOOKING']",11.0,"[{'category': 'MetroStation', 'text': '1 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.375003,1295.0,2895.78,Cooperative Society,22.442130,88.295510,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0

In [193]:
df.columns

Index(['PREFERENCE', 'DESCRIPTION', 'TRANSACT_TYPE', 'OWNTYPE', 'BEDROOM_NUM',
       'FURNISH', 'FACING', 'AGE', 'TOTAL_FLOOR', 'FEATURES', 'PROP_NAME',
       'AMENITIES', 'PROP_HEADING', 'SECONDARY_TAGS', 'TOTAL_LANDMARK_COUNT',
       'FORMATTED_LANDMARK_DETAILS', 'location', 'BALCONY_NUM', 'FLOOR_NUM',
       'PRICE_Cr', 'AREA_SQFT', 'PRICE_PER_SQFT(INR)', 'OWNTYPE_label',
       'LATITUDE', 'LONGITUDE', 'Cooperative Society', 'Power of Attorney',
       'Other', 'Leasehold', 'FACING_LABEL', 'FACING_label_North',
       'FACING_label_North-East', 'FACING_label_North-West',
       'FACING_label_Other', 'FACING_label_South', 'FACING_label_South-East',
       'FACING_label_South-West', 'FACING_label_West', 'FURNISH_LABEL',
       'FURNISH_label_Other', 'FURNISH_label_Semi-furnished',
       'FURNISH_label_Unfurnished', 'PROPERTY_type',
       'PROPERTY_TYPE_Independent/Builder Floor',
       'PROPERTY_TYPE_Residential Apartment', 'PROPERTY_TYPE_Residential Land',
       'CITY_LABELS', 'CITY_Kolkata East', 'CITY_Kolkata North',
       'CITY_Kolkata South', 'CITY_Kolkata West'],
      dtype='str')

In [194]:
df.head()

,PREFERENCE,DESCRIPTION,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,AMENITIES,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT,PRICE_PER_SQFT(INR),OWNTYPE_label,LATITUDE,LONGITUDE,Cooperative Society,Power of Attorney,Other,Leasehold,FACING_LABEL,FACING_label_North,FACING_label_North-East,FACING_label_North-West,FACING_label_Other,FACING_label_South,FACING_label_South-East,FACING_label_South-West,FACING_label_West,FURNISH_LABEL,FURNISH_label_Other,FURNISH_label_Semi-furnished,FURNISH_label_Unfurnished,PROPERTY_type,PROPERTY_TYPE_Independent/Builder Floor,PROPERTY_TYPE_Residential Apartment,PROPERTY_TYPE_Residential Land,CITY_LABELS,CITY_Kolkata East,CITY_Kolkata North,CITY_Kolkata South,CITY_Kolkata West
0,S,Book your 2 BHK flat in Srijan Star Swapno Pur...,2.0,1,2.0,0,0,5,3.0,N,srijan star swapno puron,NaN,2 BHK Flat in Amtala,"['UNDER CONSTRUCTION', 'NEW BOOKING', 'RERA | ...",2.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.191000,570.5,3347.94,Cooperative Society,22.364447,88.274642,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0
1,S,Make Natural Quest your next home. This projec...,2.0,1,3.0,0,0,5,11.0,N,natural quest,NaN,3 BHK Flat in EM Bypass,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",9.0,"[{'category': 'MetroStation', 'text': '1 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.590000,1115.5,5289.11,Cooperative Society,22.518795,88.388439,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0
2,S,"Book your 3 BHK apartment in Garia, Kolkata So...",2.0,1,3.0,0,0,5,20.0,N,ganguly 4sight eminence,NaN,3 BHK Flat in Garia,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",6.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.675000,1446.0,4668.05,Cooperative Society,22.513765,88.366680,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0
3,S,"Dev bhumi in joka, kolkata south by ocean land...",2.0,1,NaN,0,0,0,0.0,N,dev bhumi,NaN,Residential land / Plot in Joka,"['READY TO MOVE', 'NEW BOOKING']",13.0,"[{'category': 'MetroStation', 'text': '2 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,NaN,0.029950,1800.0,166.39,Cooperative Society,22.453830,88.249572,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Land,0,0,1,Kolkata South,0,0,1,0
4,S,Let your dream of owning a flat come true with...,2.0,1,3.0,0,0,5,19.0,N,dtc sojon,NaN,3 BHK Flat in Joka,"['UNDER CONSTRUCTION', 'NEW BOOKING']",11.0,"[{'category': 'MetroStation', 'text': '1 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.375003,1295.0,2895.78,Cooperative Society,22.442130,88.295510,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0

In [195]:
df["TRANSACT_TYPE"].value_counts()

TRANSACT_TYPE
1.0    5388
2.0    1670
Name: count, dtype: int64

In [196]:
df.head()

,PREFERENCE,DESCRIPTION,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,AMENITIES,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT,PRICE_PER_SQFT(INR),OWNTYPE_label,LATITUDE,LONGITUDE,Cooperative Society,Power of Attorney,Other,Leasehold,FACING_LABEL,FACING_label_North,FACING_label_North-East,FACING_label_North-West,FACING_label_Other,FACING_label_South,FACING_label_South-East,FACING_label_South-West,FACING_label_West,FURNISH_LABEL,FURNISH_label_Other,FURNISH_label_Semi-furnished,FURNISH_label_Unfurnished,PROPERTY_type,PROPERTY_TYPE_Independent/Builder Floor,PROPERTY_TYPE_Residential Apartment,PROPERTY_TYPE_Residential Land,CITY_LABELS,CITY_Kolkata East,CITY_Kolkata North,CITY_Kolkata South,CITY_Kolkata West
0,S,Book your 2 BHK flat in Srijan Star Swapno Pur...,2.0,1,2.0,0,0,5,3.0,N,srijan star swapno puron,NaN,2 BHK Flat in Amtala,"['UNDER CONSTRUCTION', 'NEW BOOKING', 'RERA | ...",2.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.191000,570.5,3347.94,Cooperative Society,22.364447,88.274642,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0
1,S,Make Natural Quest your next home. This projec...,2.0,1,3.0,0,0,5,11.0,N,natural quest,NaN,3 BHK Flat in EM Bypass,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",9.0,"[{'category': 'MetroStation', 'text': '1 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.590000,1115.5,5289.11,Cooperative Society,22.518795,88.388439,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0
2,S,"Book your 3 BHK apartment in Garia, Kolkata So...",2.0,1,3.0,0,0,5,20.0,N,ganguly 4sight eminence,NaN,3 BHK Flat in Garia,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",6.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.675000,1446.0,4668.05,Cooperative Society,22.513765,88.366680,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0
3,S,"Dev bhumi in joka, kolkata south by ocean land...",2.0,1,NaN,0,0,0,0.0,N,dev bhumi,NaN,Residential land / Plot in Joka,"['READY TO MOVE', 'NEW BOOKING']",13.0,"[{'category': 'MetroStation', 'text': '2 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,NaN,0.029950,1800.0,166.39,Cooperative Society,22.453830,88.249572,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Land,0,0,1,Kolkata South,0,0,1,0
4,S,Let your dream of owning a flat come true with...,2.0,1,3.0,0,0,5,19.0,N,dtc sojon,NaN,3 BHK Flat in Joka,"['UNDER CONSTRUCTION', 'NEW BOOKING']",11.0,"[{'category': 'MetroStation', 'text': '1 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.375003,1295.0,2895.78,Cooperative Society,22.442130,88.295510,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0

In [197]:
df.drop(columns = ["OWNTYPE", "FURNISH", "FACING"], inplace=True)

In [198]:
df.head()

,PREFERENCE,DESCRIPTION,TRANSACT_TYPE,BEDROOM_NUM,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,AMENITIES,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT,PRICE_PER_SQFT(INR),OWNTYPE_label,LATITUDE,LONGITUDE,Cooperative Society,Power of Attorney,Other,Leasehold,FACING_LABEL,FACING_label_North,FACING_label_North-East,FACING_label_North-West,FACING_label_Other,FACING_label_South,FACING_label_South-East,FACING_label_South-West,FACING_label_West,FURNISH_LABEL,FURNISH_label_Other,FURNISH_label_Semi-furnished,FURNISH_label_Unfurnished,PROPERTY_type,PROPERTY_TYPE_Independent/Builder Floor,PROPERTY_TYPE_Residential Apartment,PROPERTY_TYPE_Residential Land,CITY_LABELS,CITY_Kolkata East,CITY_Kolkata North,CITY_Kolkata South,CITY_Kolkata West
0,S,Book your 2 BHK flat in Srijan Star Swapno Pur...,2.0,2.0,5,3.0,N,srijan star swapno puron,NaN,2 BHK Flat in Amtala,"['UNDER CONSTRUCTION', 'NEW BOOKING', 'RERA | ...",2.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.191000,570.5,3347.94,Cooperative Society,22.364447,88.274642,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0
1,S,Make Natural Quest your next home. This projec...,2.0,3.0,5,11.0,N,natural quest,NaN,3 BHK Flat in EM Bypass,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",9.0,"[{'category': 'MetroStation', 'text': '1 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.590000,1115.5,5289.11,Cooperative Society,22.518795,88.388439,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0
2,S,"Book your 3 BHK apartment in Garia, Kolkata So...",2.0,3.0,5,20.0,N,ganguly 4sight eminence,NaN,3 BHK Flat in Garia,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",6.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.675000,1446.0,4668.05,Cooperative Society,22.513765,88.366680,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0
3,S,"Dev bhumi in joka, kolkata south by ocean land...",2.0,NaN,0,0.0,N,dev bhumi,NaN,Residential land / Plot in Joka,"['READY TO MOVE', 'NEW BOOKING']",13.0,"[{'category': 'MetroStation', 'text': '2 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,NaN,0.029950,1800.0,166.39,Cooperative Society,22.453830,88.249572,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Land,0,0,1,Kolkata South,0,0,1,0
4,S,Let your dream of owning a flat come true with...,2.0,3.0,5,19.0,N,dtc sojon,NaN,3 BHK Flat in Joka,"['UNDER CONSTRUCTION', 'NEW BOOKING']",11.0,"[{'category': 'MetroStation', 'text': '1 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.375003,1295.0,2895.78,Cooperative Society,22.442130,88.295510,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0

In [234]:
import ast

val = df["FORMATTED_LANDMARK_DETAILS"][1]
parsed = ast.literal_eval(val) 
print(parsed)

[{'category': 'MetroStation', 'text': '1 Metro Station', 'className': 'mstn', 'icon': 'https://static.99acres.com/universalapp/img/mstn.png'}, {'category': 'Shopping', 'text': '2 Shoppings', 'className': 'shpng', 'icon': 'https://static.99acres.com/universalapp/img/shpng.png'}, {'category': 'Education', 'text': '2 Educations', 'className': 'schl', 'icon': 'https://static.99acres.com/universalapp/img/schl.png'}, {'category': 'Hospital', 'text': '2 Hospitals', 'className': 'hsptl', 'icon': 'https://static.99acres.com/universalapp/img/hsptl.png'}, {'category': 'Airport', 'text': '1 Airport', 'className': 'aprt', 'icon': 'https://static.99acres.com/universalapp/img/aprt.png'}, {'category': 'RailwayStation', 'text': '1 Railway Station', 'className': 'rail', 'icon': 'https://static.99acres.com/universalapp/img/rail.png'}]

In [238]:
def extract_category(val):
    # First handle missing values
    if pd.isna(val):
        return ""
    
    # Then safely parse the string
    try:
        parsed = ast.literal_eval(val)
    except (ValueError, SyntaxError):
        return ""
    
    # Handle dict case
    if isinstance(parsed, dict):
        return parsed.get("category", "")
    
    # Handle list of dicts case
    if isinstance(parsed, list):
        return [item.get("category", "") for item in parsed if isinstance(item, dict)]
    
    return ""

# print(extract_category(df["FORMATTED_LANDMARK_DETAILS"][1]))

df["LANDMARK_DETAILS"] = df["FORMATTED_LANDMARK_DETAILS"].apply(extract_category)

In [239]:
df.head()

,PREFERENCE,DESCRIPTION,TRANSACT_TYPE,BEDROOM_NUM,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,AMENITIES,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT,PRICE_PER_SQFT(INR),OWNTYPE_label,LATITUDE,LONGITUDE,Cooperative Society,Power of Attorney,Other,Leasehold,FACING_LABEL,FACING_label_North,FACING_label_North-East,FACING_label_North-West,FACING_label_Other,FACING_label_South,FACING_label_South-East,FACING_label_South-West,FACING_label_West,FURNISH_LABEL,FURNISH_label_Other,FURNISH_label_Semi-furnished,FURNISH_label_Unfurnished,PROPERTY_type,PROPERTY_TYPE_Independent/Builder Floor,PROPERTY_TYPE_Residential Apartment,PROPERTY_TYPE_Residential Land,CITY_LABELS,CITY_Kolkata East,CITY_Kolkata North,CITY_Kolkata South,CITY_Kolkata West,LANDMARK_DETAILS
0,S,Book your 2 BHK flat in Srijan Star Swapno Pur...,2.0,2.0,5,3.0,N,srijan star swapno puron,NaN,2 BHK Flat in Amtala,"['UNDER CONSTRUCTION', 'NEW BOOKING', 'RERA | ...",2.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.191000,570.5,3347.94,Cooperative Society,22.364447,88.274642,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0,"[Shopping, Hospital]"
1,S,Make Natural Quest your next home. This projec...,2.0,3.0,5,11.0,N,natural quest,NaN,3 BHK Flat in EM Bypass,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",9.0,"[{'category': 'MetroStation', 'text': '1 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.590000,1115.5,5289.11,Cooperative Society,22.518795,88.388439,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0,"[MetroStation, Shopping, Education, Hospital, ..."
2,S,"Book your 3 BHK apartment in Garia, Kolkata So...",2.0,3.0,5,20.0,N,ganguly 4sight eminence,NaN,3 BHK Flat in Garia,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",6.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.675000,1446.0,4668.05,Cooperative Society,22.513765,88.366680,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0,"[Shopping, Education, Hospital, Airport, Railw..."
3,S,"Dev bhumi in joka, kolkata south by ocean land...",2.0,NaN,0,0.0,N,dev bhumi,NaN,Residential land / Plot in Joka,"['READY TO MOVE', 'NEW BOOKING']",13.0,"[{'category': 'MetroStation', 'text': '2 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,NaN,0.029950,1800.0,166.39,Cooperative Society,22.453830,88.249572,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Land,0,0,1,Kolkata South,0,0,1,0,"[MetroStation, Connectivity, Education, Hospital]"
4,S,Let your dream of owning a flat come true with...,2.0,3.0,5,19.0,N,dtc sojon,NaN,3 BHK Flat in Joka,"['UNDER CONSTRUCTION', 'NEW BOOKING']",11.0,"[{'category': 'MetroStation', 'text': '1 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.375003,1295.0,2895.78,Cooperative Society,22.442130,88.295510,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0,"[MetroStation, Shopping, Connectivity, Educati..."

In [241]:
for i in range(df["location"].shape[0]):
    parsed = ast.literal_eval(df["location"][i])
    print(parsed)

{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '8005', 'LOCALITY_NAME': 'Amtala ', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '603', 'LOCALITY_NAME': 'EM Bypass', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '651', 'LOCALITY_NAME': 'Garia', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '844', 'LOCALITY_NAME': 'Joka', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '844', 'LOCALITY_NAME': 'Joka', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '844', 'LOCALITY_NAME': 'Joka', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '1465', 'LOCALITY_NAME': 'New Alipore', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '528', 'LOCALITY_NAME': 'Madhyamgram', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6849', 'LOCALITY_NAME': 'Kamalgazi', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6849', 'LOCALITY_NAME': 'Kamalgazi', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '844', 'LOCALITY_NAME': 'Joka', 'ADDRESS': None}
{'CITY': '30', 'CITY_NAME': 'Kolkata Central', 'LOCALITY_ID': '6859', 'LOCALITY_NAME': 'Shakespeare Sarani ', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '844', 'LOCALITY_NAME': 'Joka', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '651', 'LOCALITY_NAME': 'Garia', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '651', 'LOCALITY_NAME': 'Garia', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '651', 'LOCALITY_NAME': 'Garia', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1495', 'LOCALITY_NAME': 'Rajarhat', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1495', 'LOCALITY_NAME': 'Rajarhat', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1495', 'LOCALITY_NAME': 'Rajarhat', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '7998', 'LOCALITY_NAME': 'Chinar Park', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '7998', 'LOCALITY_NAME': 'Chinar Park', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '7998', 'LOCALITY_NAME': 'Chinar Park', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '19491', 'LOCALITY_NAME': 'Action Area 1', 'ADDRESS': 'Ac Block, 129'}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '488', 'LOCALITY_NAME': 'Dum Dum', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '8665', 'LOCALITY_NAME': 'Narkeldanga', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '8665', 'LOCALITY_NAME': 'Narkeldanga', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '1043', 'LOCALITY_NAME': 'Bhawanipore', 'ADDRESS': None}
{'CITY': '29', 'CITY_NAME': 'Kolkata West', 'LOCALITY_ID': '9764', 'LOCALITY_NAME': 'Howrah', 'ADDRESS': None}
{'CITY': '29', 'CITY_NAME': 'Kolkata West', 'LOCALITY_ID': '9764', 'LOCALITY_NAME': 'Howrah', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '484', 'LOCALITY_NAME': 'BT Road', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '484', 'LOCALITY_NAME': 'BT Road', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '484', 'LOCALITY_NAME': 'BT Road', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '25135', 'LOCALITY_NAME': 'Jadubabur Bazar', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '844', 'LOCALITY_NAME': 'Joka', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '15644', 'LOCALITY_NAME': 'Ramchandrapur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '15644', 'LOCALITY_NAME': 'Ramchandrapur', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '528', 'LOCALITY_NAME': 'Madhyamgram', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '8005', 'LOCALITY_NAME': 'Amtala ', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '8005', 'LOCALITY_NAME': 'Amtala ', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '8735', 'LOCALITY_NAME': 'Rajpur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '8735', 'LOCALITY_NAME': 'Rajpur', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '482', 'LOCALITY_NAME': 'Bangur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6852', 'LOCALITY_NAME': 'Narendrapur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6852', 'LOCALITY_NAME': 'Narendrapur', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '484', 'LOCALITY_NAME': 'BT Road', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '484', 'LOCALITY_NAME': 'BT Road', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '603', 'LOCALITY_NAME': 'EM Bypass', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '603', 'LOCALITY_NAME': 'EM Bypass', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6841', 'LOCALITY_NAME': 'Baruipur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6841', 'LOCALITY_NAME': 'Baruipur', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1495', 'LOCALITY_NAME': 'Rajarhat', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1495', 'LOCALITY_NAME': 'Rajarhat', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '603', 'LOCALITY_NAME': 'EM Bypass', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '603', 'LOCALITY_NAME': 'EM Bypass', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1495', 'LOCALITY_NAME': 'Rajarhat', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1495', 'LOCALITY_NAME': 'Rajarhat', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1495', 'LOCALITY_NAME': 'Rajarhat', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1495', 'LOCALITY_NAME': 'Rajarhat', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6845', 'LOCALITY_NAME': 'Boral', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6852', 'LOCALITY_NAME': 'Narendrapur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6852', 'LOCALITY_NAME': 'Narendrapur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6852', 'LOCALITY_NAME': 'Narendrapur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6852', 'LOCALITY_NAME': 'Narendrapur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6845', 'LOCALITY_NAME': 'Boral', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '488', 'LOCALITY_NAME': 'Dum Dum', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '488', 'LOCALITY_NAME': 'Dum Dum', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '528', 'LOCALITY_NAME': 'Madhyamgram', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '528', 'LOCALITY_NAME': 'Madhyamgram', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '1490', 'LOCALITY_NAME': 'Sonarpur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '1490', 'LOCALITY_NAME': 'Sonarpur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '651', 'LOCALITY_NAME': 'Garia', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '651', 'LOCALITY_NAME': 'Garia', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '603', 'LOCALITY_NAME': 'EM Bypass', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '603', 'LOCALITY_NAME': 'EM Bypass', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '507', 'LOCALITY_NAME': 'Kestopur', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '507', 'LOCALITY_NAME': 'Kestopur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '1472', 'LOCALITY_NAME': 'Park Circus', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '1472', 'LOCALITY_NAME': 'Park Circus', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '8651', 'LOCALITY_NAME': 'Dum Dum Park', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '8651', 'LOCALITY_NAME': 'Dum Dum Park', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '528', 'LOCALITY_NAME': 'Madhyamgram', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '528', 'LOCALITY_NAME': 'Madhyamgram', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6839', 'LOCALITY_NAME': 'Thakurpukur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6839', 'LOCALITY_NAME': 'Thakurpukur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '31207', 'LOCALITY_NAME': 'Kabardanga', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '31207', 'LOCALITY_NAME': 'Kabardanga', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '5094', 'LOCALITY_NAME': 'Barasat', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '5094', 'LOCALITY_NAME': 'Barasat', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1495', 'LOCALITY_NAME': 'Rajarhat', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1495', 'LOCALITY_NAME': 'Rajarhat', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1495', 'LOCALITY_NAME': 'Rajarhat', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1495', 'LOCALITY_NAME': 'Rajarhat', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '603', 'LOCALITY_NAME': 'EM Bypass', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '3454', 'LOCALITY_NAME': 'Kalikapur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '3454', 'LOCALITY_NAME': 'Kalikapur', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1495', 'LOCALITY_NAME': 'Rajarhat', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '528', 'LOCALITY_NAME': 'Madhyamgram', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '528', 'LOCALITY_NAME': 'Madhyamgram', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '487', 'LOCALITY_NAME': 'Belgharia', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '487', 'LOCALITY_NAME': 'Belgharia', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '7998', 'LOCALITY_NAME': 'Chinar Park', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '7998', 'LOCALITY_NAME': 'Chinar Park', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1495', 'LOCALITY_NAME': 'Rajarhat', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1495', 'LOCALITY_NAME': 'Rajarhat', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '8599', 'LOCALITY_NAME': 'Chingrighata ', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '8599', 'LOCALITY_NAME': 'Chingrighata ', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '598', 'LOCALITY_NAME': 'Tollygunge', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '598', 'LOCALITY_NAME': 'Tollygunge', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '598', 'LOCALITY_NAME': 'Tollygunge', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6852', 'LOCALITY_NAME': 'Narendrapur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6852', 'LOCALITY_NAME': 'Narendrapur', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '1490', 'LOCALITY_NAME': 'Sonarpur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '1490', 'LOCALITY_NAME': 'Sonarpur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '21195', 'LOCALITY_NAME': 'Patuapara', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '844', 'LOCALITY_NAME': 'Joka', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '844', 'LOCALITY_NAME': 'Joka', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '844', 'LOCALITY_NAME': 'Joka', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6841', 'LOCALITY_NAME': 'Baruipur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6841', 'LOCALITY_NAME': 'Baruipur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6839', 'LOCALITY_NAME': 'Thakurpukur', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '7735', 'LOCALITY_NAME': 'Maheshtala', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '7735', 'LOCALITY_NAME': 'Maheshtala', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '484', 'LOCALITY_NAME': 'BT Road', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '484', 'LOCALITY_NAME': 'BT Road', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '484', 'LOCALITY_NAME': 'BT Road', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '5094', 'LOCALITY_NAME': 'Barasat', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '5094', 'LOCALITY_NAME': 'Barasat', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '5094', 'LOCALITY_NAME': 'Barasat', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6852', 'LOCALITY_NAME': 'Narendrapur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6852', 'LOCALITY_NAME': 'Narendrapur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6852', 'LOCALITY_NAME': 'Narendrapur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6841', 'LOCALITY_NAME': 'Baruipur', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '6841', 'LOCALITY_NAME': 'Baruipur', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '528', 'LOCALITY_NAME': 'Madhyamgram', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '528', 'LOCALITY_NAME': 'Madhyamgram', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '528', 'LOCALITY_NAME': 'Madhyamgram', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '844', 'LOCALITY_NAME': 'Joka', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '844', 'LOCALITY_NAME': 'Joka', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '844', 'LOCALITY_NAME': 'Joka', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '5086', 'LOCALITY_NAME': 'Ultadanga', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '5086', 'LOCALITY_NAME': 'Ultadanga', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '7998', 'LOCALITY_NAME': 'Chinar Park', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '7998', 'LOCALITY_NAME': 'Chinar Park', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'LOCALITY_ID': '1503', 'LOCALITY_NAME': 'New Town', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '543', 'LOCALITY_NAME': 'Salt Lake', 'ADDRESS': None}
{'CITY': '26', 'CITY_NAME': 'Kolkata North', 'LOCALITY_ID': '543', 'LOCALITY_NAME': 'Salt Lake', 'ADDRESS': None}
{'CITY': '29', 'CITY_NAME': 'Kolkata West', 'LOCALITY_ID': '8961', 'LOCALITY_NAME': 'Uttarpara', 'ADDRESS': None}
{'CITY': '29', 'CITY_NAME': 'Kolkata West', 'LOCALITY_ID': '8961', 'LOCALITY_NAME': 'Uttarpara', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '844', 'LOCALITY_NAME': 'Joka', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '844', 'LOCALITY_NAME': 'Joka', 'ADDRESS': None}
{'CITY': '27', 'CITY_NAME': 'Kolkata South', 'LOCALITY_ID': '844', 'LOCALITY_NAME': 'Joka', 'ADDRESS': None}

In [246]:
def extract_city_num(val):
    if pd.isna(val):
        return ""
    
    # Then safely parse the string
    try:
        parsed = ast.literal_eval(val)
    except (ValueError, SyntaxError):
        return ""

    for i in range(df["location"].shape[0]):
        return parsed.get("CITY")

def extract_locality_name(val):
    if pd.isna(val):
        return ""
    
    # Then safely parse the string
    try:
        parsed = ast.literal_eval(val)
    except (ValueError, SyntaxError):
        return ""

    for i in range(df["location"].shape[0]):
        return parsed.get("LOCALITY_NAME")

In [247]:
print(extract_city_num(df["location"][7]))
print(extract_locality_name(df["location"][7]))

26
Madhyamgram

In [248]:
df["CITY_NUM"] = df["location"].apply(extract_city_num)
df["LOCALITY"] = df["location"].apply(extract_locality_name)

In [249]:
df.head()

,PREFERENCE,DESCRIPTION,TRANSACT_TYPE,BEDROOM_NUM,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,AMENITIES,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT,PRICE_PER_SQFT(INR),OWNTYPE_label,LATITUDE,LONGITUDE,Cooperative Society,Power of Attorney,Other,Leasehold,FACING_LABEL,FACING_label_North,FACING_label_North-East,FACING_label_North-West,FACING_label_Other,FACING_label_South,FACING_label_South-East,FACING_label_South-West,FACING_label_West,FURNISH_LABEL,FURNISH_label_Other,FURNISH_label_Semi-furnished,FURNISH_label_Unfurnished,PROPERTY_type,PROPERTY_TYPE_Independent/Builder Floor,PROPERTY_TYPE_Residential Apartment,PROPERTY_TYPE_Residential Land,CITY_LABELS,CITY_Kolkata East,CITY_Kolkata North,CITY_Kolkata South,CITY_Kolkata West,LANDMARK_DETAILS,CITY_NUM,LOCALITY
0,S,Book your 2 BHK flat in Srijan Star Swapno Pur...,2.0,2.0,5,3.0,N,srijan star swapno puron,NaN,2 BHK Flat in Amtala,"['UNDER CONSTRUCTION', 'NEW BOOKING', 'RERA | ...",2.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.191000,570.5,3347.94,Cooperative Society,22.364447,88.274642,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0,"[Shopping, Hospital]",27,Amtala
1,S,Make Natural Quest your next home. This projec...,2.0,3.0,5,11.0,N,natural quest,NaN,3 BHK Flat in EM Bypass,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",9.0,"[{'category': 'MetroStation', 'text': '1 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.590000,1115.5,5289.11,Cooperative Society,22.518795,88.388439,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0,"[MetroStation, Shopping, Education, Hospital, ...",27,EM Bypass
2,S,"Book your 3 BHK apartment in Garia, Kolkata So...",2.0,3.0,5,20.0,N,ganguly 4sight eminence,NaN,3 BHK Flat in Garia,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",6.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.675000,1446.0,4668.05,Cooperative Society,22.513765,88.366680,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0,"[Shopping, Education, Hospital, Airport, Railw...",27,Garia
3,S,"Dev bhumi in joka, kolkata south by ocean land...",2.0,NaN,0,0.0,N,dev bhumi,NaN,Residential land / Plot in Joka,"['READY TO MOVE', 'NEW BOOKING']",13.0,"[{'category': 'MetroStation', 'text': '2 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,NaN,0.029950,1800.0,166.39,Cooperative Society,22.453830,88.249572,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Land,0,0,1,Kolkata South,0,0,1,0,"[MetroStation, Connectivity, Education, Hospital]",27,Joka
4,S,Let your dream of owning a flat come true with...,2.0,3.0,5,19.0,N,dtc sojon,NaN,3 BHK Flat in Joka,"['UNDER CONSTRUCTION', 'NEW BOOKING']",11.0,"[{'category': 'MetroStation', 'text': '1 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.375003,1295.0,2895.78,Cooperative Society,22.442130,88.295510,1,0,0,0,East,0,0,0,0,0,0,0,0,Unfurnished,0,0,1,Residential Apartment,0,1,0,Kolkata South,0,0,1,0,"[MetroStation, Shopping, Connectivity, Educati...",27,Joka

In [251]:
df.to_csv("D:\\CODING\\Virtual_py\\PROJECTS\\real_estate_ml\\backend\\kolkata.csv\\v2.csv", index= False)