In [94]:
import numpy as np
import pandas as pd

In [95]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [96]:
kolkata = pd.read_csv("D:\\CODING\\Virtual_py\\PROJECTS\\real_estate_ml\\backend\\kolkata.csv\\kolkata.csv")

In [97]:
kolkata.head()

,PROP_ID,PREFERENCE,DESCRIPTION,PROPERTY_TYPE,CITY,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,PRICE_PER_UNIT_AREA,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,PRICE_SQFT,MAP_DETAILS,AMENITIES,AREA,PRICE,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,SOCIETY_NAME,BUILDING_NAME,location,BALCONY_NUM,FLOOR_NUM,CARPET_SQFT,SUPERBUILTUP_SQFT,BUILTUP_SQFT,SUPER_AREA,SUPERAREA_UNIT,SUPER_SQFT
0,Y71306776,S,Book your 2 BHK flat in Srijan Star Swapno Pur...,Residential Apartment,Kolkata South,2.0,1,2.0,3662.0,0,0,5,3.0,N,Srijan Star Swapno Puron,3662.0,"{'LATITUDE': '22.364447', 'LONGITUDE': '88.274...",NaN,518-623 sq.ft.,19.1 L Onwards,2 BHK Flat in Amtala,"['UNDER CONSTRUCTION', 'NEW BOOKING', 'RERA | ...",2.0,"[{'category': 'Shopping', 'text': '1 Shopping'...",Srijan Star Swapno Puron,Srijan Star Swapno Puron,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,NaN,NaN,NaN,NaN,NaN,NaN
1,B70113976,S,Make Natural Quest your next home. This projec...,Residential Apartment,Kolkata South,2.0,1,3.0,10500.0,0,0,5,11.0,N,Natural Quest,10500.0,"{'LATITUDE': '22.518795', 'LONGITUDE': '88.388...",NaN,1110-1121 sq.ft.,1.17 - 1.18 Cr,3 BHK Flat in EM Bypass,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",9.0,"[{'category': 'MetroStation', 'text': '1 Metro...",Natural Quest,Natural Quest,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,NaN,NaN,NaN,NaN,NaN,NaN
2,O70374510,S,"Book your 3 BHK apartment in Garia, Kolkata So...",Residential Apartment,Kolkata South,2.0,1,3.0,8900.0,0,0,5,20.0,N,Ganguly 4Sight Eminence,8900.0,"{'LATITUDE': '22.5137646', 'LONGITUDE': '88.36...",NaN,1376-1516 sq.ft.,1.22 - 1.35 Cr,3 BHK Flat in Garia,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",6.0,"[{'category': 'Shopping', 'text': '1 Shopping'...",Ganguly 4Sight Eminence,Ganguly 4Sight Eminence,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,NaN,NaN,NaN,NaN,NaN,NaN
3,Q69170182,S,"Dev bhumi in joka, kolkata south by ocean land...",Residential Land,Kolkata South,2.0,1,NaN,208.0,0,0,0,0.0,N,Dev Bhumi,208.0,"{'LATITUDE': '22.45383', 'LONGITUDE': '88.2495...",NaN,720-2880 sq.ft.,1.5 - 5.99 L,Residential land / Plot in Joka,"['READY TO MOVE', 'NEW BOOKING']",13.0,"[{'category': 'MetroStation', 'text': '2 Metro...",Dev Bhumi,Dev Bhumi,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,F69917588,S,Let your dream of owning a flat come true with...,Residential Apartment,Kolkata South,2.0,1,3.0,5215.0,0,0,5,19.0,N,DTC Sojon,5215.0,"{'LATITUDE': '22.44213', 'LONGITUDE': '88.29551'}",NaN,1130-1460 sq.ft.,60 - 75 L,3 BHK Flat in Joka,"['UNDER CONSTRUCTION', 'NEW BOOKING']",11.0,"[{'category': 'MetroStation', 'text': '1 Metro...",DTC Sojon,DTC Sojon,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
df = kolkata.copy()
df.head(2)

,PROP_ID,PREFERENCE,DESCRIPTION,PROPERTY_TYPE,CITY,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,PRICE_PER_UNIT_AREA,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,PRICE_SQFT,MAP_DETAILS,AMENITIES,AREA,PRICE,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,SOCIETY_NAME,BUILDING_NAME,location,BALCONY_NUM,FLOOR_NUM,CARPET_SQFT,SUPERBUILTUP_SQFT,BUILTUP_SQFT,SUPER_AREA,SUPERAREA_UNIT,SUPER_SQFT
0,Y71306776,S,Book your 2 BHK flat in Srijan Star Swapno Pur...,Residential Apartment,Kolkata South,2.0,1,2.0,3662.0,0,0,5,3.0,N,Srijan Star Swapno Puron,3662.0,"{'LATITUDE': '22.364447', 'LONGITUDE': '88.274...",NaN,518-623 sq.ft.,19.1 L Onwards,2 BHK Flat in Amtala,"['UNDER CONSTRUCTION', 'NEW BOOKING', 'RERA | ...",2.0,"[{'category': 'Shopping', 'text': '1 Shopping'...",Srijan Star Swapno Puron,Srijan Star Swapno Puron,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,NaN,NaN,NaN,NaN,NaN,NaN
1,B70113976,S,Make Natural Quest your next home. This projec...,Residential Apartment,Kolkata South,2.0,1,3.0,10500.0,0,0,5,11.0,N,Natural Quest,10500.0,"{'LATITUDE': '22.518795', 'LONGITUDE': '88.388...",NaN,1110-1121 sq.ft.,1.17 - 1.18 Cr,3 BHK Flat in EM Bypass,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",9.0,"[{'category': 'MetroStation', 'text': '1 Metro...",Natural Quest,Natural Quest,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,NaN,NaN,NaN,NaN,NaN,NaN

In [99]:
df.columns

Index(['PROP_ID', 'PREFERENCE', 'DESCRIPTION', 'PROPERTY_TYPE', 'CITY',
       'TRANSACT_TYPE', 'OWNTYPE', 'BEDROOM_NUM', 'PRICE_PER_UNIT_AREA',
       'FURNISH', 'FACING', 'AGE', 'TOTAL_FLOOR', 'FEATURES', 'PROP_NAME',
       'PRICE_SQFT', 'MAP_DETAILS', 'AMENITIES', 'AREA', 'PRICE',
       'PROP_HEADING', 'SECONDARY_TAGS', 'TOTAL_LANDMARK_COUNT',
       'FORMATTED_LANDMARK_DETAILS', 'SOCIETY_NAME', 'BUILDING_NAME',
       'location', 'BALCONY_NUM', 'FLOOR_NUM', 'CARPET_SQFT',
       'SUPERBUILTUP_SQFT', 'BUILTUP_SQFT', 'SUPER_AREA', 'SUPERAREA_UNIT',
       'SUPER_SQFT'],
      dtype='str')

In [100]:
df.shape

(8797, 35)

In [101]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8797 entries, 0 to 8796
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PROP_ID                     8797 non-null   str
 1   PREFERENCE                  8797 non-null   str
 2   DESCRIPTION                 8797 non-null   str
 3   PROPERTY_TYPE               8797 non-null   str
 4   CITY                        8797 non-null   str
 5   TRANSACT_TYPE               7058 non-null   float64
 6   OWNTYPE                     8797 non-null   int64
 7   BEDROOM_NUM                 8311 non-null   float64
 8   PRICE_PER_UNIT_AREA         8797 non-null   float64
 9   FURNISH                     8797 non-null   int64
 10  FACING                      8797 non-null   int64
 11  AGE                         8797 non-null   int64
 12  TOTAL_FLOOR                 8745 non-null   float64
 13  FEATURES                    8797 non-null   str
 14  PROP_NAME                   8162 non-null   str
 15  PRICE_SQFT                  8797 non-null   float64
 16  MAP_DETAILS                 8797 non-null   str
 17  AMENITIES                   6744 non-null   str
 18  AREA                        8797 non-null   str
 19  PRICE                       8797 non-null   str
 20  PROP_HEADING                8797 non-null   str
 21  SECONDARY_TAGS              8797 non-null   str
 22  TOTAL_LANDMARK_COUNT        8574 non-null   float64
 23  FORMATTED_LANDMARK_DETAILS  8574 non-null   str
 24  SOCIETY_NAME                8162 non-null   str
 25  BUILDING_NAME               8149 non-null   str
 26  location                    8797 non-null   str
 27  BALCONY_NUM                 6653 non-null   float64
 28  FLOOR_NUM                   7817 non-null   str
 29  CARPET_SQFT                 2489 non-null   float64
 30  SUPERBUILTUP_SQFT           5400 non-null   float64
 31  BUILTUP_SQFT                1680 non-null   float64
 32  SUPER_AREA                  820 non-null    float64
 33  SUPERAREA_UNIT              820 non-null    str
 34  SUPER_SQFT                  833 non-null    float64
dtypes: float64(12), int64(4), str(19)
memory usage: 17.1 MB

In [102]:
df.duplicated().sum()

np.int64(0)

In [103]:
df.isnull().sum().sort_values(ascending=False).head(20)

SUPERAREA_UNIT                7977
SUPER_AREA                    7977
SUPER_SQFT                    7964
BUILTUP_SQFT                  7117
CARPET_SQFT                   6308
SUPERBUILTUP_SQFT             3397
BALCONY_NUM                   2144
AMENITIES                     2053
TRANSACT_TYPE                 1739
FLOOR_NUM                      980
BUILDING_NAME                  648
SOCIETY_NAME                   635
PROP_NAME                      635
BEDROOM_NUM                    486
TOTAL_LANDMARK_COUNT           223
FORMATTED_LANDMARK_DETAILS     223
TOTAL_FLOOR                     52
PROP_ID                          0
PREFERENCE                       0
DESCRIPTION                      0
dtype: int64

In [104]:
df.drop(columns = ["SUPERAREA_UNIT", "SUPER_AREA", "SUPER_SQFT", "BUILTUP_SQFT", "CARPET_SQFT", "SUPERBUILTUP_SQFT"], inplace = True)

In [105]:
df.sample(5)

,PROP_ID,PREFERENCE,DESCRIPTION,PROPERTY_TYPE,CITY,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,PRICE_PER_UNIT_AREA,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,PRICE_SQFT,MAP_DETAILS,AMENITIES,AREA,PRICE,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,SOCIETY_NAME,BUILDING_NAME,location,BALCONY_NUM,FLOOR_NUM
8510,Y57995238,S,"A 3 bhk apartment in alipore, kolkata south is...",Residential Apartment,Kolkata South,1.0,1,3.0,26763.0,2,7,5,42.0,"33,1,12,3,5,6,17,19,9,20,21,10",Tata 88 East,26763.0,"{'LATITUDE': '22.521668', 'LONGITUDE': '88.322...","5,17,20,21,10,1,6,19,9,33,12,3",1233 sq.ft.,3.3 Cr,3 BHK Flat in Alipore,"['UNDER CONSTRUCTION', 'RESALE', 'RERA | HIRA']",10.0,"[{'category': 'MetroStation', 'text': '1 Metro...",Tata 88 East,Tata 88 East,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",1.0,3
4391,O68141254,R,This 2 bhk flat in mukundapur is available in ...,Residential Apartment,Kolkata South,NaN,0,2.0,28.0,1,4,2,17.0,"44,33,23,45,12,24,25,47,26,17,19,1,3,5,6,9,40,...",Avidipta Housing Complex,28.0,"{'LATITUDE': '22.49236', 'LONGITUDE': '88.40865'}","17,5,20,21,44,23,45,24,47,19,1,6,9,40,41,33,12...",1347 sq.ft.,"38,000",2 BHK Flat in Mukundapur,['FURNISHED'],40.0,"[{'category': 'ReligiousPlace', 'text': '16 Re...",Avidipta Housing Complex,Avidipta Housing Complex,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",2.0,10
1880,T71205668,S,Enjoy a blissful living experience in DTC Capi...,Residential Apartment,Kolkata East,2.0,1,4.0,4741.0,0,0,5,20.0,N,DTC Capital City,4741.0,"{'LATITUDE': '22.562087130058', 'LONGITUDE': '...",NaN,1940 sq.ft.,91.98 L,4 BHK Flat in Rajarhat,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",6.0,"[{'category': 'Shopping', 'text': '1 Shopping'...",DTC Capital City,DTC Capital City,"{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'L...",NaN,1
6550,V64408244,S,Looking for a 4 bhk property for sale in kolka...,Residential Apartment,Kolkata South,1.0,1,4.0,12654.0,2,7,1,23.0,"23,24,5,17,6,19,20,21",Victoria Vistas,12654.0,"{'LATITUDE': '22.53566', 'LONGITUDE': '88.33917'}","5,17,20,21,23,24,6,19,101,102",3319 sq.ft.,4.2 Cr,4 BHK Flat in Bhawanipore,"['READY TO MOVE', 'RESALE', 'RERA | HIRA']",13.0,"[{'category': 'MetroStation', 'text': '1 Metro...",Victoria Vistas,Victoria Vistas,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",1.0,6
2564,C71425258,S,Experience a new style of living with DTC Capi...,Residential Apartment,Kolkata East,2.0,1,4.0,4742.0,0,0,5,20.0,N,DTC Capital City,4742.0,"{'LATITUDE': '22.562087130058', 'LONGITUDE': '...",NaN,1940 sq.ft.,92 L,4 BHK Flat in Rajarhat,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",6.0,"[{'category': 'Shopping', 'text': '1 Shopping'...",DTC Capital City,DTC Capital City,"{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'L...",NaN,1

In [106]:
print(df["PRICE_PER_UNIT_AREA"] == df["PRICE_SQFT"])

0        True
1        True
2        True
3        True
4        True
5        True
6        True
7        True
8        True
9        True
10       True
11       True
12       True
13       True
14       True
15       True
16       True
17       True
18       True
19       True
20       True
21       True
22       True
23       True
24       True
25       True
26       True
27       True
28       True
29       True
30       True
31       True
32       True
33       True
34       True
35       True
36       True
37       True
38       True
39       True
40       True
41       True
42       True
43       True
44       True
45       True
46       True
47       True
48       True
49       True
50       True
51       True
52       True
53       True
54       True
55       True
56       True
57       True
58       True
59       True
60       True
61       True
62       True
63       True
64       True
65       True
66       True
67       True
68       True
69       True
70       True
71       True
72       True
73       True
74       True
75       True
76       True
77       True
78       True
79       True
80       True
81       True
82       True
83       True
84       True
85       True
86       True
87       True
88       True
89       True
90       True
91       True
92       True
93       True
94       True
95       True
96       True
97       True
98       True
99       True
100      True
101      True
102      True
103      True
104      True
105      True
106      True
107      True
108      True
109      True
110      True
111      True
112      True
113      True
114      True
115      True
116      True
117      True
118      True
119      True
120      True
121      True
122      True
123      True
124      True
125      True
126      True
127      True
128      True
129      True
130      True
131      True
132      True
133      True
134      True
135      True
136      True
137      True
138      True
139      True
140      True
141      True
142      True
143      True
144      True
145      True
146      True
147      True
148      True
149      True
150      True
151      True
152      True
153      True
154      True
155      True
156      True
157      True
158      True
159      True
160      True
161      True
162      True
163      True
164      True
165      True
166      True
167      True
168      True
169      True
170      True
171      True
172      True
173      True
174      True
175      True
176      True
177      True
178      True
179      True
180      True
181      True
182      True
183      True
184      True
185      True
186      True
187      True
188      True
189      True
190      True
191      True
192      True
193      True
194      True
195      True
196      True
197      True
198      True
199      True
200      True
201      True
202      True
203      True
204      True
205      True
206      True
207      True
208      True
209      True
210      True
211      True
212      True
213      True
214      True
215      True
216      True
217      True
218      True
219      True
220      True
221      True
222      True
223      True
224      True
225      True
226      True
227      True
228      True
229      True
230      True
231      True
232      True
233      True
234      True
235      True
236      True
237      True
238      True
239      True
240      True
241      True
242      True
243      True
244      True
245      True
246      True
247      True
248      True
249      True
250      True
251      True
252      True
253      True
254      True
255      True
256      True
257      True
258      True
259      True
260      True
261      True
262      True
263      True
264      True
265      True
266      True
267      True
268      True
269      True
270      True
271      True
272      True
273      True
274      True
275      True
276      True
277      True
278      True
279      True
280      True
281      True
282      True
283      True
284      True
285      True
286      True
287      True
288      True
289      True
290      True
291      True
292      True
293      True
294      True
295      True
296      True
297      True
298      True
299      True
300      True
301      True
302      True
303      True
304      True
305      True
306      True
307      True
308      True
309      True
310      True
311      True
312      True
313      True
314      True
315      True
316      True
317      True
318      True
319      True
320      True
321      True
322      True
323      True
324      True
325      True
326      True
327      True
328      True
329      True
330      True
331      True
332      True
333      True
334      True
335      True
336      True
337      True
338      True
339      True
340      True
341      True
342      True
343      True
344      True
345      True
346      True
347      True
348      True
349      True
350      True
351      True
352      True
353      True
354      True
355      True
356      True
357      True
358      True
359      True
360      True
361      True
362      True
363      True
364      True
365      True
366      True
367      True
368      True
369      True
370      True
371      True
372      True
373      True
374      True
375      True
376      True
377      True
378      True
379      True
380      True
381      True
382      True
383      True
384      True
385      True
386      True
387      True
388      True
389      True
390      True
391      True
392      True
393      True
394      True
395      True
396      True
397      True
398      True
399      True
400      True
401      True
402      True
403      True
404      True
405      True
406      True
407      True
408      True
409      True
410      True
411      True
412      True
413      True
414      True
415      True
416      True
417      True
418      True
419      True
420      True
421      True
422      True
423      True
424      True
425      True
426      True
427      True
428      True
429      True
430      True
431      True
432      True
433      True
434      True
435      True
436      True
437      True
438      True
439      True
440      True
441      True
442      True
443      True
444      True
445      True
446      True
447      True
448      True
449      True
450      True
451      True
452      True
453      True
454      True
455      True
456      True
457      True
458      True
459      True
460      True
461      True
462      True
463      True
464      True
465      True
466      True
467      True
468      True
469      True
470      True
471      True
472      True
473      True
474      True
475      True
476      True
477      True
478      True
479      True
480      True
481      True
482      True
483      True
484      True
485      True
486      True
487      True
488      True
489      True
490      True
491      True
492      True
493      True
494      True
495      True
496      True
497      True
498      True
499      True
500      True
501      True
502      True
503      True
504      True
505      True
506      True
507      True
508      True
509      True
510      True
511      True
512      True
513      True
514      True
515      True
516      True
517      True
518      True
519      True
520      True
521      True
522      True
523      True
524      True
525      True
526      True
527      True
528      True
529      True
530      True
531      True
532      True
533      True
534      True
535      True
536      True
537      True
538      True
539      True
540      True
541      True
542      True
543      True
544      True
545      True
546      True
547      True
548      True
549      True
550      True
551      True
552      True
553      True
554      True
555      True
556      True
557      True
558      True
559      True
560      True
561      True
562      True
563      True
564      True
565      True
566      True
567      True
568      True
569      True
570      True
571      True
572      True
573      True
574      True
575      True
576      True
577      True
578      True
579      True
580      True
581      True
582      True
583      True
584      True
585      True
586      True
587      True
588      True
589      True
590      True
591      True
592      True
593      True
594      True
595      True
596      True
597      True
598      True
599      True
600      True
601      True
602      True
603      True
604      True
605      True
606      True
607      True
608      True
609      True
610      True
611      True
612      True
613      True
614      True
615      True
616      True
617      True
618      True
619      True
620      True
621      True
622      True
623      True
624      True
625      True
626      True
627      True
628      True
629      True
630      True
631      True
632      True
633      True
634      True
635      True
636      True
637      True
638      True
639      True
640      True
641      True
642      True
643      True
644      True
645      True
646      True
647      True
648      True
649      True
650      True
651      True
652      True
653      True
654      True
655      True
656      True
657      True
658      True
659      True
660      True
661      True
662      True
663      True
664      True
665      True
666      True
667      True
668      True
669      True
670      True
671      True
672      True
673      True
674      True
675      True
676      True
677      True
678      True
679      True
680      True
681      True
682      True
683      True
684      True
685      True
686      True
687      True
688      True
689      True
690      True
691      True
692      True
693      True
694      True
695      True
696      True
697      True
698      True
699      True
700      True
701      True
702      True
703      True
704      True
705      True
706      True
707      True
708      True
709      True
710      True
711      True
712      True
713      True
714      True
715      True
716      True
717      True
718      True
719      True
720      True
721      True
722      True
723      True
724      True
725      True
726      True
727      True
728      True
729      True
730      True
731      True
732      True
733      True
734      True
735      True
736      True
737      True
738      True
739      True
740      True
741      True
742      True
743      True
744      True
745      True
746      True
747      True
748      True
749      True
750      True
751      True
752      True
753      True
754      True
755      True
756      True
757      True
758      True
759      True
760      True
761      True
762      True
763      True
764      True
765      True
766      True
767      True
768      True
769      True
770      True
771      True
772      True
773      True
774      True
775      True
776      True
777      True
778      True
779      True
780      True
781      True
782      True
783      True
784      True
785      True
786      True
787      True
788      True
789      True
790      True
791      True
792      True
793      True
794      True
795      True
796      True
797      True
798      True
799      True
800      True
801      True
802      True
803      True
804      True
805      True
806      True
807      True
808      True
809      True
810      True
811      True
812      True
813      True
814      True
815      True
816      True
817      True
818      True
819      True
820      True
821      True
822      True
823      True
824      True
825      True
826      True
827      True
828      True
829      True
830      True
831      True
832      True
833      True
834      True
835      True
836      True
837      True
838      True
839      True
840      True
841      True
842      True
843      True
844      True
845      True
846      True
847      True
848      True
849      True
850      True
851      True
852      True
853      True
854      True
855      True
856      True
857      True
858      True
859      True
860      True
861      True
862      True
863      True
864      True
865      True
866      True
867      True
868      True
869      True
870      True
871      True
872      True
873      True
874      True
875      True
876      True
877      True
878      True
879      True
880      True
881      True
882      True
883      True
884      True
885      True
886      True
887      True
888      True
889      True
890      True
891      True
892      True
893      True
894      True
895      True
896      True
897      True
898      True
899      True
900      True
901      True
902      True
903      True
904      True
905      True
906      True
907      True
908      True
909      True
910      True
911      True
912      True
913      True
914      True
915      True
916      True
917      True
918      True
919      True
920      True
921      True
922      True
923      True
924      True
925      True
926      True
927      True
928      True
929      True
930      True
931      True
932      True
933      True
934      True
935      True
936      True
937      True
938      True
939      True
940      True
941      True
942      True
943      True
944      True
945      True
946      True
947      True
948      True
949      True
950      True
951      True
952      True
953      True
954      True
955      True
956      True
957      True
958      True
959      True
960      True
961      True
962      True
963      True
964      True
965      True
966      True
967      True
968      True
969      True
970      True
971      True
972      True
973      True
974      True
975      True
976      True
977      True
978      True
979      True
980      True
981      True
982      True
983      True
984      True
985      True
986      True
987      True
988      True
989      True
990      True
991      True
992      True
993      True
994      True
995      True
996      True
997      True
998      True
999      True
1000     True
1001     True
1002     True
1003     True
1004     True
1005     True
1006     True
1007     True
1008     True
1009     True
1010     True
1011     True
1012     True
1013     True
1014     True
1015     True
1016     True
1017     True
1018     True
1019     True
1020     True
1021     True
1022     True
1023     True
1024     True
1025     True
1026     True
1027     True
1028     True
1029     True
1030     True
1031     True
1032     True
1033     True
1034     True
1035     True
1036     True
1037     True
1038     True
1039     True
1040     True
1041     True
1042     True
1043     True
1044     True
1045     True
1046     True
1047     True
1048     True
1049     True
1050     True
1051     True
1052     True
1053     True
1054     True
1055     True
1056     True
1057     True
1058     True
1059     True
1060     True
1061     True
1062     True
1063     True
1064     True
1065     True
1066     True
1067     True
1068     True
1069     True
1070     True
1071     True
1072     True
1073     True
1074     True
1075     True
1076     True
1077     True
1078     True
1079     True
1080     True
1081     True
1082     True
1083     True
1084     True
1085     True
1086     True
1087     True
1088     True
1089     True
1090     True
1091     True
1092     True
1093     True
1094     True
1095     True
1096     True
1097     True
1098     True
1099     True
1100     True
1101     True
1102     True
1103     True
1104     True
1105     True
1106     True
1107     True
1108     True
1109     True
1110     True
1111     True
1112     True
1113     True
1114     True
1115     True
1116     True
1117     True
1118     True
1119     True
1120     True
1121     True
1122     True
1123     True
1124     True
1125     True
1126     True
1127     True
1128     True
1129     True
1130     True
1131     True
1132     True
1133     True
1134     True
1135     True
1136     True
1137     True
1138     True
1139     True
1140     True
1141     True
1142     True
1143     True
1144     True
1145     True
1146     True
1147     True
1148     True
1149     True
1150     True
1151     True
1152     True
1153     True
1154     True
1155     True
1156     True
1157     True
1158     True
1159     True
1160     True
1161     True
1162     True
1163     True
1164     True
1165     True
1166     True
1167     True
1168     True
1169     True
1170     True
1171     True
1172     True
1173     True
1174     True
1175     True
1176     True
1177     True
1178     True
1179     True
1180     True
1181     True
1182     True
1183     True
1184     True
1185     True
1186     True
1187     True
1188     True
1189     True
1190     True
1191     True
1192     True
1193     True
1194     True
1195     True
1196     True
1197     True
1198     True
1199     True
1200     True
1201     True
1202     True
1203     True
1204     True
1205     True
1206     True
1207     True
1208     True
1209     True
1210     True
1211     True
1212     True
1213     True
1214     True
1215     True
1216     True
1217     True
1218     True
1219     True
1220     True
1221     True
1222     True
1223     True
1224     True
1225     True
1226     True
1227     True
1228     True
1229     True
1230     True
1231     True
1232     True
1233     True
1234     True
1235     True
1236     True
1237     True
1238     True
1239     True
1240     True
1241     True
1242     True
1243     True
1244     True
1245     True
1246     True
1247     True
1248     True
1249     True
1250     True
1251     True
1252     True
1253     True
1254     True
1255     True
1256     True
1257     True
1258     True
1259     True
1260     True
1261     True
1262     True
1263     True
1264     True
1265     True
1266     True
1267     True
1268     True
1269     True
1270     True
1271     True
1272     True
1273     True
1274     True
1275     True
1276     True
1277     True
1278     True
1279     True
1280     True
1281     True
1282     True
1283     True
1284     True
1285     True
1286     True
1287     True
1288     True
1289     True
1290     True
1291     True
1292     True
1293     True
1294     True
1295     True
1296     True
1297     True
1298     True
1299     True
1300     True
1301     True
1302     True
1303     True
1304     True
1305     True
1306     True
1307     True
1308     True
1309     True
1310     True
1311     True
1312     True
1313     True
1314     True
1315     True
1316     True
1317     True
1318     True
1319     True
1320     True
1321     True
1322     True
1323     True
1324     True
1325     True
1326     True
1327     True
1328     True
1329     True
1330     True
1331     True
1332     True
1333     True
1334     True
1335     True
1336     True
1337     True
1338     True
1339     True
1340     True
1341     True
1342     True
1343     True
1344     True
1345     True
1346     True
1347     True
1348     True
1349     True
1350     True
1351     True
1352     True
1353     True
1354     True
1355     True
1356     True
1357     True
1358     True
1359     True
1360     True
1361     True
1362     True
1363     True
1364     True
1365     True
1366     True
1367     True
1368     True
1369     True
1370     True
1371     True
1372     True
1373     True
1374     True
1375     True
1376     True
1377     True
1378     True
1379     True
1380     True
1381     True
1382     True
1383     True
1384     True
1385     True
1386     True
1387     True
1388     True
1389     True
1390     True
1391     True
1392     True
1393     True
1394     True
1395     True
1396     True
1397     True
1398     True
1399     True
1400     True
1401     True
1402     True
1403     True
1404     True
1405     True
1406     True
1407     True
1408     True
1409     True
1410     True
1411     True
1412     True
1413     True
1414     True
1415     True
1416     True
1417     True
1418     True
1419     True
1420     True
1421     True
1422     True
1423     True
1424     True
1425     True
1426     True
1427     True

In [107]:
np.sum(df["PRICE_PER_UNIT_AREA"] == df["PRICE_SQFT"])

np.int64(8796)

In [108]:
len(df["PRICE_PER_UNIT_AREA"])

8797

In [109]:
# as the "PRICE_SQFT" and "PRICE_PER_UNIT_AREA" are same we delete one 
df.drop(columns = ["PRICE_SQFT"], inplace = True)

In [110]:
np.sum(df["FEATURES"] == df["AMENITIES"])

np.int64(565)

In [111]:
# dropping prop id

df.drop(columns = ["PROP_ID"], inplace = True)

In [112]:
df.columns

df.sample(5)

,PREFERENCE,DESCRIPTION,PROPERTY_TYPE,CITY,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,PRICE_PER_UNIT_AREA,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,MAP_DETAILS,AMENITIES,AREA,PRICE,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,SOCIETY_NAME,BUILDING_NAME,location,BALCONY_NUM,FLOOR_NUM
2729,S,This lovely 2 bhk apartment/flat in prafulla k...,Residential Apartment,Kolkata North,1.0,1,2.0,4200.0,2,3,5,5.0,"44,23,24,47,5,19,40,41,21,32",subho Apartment.kestopur.kolkats,"{'LATITUDE': '22.715388', 'LONGITUDE': '88.378...","5,21,32,44,23,24,47,19,40,41,102,103",928 sq.ft.,38.98 L,2 BHK Flat in Prafulla Kanan,"['UNDER CONSTRUCTION', 'RESALE']",25.0,"[{'category': 'ReligiousPlace', 'text': '1 Rel...",subho Apartment.kestopur.kolkats,subho Apartment.kestopur.kolkats,"{'CITY': '26', 'CITY_NAME': 'Kolkata North', '...",1.0,2
745,S,Let your dream of owning a flat come true with...,Residential Apartment,Kolkata East,2.0,1,3.0,13046.0,0,0,6,23.0,N,Anik One Rajarhat,"{'LATITUDE': '22.581199', 'LONGITUDE': '88.461...",NaN,1878-2073 sq.ft.,2.45 - 2.7 Cr,3 BHK Flat in New Town,"['READY TO MOVE', 'NEW BOOKING', 'RERA | HIRA']",15.0,"[{'category': 'MetroStation', 'text': '1 Metro...",Anik One Rajarhat,Anik One Rajarhat,"{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'L...",NaN,1
6057,S,Welcome to aashay home - Where your dream life...,Residential Land,Kolkata South,1.0,1,NaN,694.0,0,2,0,3.0,"23,24,5",Aashay Home,"{'LATITUDE': '22.4439029807', 'LONGITUDE': '88...","5,23,24",1440 sq.ft.,10 L,Residential land / Plot in Joka,"['WBIDCL APPROVED', 'IN GATED COMMUNITY', 'REA...",12.0,"[{'category': 'Hospital', 'text': '10 Hospital...",Aashay Home,Aashay Home,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,NaN
6246,R,On request is one of kolkata east's most sough...,Residential Apartment,Kolkata East,NaN,0,2.0,14.0,2,5,1,4.0,"24,17,6,21",On request,"{'LATITUDE': '22.574199', 'LONGITUDE': '88.474...","17,21,24,6,101,102",1000 sq.ft.,"14,000",2 BHK Flat in New Town Action Area 1D,"['FOR SINGLE MEN', 'FOR SINGLE WOMEN']",35.0,"[{'category': 'MetroStation', 'text': '1 Metro...",On request,On request,"{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'L...",1.0,4
1053,S,Experience a new style of living with Bhawani ...,Residential Apartment,Kolkata East,2.0,1,3.0,8275.0,0,0,5,13.0,N,Bhawani Inara,"{'LATITUDE': '22.626586', 'LONGITUDE': '88.453...",NaN,1728 sq.ft.,1.43 Cr,3 BHK Flat in New Town,"['UNDER CONSTRUCTION', 'NEW BOOKING', 'RERA | ...",13.0,"[{'category': 'MetroStation', 'text': '1 Metro...",Bhawani Inara,Bhawani Inara,"{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'L...",NaN,1

In [113]:
df["PREFERENCE"].unique()

<ArrowStringArray>
['S', 'P', 'R']
Length: 3, dtype: str

In [114]:
df["PROPERTY_TYPE"].unique()

<ArrowStringArray>
[    'Residential Apartment',          'Residential Land',
   'Independent House/Villa', 'Independent/Builder Floor']
Length: 4, dtype: str

In [115]:
df["CITY"].unique()

<ArrowStringArray>
[  'Kolkata South',   'Kolkata North', 'Kolkata Central',    'Kolkata East',
    'Kolkata West']
Length: 5, dtype: str

In [116]:
df.isnull().sum().sort_values(ascending=False).head(20)

BALCONY_NUM                   2144
AMENITIES                     2053
TRANSACT_TYPE                 1739
FLOOR_NUM                      980
BUILDING_NAME                  648
PROP_NAME                      635
SOCIETY_NAME                   635
BEDROOM_NUM                    486
FORMATTED_LANDMARK_DETAILS     223
TOTAL_LANDMARK_COUNT           223
TOTAL_FLOOR                     52
AGE                              0
FACING                           0
FURNISH                          0
PRICE_PER_UNIT_AREA              0
OWNTYPE                          0
CITY                             0
DESCRIPTION                      0
PROPERTY_TYPE                    0
PREFERENCE                       0
dtype: int64

In [117]:
df["PREFERENCE"].value_counts()

PREFERENCE
S    7060
R    1354
P     383
Name: count, dtype: int64

In [118]:
df[["PRICE"]].dtypes

PRICE    str
dtype: object

In [119]:
df["PRICE"].value_counts()

PRICE
75 L                 106
65 L                 101
25,000                89
45 L                  83
85 L                  83
80 L                  73
55 L                  71
70 L                  70
42 L                  67
35 L                  67
32 L                  67
60 L                  65
20,000                63
30 L                  62
50 L                  61
1.3 Cr                58
35,000                58
40 L                  57
1.1 Cr                57
90 L                  56
22,000                55
18,000                54
95 L                  54
28 L                  52
30,000                49
15,000                49
72 L                  47
1 Cr                  46
1.4 Cr                44
17,000                44
1.5 Cr                44
1.2 Cr                42
48 L                  42
1.35 Cr               41
25 L                  39
52 L                  39
36 L                  38
38 L                  37
16,000                37
58 L                  36
68 L                  36
78 L                  36
12,000                36
Price on Request      35
1.05 Cr               35
1.15 Cr               35
3 Cr                  34
45,000                34
1.25 Cr               34
2.5 Cr                33
23 L                  32
13,000                32
23,000                32
28,000                32
26 L                  31
37 L                  30
82 L                  30
24 L                  29
22 L                  29
46 L                  29
1.45 Cr               29
10,000                29
2.2 Cr                28
56 L                  28
27 L                  28
4,000/Bed             28
26,000                28
1.6 Cr                28
34 L                  27
14,000                27
1.65 Cr               27
40,000                26
92 L                  25
3,000/Bed             25
63 L                  25
62 L                  25
5,000/Bed             24
43 L                  24
33 L                  24
50,000                23
67 L                  21
51 L                  21
4 Cr                  21
64 L                  21
53 L                  20
20 L                  20
41 L                  20
55,000                20
21 L                  20
1.9 Cr                20
24,000                20
39 L                  19
70,000                19
21,000                19
11,000                19
1.55 Cr               19
2,500/Bed             18
31 L                  18
66 L                  18
44 L                  18
49 L                  18
57 L                  18
54 L                  18
1.75 Cr               17
29 L                  17
2 Cr                  17
1.8 Cr                17
76 L                  17
27,000                17
32,000                17
83 L                  17
2.5 L                 17
47 L                  16
1.7 Cr                16
1.85 Cr               16
1.32 Cr               16
15 L                  15
2.6 Cr                15
18 L                  15
3,500/Bed             15
8,500                 15
88 L                  15
19,000                15
69 L                  14
1.43 Cr               14
2.3 Cr                14
2.1 Cr                14
42,000                14
3.5 Cr                14
8,000                 14
6,500/Bed             14
87 L                  13
1.5 L                 13
71 L                  13
1 L                   13
2.7 Cr                13
19 L                  12
1.02 Cr               12
59 L                  12
60,000                12
2.25 Cr               12
7,500                 12
21.5 L                12
73 L                  12
6,000/Bed             12
75  - 90 L            11
28.5 L                11
31.5 L                11
5,000/Bedroom         11
61 L                  11
12,500                11
74 L                  11
17 L                  11
89 L                  11
5 L                   11
16.5 L                11
23.5 L                11
64.12 L               10
1.74  - 1.96 Cr       10
16 L                  10
58.5  - 64.19 L       10
4,500/Bed             10
4,000/Bedroom         10
22.5 L                10
77 L                  10
69.25 L - 1.21 Cr     10
1.28 Cr               10
1.26 Cr               10
18,500                10
12 L                  10
86 L                  10
90,000                10
65,000                10
1.07 Cr               10
80,000                10
16,500                10
5,500/Bed             10
48  - 82 L             9
10,000/Bed             9
6,000/Bedroom          9
8,000/Bed              9
1.29  - 1.4 Cr         9
51.75 L                9
6 Cr                   9
2.8 Cr                 9
32.5 L                 9
4.2 Cr                 9
1.42 Cr                9
5.5 L                  9
12.5 L                 9
96 L                   9
9,000                  9
1.18 Cr                9
4.25 Cr                9
75,000                 9
98 L                   9
1.12 Cr                9
60  - 75 L             8
29.5 L                 8
47  - 63.86 L          8
51  - 55 L             8
64.86  - 84.75 L       8
1.27 Cr                8
17.5 L                 8
19.5 L                 8
74  - 85.96 L          8
53  - 65.67 L          8
40  - 70.72 L          8
27.5 L                 8
36,000                 8
34,000                 8
33,000                 8
84 L                   8
45  - 49 L             7
22.88  - 26 L          7
2.8  - 2.84 Cr         7
1.15  - 1.44 Cr        7
39.6 L                 7
3.25 Cr                7
75.09 L - 1.02 Cr      7
58.01  - 59.11 L       7
5.1 Cr                 7
2.96  - 3.05 Cr        7
1.85  - 2.49 Cr        7
2,800/Bed              7
2,000/Bed              7
3  - 3.82 Cr           7
2.3  - 2.9 Cr          7
1.01  - 1.52 Cr        7
90 L - 1.01 Cr         7
7,500/Bed              7
38,000                 7
1.43  - 1.5 Cr         7
81 L                   7
1.01 Cr                7
45.5 L                 7
26.5 L                 7
20.5 L                 7
1.16 Cr                7
2.45 Cr                7
7.5 L                  7
42.5 L                 7
3.6 Cr                 7
49.5 L                 7
2.35 Cr                7
2.85 Cr                7
1.06 Cr                7
1.17 Cr                7
17,500                 7
10,000/Bedroom         7
53  - 58.48 L          6
4.27 Cr                6
35.65 L                6
47.5 L Onwards         6
66.18  - 76.18 L       6
1.72  - 2.09 Cr        6
1.52  - 2.05 Cr        6
1.41 Cr                6
1.11 Cr                6
1.36 Cr                6
1.66 Cr                6
40.5 L                 6
2.65 Cr                6
2.4 Cr                 6
1.52 Cr                6
5 Cr                   6
13.75 L                6
97 L                   6
10,500                 6
43.5 L                 6
9,500                  6
5.5 Cr                 6
7,000                  6
24.5 L                 6
2 L                    6
3.3 Cr                 6
2.15 Cr                6
11,500                 6
1.34 Cr                6
2.75 Cr                6
2.9 Cr                 6
9,000/Bed              6
41  - 47.25 L          5
1.39  - 1.81 Cr        5
2.65  - 3.21 Cr        5
63 L Onwards           5
36.5 L                 5
1.22 Cr                5
1.72 Cr                5
1.34  - 1.66 Cr        5
2.46  - 3.41 Cr        5
1.24 Cr                5
1.68  - 1.75 Cr        5
69  - 90.5 L           5
37  - 38.45 L          5
68.88 L                5
47.5 L                 5
1.23 Cr                5
1.67 Cr                5
3.2 Cr                 5
1.83  - 1.86 Cr        5
1.43  - 1.48 Cr        5
9 L                    5
15.5 L                 5
1.21 Cr                5
13,500                 5
46,000                 5
25.5 L                 5
13 L                   5
20,500                 5
85,000                 5
32.4 L                 5
11.5 L                 5
1.48 Cr                5
48,000                 5
38.5 L                 5
32.11 L                5
99 L                   5
10 L                   5
1.95 Cr                5
32.3 L                 5
31,000                 5
3.1 Cr                 5
22.1 L                 5
3.8 Cr                 5
10 Cr                  5
34.4 L                 5
15,000/Bed             5
3,000/Bedroom          5
7,000/Bedroom          5
11,000/Bed             4
78.82  - 95.66 L       4
66  - 76.18 L          4
85  - 97.22 L          4
58.5 L                 4
1.43  - 1.43 Cr        4
29.4 L                 4
49.16  - 58.32 L       4
35.5 L                 4
4.99  - 7.52 Cr        4
1.31  - 1.48 Cr        4
3.1  - 4.35 Cr         4
2.81 Cr                4
3,500/Bedroom          4
53.69  - 71.12 L       4
1.14  - 1.28 Cr        4
2.29 Cr                4
68.49  - 76.86 L       4
54.41  - 54.94 L       4
47  - 48.66 L          4
1.82 Cr                4
2.45  - 2.7 Cr         4
1.74 Cr                4
54 L Onwards           4
41 L Onwards           4
1.8  - 2.1 Cr          4
1.08  - 1.21 Cr        4
59.1  - 63 L           4
44.69  - 53.24 L       4
85 L Onwards           4
41  - 44 L             4
79 L                   4
1.4  - 1.41 Cr         4
64.5 L                 4
1.39  - 1.48 Cr        4
96.5 L - 1.22 Cr       4
67.5 L                 4
78.53  - 98.89 L       4
76.06 L                4
58.52  - 77.51 L       4
1.32  - 1.76 Cr        4
22.75 L                4
1.38 Cr                4
47.38 L                4
57.07  - 64.26 L       4
39.35  - 56.29 L       4
25.38  - 65.88 L       4
2.46 Cr                4
3 L                    4
1.56 Cr                4
13.7 L                 4
14 L                   4
2.75 L                 4
38.85 L                4
95,000                 4
1.29 Cr                4
53,000                 4
93 L                   4
6,000                  4
1.04 Cr                4
1.1 L                  4
1.2 L                  4
4.5 Cr                 4
1.47 Cr                4
3.05 Cr                4
50.5 L                 4
4.6 Cr                 4
25.92 L                4
4.75 Cr                4
26.1 L                 4
2.8 L                  4
3.2 L                  4
18.4 L                 4
27.72 L                4
15,500                 4
14,500                 4
1.3 L                  4
2.55 Cr                4
94 L                   4
3.75 Cr                4
33.6 L                 4
25.9 L                 4
38.43 L                4
17.55 L                4
8 Cr                   4
5,500/Bedroom          4
12,000/Bed             4
8,000/Bedroom          4
2,600/Bed              4
1,500/Bed              4
7,000/Bed              4
1.5  - 5.99 L          3
38.45 L                3
41.06  - 41.79 L       3
31.94  - 33.41 L       3
24.4  - 26.37 L        3
10  - 50 L             3
1.46 Cr                3
33.65  - 33.76 L       3
24  - 27.19 L          3
2.94 Cr                3
1.4  - 1.44 Cr         3
1.11  - 1.12 Cr        3
55 L Onwards           3
58  - 59.1 L           3
51.3  - 54.67 L        3
40.09  - 40.61 L       3
2.72 Cr                3
50.47  - 63.86 L       3
2.9  - 4.95 Cr         3
44.5 L                 3
12,000/Bedroom         3
6.5 Cr                 3
44.9 L                 3
45.26  - 47 L          3
78.82  - 99.59 L       3
2,700/Bed              3
69.25 L                3
5.2 Cr                 3
73.13 L - 2.18 Cr      3
98.73 L - 1.11 Cr      3
67.33  - 81.72 L       3
51  - 71.12 L          3
3.63 Cr                3
70.83 L                3
23,001                 3
52.32 L                3
48 L Onwards           3
39.65 L Onwards        3
56  - 56 L             3
40.5  - 40.5 L         3
39  - 40.52 L          3
87  - 88.01 L          3
75  - 75.88 L          3
2.2  - 2.94 Cr         3
1.85  - 2.04 Cr        3
45  - 49.09 L          3
98.8 L                 3
1.99 Cr                3
65.79 L                3
46.3  - 80.89 L        3
1.83 Cr                3
1.15  - 1.45 Cr        3
3.68  - 3.94 Cr        3
2.96 Cr                3
31.83 L                3
23.87 L                3
4.46  - 4.8 Cr         3
3.36  - 3.59 Cr        3
2.47  - 2.65 Cr        3
80.6 L                 3
59.87  - 63.41 L       3
43.44  - 52.23 L       3
53.98  - 80.89 L       3
24.08 L                3
1.49 Cr                3
1.75 L                 3
73  - 73.85 L          3
78.53 L - 1.32 Cr      3
48.5 L                 3
31.92 L                3
1.12  - 1.22 Cr        3
79.48  - 82.67 L       3
26.11 L                3
36.48  - 36.7 L        3
30.49  - 33.63 L       3
28,500                 3
1.17  - 1.23 Cr        3
70  - 81.36 L          3
39.2 L                 3
1.05  - 1.29 Cr        3
93.51  - 97.95 L       3
34.63  - 36.07 L       3
23,500                 3
1.1 Cr Onwards         3
11 L                   3
41.5 L                 3
26.25 L                3
1.31 Cr                3
14.2 L                 3
5.25 L                 3
3.45 Cr                3
46.8 L                 3
5,000                  3
8.25 L                 3
6,500                  3
64.63 L                3
5.4 Cr                 3
24,500                 3
30.5 L                 3
6.25 L                 3
5.2 L                  3
52.5 L                 3
63.8 L                 3
31.28 L                3
37.67 L                3
47.58 L                3
1.08 Cr                3
97.5 L                 3
3.9 Cr                 3
65.5 L                 3
39.5 L                 3
3.7 Cr                 3
1.77 Cr                3
4.6 L                  3
6 L                    3
1.8 L                  3
4 L                    3
1.6 L                  3
18.5 L                 3
1.14 Cr                3
53.5 L                 3
76.5 L                 3
71.5 L                 3
33.54 L                3
46.5 L                 3
66.5 L                 3
8 L                    3
2.58 Cr                3
33.72 L                3
3.95 Cr                3
13.5 L                 3
29,500                 3
55.5 L                 3
37.4 L                 3
34.92 L                3
35.1 L                 3
27,500                 3
50.4 L                 3
3.65 Cr                3
20.92 L                3
36.48 L                3
40.59 L                3
29.7 L                 3
45.6 L                 3
1.62 Cr                3
25.44 L                3
27.65 L                3
9 Cr                   3
25,000/Bed             3
4,400/Bed              3
4,500/Bedroom          3
6,500/Bedroom          3
2,200/Bed              3
7,500/Bedroom          3
26.92 L                3
17.51 L                3
28.09 L                3
55.28 L                3
1.8  - 5.4 L           2
1.01  - 1.08 Cr        2
68.76  - 81.6 L        2
54.78  - 64.98 L       2
1.26  - 1.26 Cr        2
34.03  - 34.94 L       2
26.58  - 28.38 L       2
37.94 L                2
32.76 L                2
56.97  - 58.51 L       2
57  - 57.95 L          2
82.56  - 95.63 L       2
58.76  - 67.45 L       2
68  - 78.12 L          2
19.69  - 22.47 L       2
46.45 L                2
32.01  - 32.34 L       2
5.91 Cr                2
24.9 L                 2
53.51  - 59.49 L       2
41.99  - 43.42 L       2
35.07 L                2
20.58 L                2
71  - 73.78 L          2
90.5 L                 2
1.36  - 1.41 Cr        2
26.78 L                2
14.5 L                 2
56.4 L                 2
65.34 L                2
52.02  - 65.79 L       2
52.15 L                2
85.75  - 96.84 L       2
60.51 L                2
46.55  - 55.33 L       2
33.66  - 41.36 L       2
1.13 Cr                2
51.6 L                 2
37.75  - 54.74 L       2
35  - 40.83 L          2
98.67 L                2
4.65 Cr                2
1.92 Cr                2
1.75  - 1.93 Cr        2
1.36  - 1.47 Cr        2
97.85 L - 1.27 Cr      2
3,600/Bed              2
24.48  - 25.16 L       2
11,000/Bedroom         2
1.79 Cr                2
47.03  - 66.72 L       2
46.99  - 54.29 L       2
51.54  - 57.95 L       2
3,300/Bed              2
81.76 L                2
58.54  - 77.54 L       2
54.36  - 54.59 L       2
46.3 L                 2
49.6  - 57.25 L        2
58.01  - 59.1 L        2
3.1  - 3.57 Cr         2
23.9 L                 2
53.7 L                 2
31.46 L                2
46.3  - 84.96 L        2
1.21  - 1.38 Cr        2
89 L - 1.06 Cr         2
1.24  - 2.19 Cr        2
64.86 L                2
58.01 L                2
2.01 Cr                2
1.52  - 1.88 Cr        2
63.62  - 67.6 L        2
35.84  - 45.11 L       2
29.38  - 34.35 L       2
20,200                 2
2.26  - 2.26 Cr        2
1.72  - 1.84 Cr        2
63.09 L Onwards        2
67.14 L                2
63.79 L Onwards        2
93.9 L - 1.1 Cr        2
94.32 L - 1.74 Cr      2
60  - 77.53 L          2
89.7 L - 1.12 Cr       2
76  - 76.83 L          2
42.3  - 46.3 L         2
42.35  - 60.06 L       2
36.74  - 49.04 L       2
47.32  - 53.75 L       2
73.82 L - 1.02 Cr      2
74  - 78.01 L          2
45  - 65 L             2
75.99 L                2
49.16 L                2
45.64  - 54.07 L       2
1.33 Cr                2
70  - 72.75 L          2
2.96  - 3.02 Cr        2
1.12  - 1.37 Cr        2
40.42  - 41.84 L       2
51  - 56 L             2
32.37 L                2
1.65  - 1.66 Cr        2
90.01 L - 1.33 Cr      2
70  - 84.42 L          2
99.94 L - 1.32 Cr      2
1.29  - 1.39 Cr        2
16.1 L                 2
52.61  - 71.59 L       2
96.75 L - 1.58 Cr      2
44.8 L                 2
29.25 L                2
41.42 L                2
1.35  - 4.06 L         2
29.9 L                 2
39,000                 2
78 L - 1.28 Cr         2
56 L Onwards           2
29.45 L                2
34.88 L                2
44.25  - 47.47 L       2
29.35  - 42.4 L        2
52.1 L Onwards         2
42.85 L Onwards        2
24.01  - 29.34 L       2
38.21  - 39.2 L        2
19,500                 2
50.92 L                2
24.6 L Onwards         2
16.6 L Onwards         2
22.4 L                 2
25.15 L                2
5.51 L                 2
27.93 L                2
64 L Onwards           2
18.95 L                2
31.41 L Onwards        2
21.78 L Onwards        2
1.27  - 1.28 Cr        2
82.78  - 89.62 L       2
1.09  - 1.11 Cr        2
80  - 81.07 L          2
26.55 L                2
77.72 L                2
65  - 79.7 L           2
5.24 L                 2
6.88 L                 2
1.93 Cr                2
1.03 Cr                2
72.5 L                 2
42.8 L                 2
8.25 Cr                2
2.3 L                  2
27.8 L                 2
1.29  - 1.34 Cr        2
93.99 L - 1.18 Cr      2
29.9  - 39.17 L        2
14.85  - 14.95 L       2
55.65 L                2
21.6 L                 2
10.5 Cr                2
79.5 L                 2
62.5 L                 2
2.05 Cr                2
14.8 L                 2
27.9 L                 2
20.44 L                2
58.44 L                2
35.43 L                2
4.1 Cr                 2
5,500                  2
25.65 L                2
44.35 L                2
36.1 L                 2
39.9 L                 2
48.7 L                 2
30.75 L                2
28.14 L                2
16.39 L                2
27.34 L                2
3.85 Cr                2
5.52 L                 2
5.53 L                 2
5.6 L                  2
43.2 L                 2
36.08 L                2
38.55 L                2
54.9 L                 2
51.08 L                2
58.3 L                 2
18.75 L                2
21.76 L                2
2.85 L                 2
1.9 L                  2
3.6 L                  2
24.61 L                2
32.14 L                2
18.7 L                 2
90.72 L                2
91 L                   2
11,900                 2
1.51 Cr                2
7.5 Cr                 2
1.59 Cr                2
75.36 L                2
17.36 L                2
3.15 Cr                2
83.5 L                 2
2.15 L                 2
1.99 L                 2
2.39 L                 2
1.25 L                 2
1.35 L                 2
22.78 L                2
21.45 L                2
37.5 L                 2
56.5 L                 2
15,999                 2
33.75 L                2

In [120]:
import pandas as pd
import re

def convert_price_to_cr(price_str):
    if pd.isna(price_str):
        return None
    
    price_str = str(price_str).replace(",", "").strip()
    
    # Handle ranges (take average)
    if "-" in price_str:
        parts = price_str.split("-")
        values = [convert_price_to_cr(p.strip()) for p in parts]
        return sum(values) / len(values) if all(values) else None
    
    # Crores
    if "Cr" in price_str:
        num = re.findall(r"[\d\.]+", price_str)
        return float(num[0]) if num else None
    
    # Lakhs
    if "L" in price_str:
        num = re.findall(r"[\d\.]+", price_str)
        return float(num[0]) / 100 if num else None
    
    # Per Bedroom / Bed (rental values → convert to Cr)
    if "/Bedroom" in price_str or "/Bed" in price_str:
        num = re.findall(r"[\d\.]+", price_str)
        return float(num[0]) / 1e7 if num else None
    
    # Plain number (₹)
    num = re.findall(r"[\d\.]+", price_str)
    return float(num[0]) / 1e7 if num else None

# Apply to your DataFrame
df["PRICE_Cr"] = df["PRICE"].apply(convert_price_to_cr)

print(df[["PRICE", "PRICE_Cr"]].head(20))

               PRICE  PRICE_Cr
0     19.1 L Onwards  0.191000
1    1.17  - 1.18 Cr  0.590000
2    1.22  - 1.35 Cr  0.675000
3      1.5  - 5.99 L  0.029950
4         60  - 75 L  0.375003
5         45  - 49 L  0.245002
6    90.85 L Onwards  0.908500
7               39 L  0.390000
8   52.64  - 60.16 L  0.300803
9    41.6  - 41.83 L  0.209152
10      1.8  - 5.4 L  0.027000
11        11,000/Bed  0.001100
12      42  - 43.4 L  0.217002
13           80.03 L  0.800300
14  50.69  - 52.28 L  0.261403
15  36.97  - 42.48 L  0.212402
16           27.28 L  0.272800
17   1.29  - 1.59 Cr  0.795000
18              92 L  0.920000
19        48  - 82 L  0.410002

In [121]:
df.sample(5)

,PREFERENCE,DESCRIPTION,PROPERTY_TYPE,CITY,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,PRICE_PER_UNIT_AREA,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,MAP_DETAILS,AMENITIES,AREA,PRICE,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,SOCIETY_NAME,BUILDING_NAME,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr
1812,R,"Fully secured with club, gym and swimming pool...",Residential Apartment,Kolkata East,NaN,0,3.0,19.0,1,0,3,19.0,"33,1,12,3,25,6,9,20,21",Uniworld City,"{'LATITUDE': '22.5599444', 'LONGITUDE': '88.49...","20,21,1,6,9,33,12,3,25,103",1768 sq.ft.,"40,000",3 BHK Flat in New Town,"['FURNISHED', 'FOR SINGLE MEN', 'FOR SINGLE WO...",13.0,"[{'category': 'ATM', 'text': '2 ATMs', 'classN...",Uniworld City,Uniworld City,"{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'L...",2.0,19,0.0040
8090,S,Booking going on\nGreen project (G+12) hig bul...,Residential Apartment,Kolkata East,1.0,1,3.0,4615.0,2,7,5,12.0,"44,33,23,12,24,25,26,17,19,1,3,5,6,8,9,40,30,4...",On Request,"{'LATITUDE': '22.569', 'LONGITUDE': '88.510296'}","17,5,8,20,21,44,23,24,19,1,6,9,40,30,41,33,12,...",1625 sq.ft.,75 L,3 BHK Flat in Action Area 3,"['UNDER CONSTRUCTION', 'RESALE']",11.0,"[{'category': 'ATM', 'text': '2 ATMs', 'classN...",On Request,On Request,"{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'L...",2.0,9,0.7500
1686,S,Near noapara metro station 2 km away.,Independent/Builder Floor,Kolkata North,1.0,1,1.0,3444.0,4,3,2,4.0,"24,19,40,21",NaN,"{'LATITUDE': '22.636815', 'LONGITUDE': '88.412...","21,24,19,40,103",450 sq.ft.,15.5 L,1 BHK Independent Builder Floor in Dum Dum Cantt,"['READY TO MOVE', 'RESALE']",48.0,"[{'category': 'MetroStation', 'text': '1 Metro...",NaN,NaN,"{'CITY': '26', 'CITY_NAME': 'Kolkata North', '...",0.0,3,0.1550
2090,S,"Book your 3 BHK flat in Kamalgazi, Kolkata Sou...",Residential Apartment,Kolkata South,2.0,1,3.0,4200.0,0,0,6,4.0,N,Ananth,"{'LATITUDE': '22.446293', 'LONGITUDE': '88.392...",NaN,1271 sq.ft.,53.38 L,3 BHK Flat in Kamalgazi,"['READY TO MOVE', 'NEW BOOKING']",15.0,"[{'category': 'MetroStation', 'text': '2 Metro...",Ananth,Ananth,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.5338
553,S,"This 2 bhk flat is located in sd aqua view, wh...",Residential Apartment,Kolkata North,1.0,1,2.0,4181.0,4,0,1,5.0,"23,6,20,21",SD Aqua View,"{'LATITUDE': '22.675382', 'LONGITUDE': '88.459...","20,21,23,6,103",861 sq.ft.,36 L,2 BHK Flat in Airport,"['READY TO MOVE', 'RESALE', 'RERA | HIRA']",15.0,"[{'category': 'Shopping', 'text': '1 Shopping'...",SD Aqua View,SD Aqua View,"{'CITY': '26', 'CITY_NAME': 'Kolkata North', '...",1.0,4,0.3600

In [122]:
# df["PRICE_Cr"].nunique()
df["PRICE_Cr"].shape

(8797,)

In [123]:
df["PRICE_PER_UNIT_AREA"].value_counts()

PRICE_PER_UNIT_AREA
4500.0         109
16.0           104
4000.0         102
15.0            93
18.0            90
20.0            86
12.0            81
17.0            81
3500.0          71
5000.0          67
4200.0          64
14.0            61
22.0            59
21.0            57
19.0            55
23.0            54
13.0            53
10.0            52
6000.0          51
3800.0          51
3000.0          51
25.0            51
11.0            46
5500.0          42
3400.0          41
3600.0          40
27.0            38
24.0            38
5200.0          37
3200.0          35
5.0             34
1486.0          33
26.0            33
28.0            32
7.0             31
2.0             30
0.0             29
10000.0         29
2500.0          29
4800.0          28
4100.0          28
3.0             28
30.0            27
4.0             26
35.0            26
3700.0          25
6.0             25
1.0             25
4615.0          22
8000.0          22
9.0             22
29.0            22
3250.0          21
2700.0          21
8.0             21
33.0            21
7500.0          20
347.0           20
31.0            19
4700.0          18
36.0            18
3100.0          18
34.0            18
5600.0          16
3750.0          16
3550.0          16
7000.0          16
6200.0          16
32.0            16
319.0           16
3300.0          15
3900.0          15
6250.0          15
2800.0          15
2600.0          14
9000.0          14
15216.0         14
40.0            14
4166.0          13
6081.0          13
6500.0          13
3333.0          13
381.0           13
6666.0          13
38.0            13
5100.0          12
4742.0          12
6362.0          12
4600.0          12
3650.0          12
7881.0          12
5212.0          12
2300.0          12
833.0           12
8673.0          11
5351.0          11
4854.0          11
6800.0          11
5555.0          11
5058.0          10
8759.0          10
5875.0          10
4250.0          10
8501.0          10
2400.0          10
7400.0          10
50.0            10
277.0           10
694.0           10
7300.0           9
7100.0           9
7920.0           9
6080.0           9
4850.0           9
12235.0          9
5333.0           9
3789.0           9
4984.0           9
5953.0           9
5750.0           9
13700.0          9
4444.0           9
3099.0           9
5215.0           8
7551.0           8
9330.0           8
6300.0           8
5800.0           8
4545.0           8
10066.0          8
10769.0          8
5837.0           8
9660.0           8
9434.0           8
9574.0           8
4884.0           8
4995.0           8
8275.0           8
42.0             8
5300.0           8
4705.0           8
5833.0           8
37.0             8
2900.0           8
9500.0           8
44.0             8
6850.0           8
5108.0           7
4535.0           7
5849.0           7
4400.0           7
12000.0          7
45.0             7
6329.0           7
12223.0          7
4750.0           7
4300.0           7
7404.0           7
14031.0          7
5900.0           7
5700.0           7
2000.0           7
4379.0           7
2777.0           7
346.0            7
5882.0           7
3599.0           7
43.0             7
8637.0           6
6094.0           6
7209.0           6
14765.0          6
16182.0          6
7878.0           6
7402.0           6
7406.0           6
13402.0          6
2750.0           6
5250.0           6
6220.0           6
7727.0           6
4333.0           6
7142.0           6
3888.0           6
6451.0           6
60.0             6
13758.0          6
4608.0           6
7855.0           6
7419.0           6
6540.0           6
10029.0          6
9960.0           6
11008.0          6
4994.0           6
7200.0           6
6400.0           6
6111.0           6
138.0            6
48.0             6
4782.0           6
5416.0           6
4796.0           6
278.0            6
222.0            6
5727.0           6
4583.0           6
208.0            5
4239.0           5
250.0            5
8804.0           5
6897.0           5
4109.0           5
13544.0          5
6296.0           5
4375.0           5
5714.0           5
11812.0          5
3372.0           5
6166.0           5
7857.0           5
600000.0         5
8333.0           5
2916.0           5
14443.0          5
10450.0          5
11623.0          5
8700.0           5
5132.0           5
5032.0           5
5114.0           5
8691.0           5
6521.0           5
2100.0           5
13118.0          5
5440.0           5
4861.0           5
5400.0           5
4550.0           5
4266.0           5
58.0             5
3208.0           5
3478.0           5
39.0             5
9722.0           5
5384.0           5
4363.0           5
12500.0          5
6100.0           5
4666.0           5
5954.0           5
250000.0         5
4661.0           5
4090.0           5
7160.0           5
3595.0           5
5405.0           5
41.0             5
66.0             5
3454.0           4
3819.0           4
9619.0           4
3594.0           4
10180.0          4
6115.0           4
3571.0           4
6022.0           4
4227.0           4
4777.0           4
5172.0           4
17964.0          4
16079.0          4
4494.0           4
7777.0           4
3684.0           4
5655.0           4
6190.0           4
3932.0           4
6758.0           4
8587.0           4
8856.0           4
8176.0           4
4360.0           4
3043.0           4
3166.0           4
6043.0           4
11811.0          4
13046.0          4
12672.0          4
6030.0           4
9614.0           4
9895.0           4
9570.0           4
5017.0           4
8012.0           4
10657.0          4
4425.0           4
5308.0           4
4934.0           4
7525.0           4
5507.0           4
8905.0           4
5858.0           4
3644.0           4
3555.0           4
6444.0           4
4195.0           4
5309.0           4
350000.0         4
4977.0           4
6181.0           4
2666.0           4
5738.0           4
5752.0           4
4307.0           4
3956.0           4
4609.0           4
3480.0           4
4285.0           4
4651.0           4
4270.0           4
3230.0           4
5951.0           4
8500.0           4
3937.0           4
3529.0           4
5140.0           4
7870.0           4
65.0             4
194.0            4
4761.0           4
7391.0           4
13888.0          4
4900.0           4
3990.0           4
5375.0           4
3181.0           4
9500000.0        4
8593.0           4
4102.0           4
550000.0         4
5338.0           4
5454.0           4
8421.0           4
5037.0           4
5625.0           4
4117.0           4
5652.0           4
5680.0           4
16666.0          4
2450.0           4
6933.0           4
7083.0           4
6215.0           4
1437.0           4
1487.0           4
10500.0          3
3520.0           3
4632.0           3
6527.0           3
9550.0           3
8506.0           3
12222.0          3
3997.0           3
9014.0           3
1389.0           3
3950.0           3
9496.0           3
3714.0           3
5650.0           3
9079.0           3
7099.0           3
3616.0           3
4951.0           3
5999.0           3
6440.0           3
7291.0           3
3363.0           3
5818.0           3
9363.0           3
6149.0           3
7891.0           3
3488.0           3
6818.0           3
4004.0           3
3504.0           3
3925.0           3
4570.0           3
3020.0           3
4642.0           3
5204.0           3
4181.0           3
4849.0           3
5126.0           3
7730.0           3
8864.0           3
8965.0           3
8881.0           3
5845.0           3
5040.0           3
12794.0          3
6206.0           3
10526.0          3
4864.0           3
4674.0           3
3720.0           3
46.0             3
11984.0          3
3428.0           3
7399.0           3
10426.0          3
4601.0           3
7417.0           3
16523.0          3
13623.0          3
8125.0           3
11235.0          3
20000.0          3
5718.0           3
6796.0           3
6944.0           3
9615.0           3
5995.0           3
6021.0           3
5647.0           3
8888.0           3
3090.0           3
3666.0           3
5901.0           3
4127.0           3
3499.0           3
7944.0           3
7462.0           3
7374.0           3
7239.0           3
7204.0           3
5349.0           3
2000000.0        3
5703.0           3
4620.0           3
2962.0           3
8876.0           3
7738.0           3
5142.0           3
11348.0          3
11387.0          3
4870.0           3
3516.0           3
4937.0           3
5720.0           3
6437.0           3
6639.0           3
4650.0           3
3506.0           3
7748.0           3
2857.0           3
5188.0           3
5092.0           3
4461.0           3
5148.0           3
14072.0          3
4480.0           3
2941.0           3
12040.0          3
10509.0          3
3904.0           3
382.0            3
3282.0           3
10902.0          3
3474.0           3
6506.0           3
5531.0           3
5924.0           3
3066.0           3
3974.0           3
7222.0           3
4923.0           3
4508.0           3
3636.0           3
2745.0           3
52.0             3
3703.0           3
7912.0           3
6199.0           3
6852.0           3
6333.0           3
3571428.0        3
14000.0          3
6696428.0        3
4489.0           3
3699.0           3
4473.0           3
3652.0           3
56.0             3
166.0            3
685000.0         3
1666.0           3
11000.0          3
7032.0           3
51.0             3
6744.0           3
4932.0           3
12087.0          3
5029.0           3
4727.0           3
3098.0           3
6761.0           3
4179.0           3
2950.0           3
5514.0           3
4640.0           3
6719.0           3
380.0            3
13194.0          3
4047.0           3
3058.0           3
16832.0          3
3854.0           3
3902.0           3
4196.0           3
3411.0           3
10514.0          3
5673.0           3
7894.0           3
4571.0           3
300000.0         3
5737.0           3
5615.0           3
10869.0          3
9411.0           3
10140.0          3
8631.0           3
10909.0          3
8928.0           3
8571.0           3
5909.0           3
3604.0           3
3850.0           3
3375.0           3
6785.0           3
7393.0           3
5666.0           3
7666666.0        3
3555555.0        3
5043.0           3
4857.0           3
3664.0           3
3111.0           3
6956.0           3
6048.0           3
5194.0           3
2914.0           3
4099.0           3
6060.0           3
4933.0           3
6153.0           3
6875.0           3
3541.0           3
5892.0           3
5034.0           3
5174.0           3
5294.0           3
11254.0          3
47.0             3
5733.0           3
3326.0           3
6222.0           3
320.0            3
7048.0           2
3581.0           2
6178.0           2
7265.0           2
6831.0           2
4075.0           2
4044.0           2
4316.0           2
14404.0          2
5099.0           2
10305.0          2
9579.0           2
1215.0           2
7873.0           2
6937.0           2
4193.0           2
3899.0           2
3926.0           2
3625.0           2
4688.0           2
3862.0           2
10542.0          2
6492.0           2
3827.0           2
2687.0           2
9468.0           2
9612.0           2
5922.0           2
14187.0          2
11225.0          2
10726.0          2
8041.0           2
7418.0           2
12727.0          2
3818.0           2
9901.0           2
6880.0           2
3399.0           2
5722.0           2
8866.0           2
4218.0           2
5191.0           2
5684.0           2
4278.0           2
3209.0           2
3777.0           2
5687.0           2
5365.0           2
6906.0           2
2649.0           2
2712.0           2
4062.0           2
10476.0          2
8468.0           2
4210.0           2
5391.0           2
3199.0           2
3614.0           2
5813.0           2
7101.0           2
6205.0           2
5277.0           2
4069.0           2
4074.0           2
3221.0           2
4610.0           2
1805.0           2
2850.0           2
2833.0           2
12306.0          2
20392.0          2
5855.0           2
10923.0          2
5490.0           2
3895.0           2
4848.0           2
6690.0           2
9880.0           2
8862.0           2
11981.0          2
2909.0           2
5518.0           2
7296.0           2
10651.0          2
10053.0          2
1583333.0        2
7507.0           2
5139.0           2
8444.0           2
3157.0           2
4735.0           2
4660.0           2
14696.0          2
9815.0           2
5310.0           2
3524.0           2
3607.0           2
5982.0           2
13043.0          2
6046.0           2
9230.0           2
6578.0           2
7380.0           2
8362.0           2
11200.0          2
3333333.0        2
7623.0           2
10192.0          2
8308.0           2
3295.0           2
7987.0           2
6129.0           2
3475.0           2
9356.0           2
6410.0           2
5090.0           2
4464.0           2
5238.0           2
4470.0           2
3586.0           2
5444.0           2
14591.0          2
10037.0          2
10160.0          2
8873.0           2
9947.0           2
13458.0          2
7394.0           2
11841.0          2
12548.0          2
5113.0           2
7065.0           2
15821.0          2
6597.0           2
4352.0           2
3101.0           2
3764.0           2
9677.0           2
4662.0           2
7951.0           2
7964.0           2
15202.0          2
3245.0           2
5861.0           2
4750000.0        2
10313.0          2
5267.0           2
2955.0           2
6663.0           2
2714.0           2
3771.0           2
6832.0           2
9047.0           2
188.0            2
9214.0           2
3955.0           2
3782.0           2
10240.0          2
14144.0          2
8696.0           2
9231.0           2
4659.0           2
10033.0          2
8140.0           2
7996.0           2
13013.0          2
3444.0           2
5185.0           2
3979.0           2
4308.0           2
5275.0           2
16694.0          2
6105.0           2
6688.0           2
4929.0           2
4910.0           2
2345.0           2
4741.0           2
3907.0           2
4132.0           2
3297.0           2
10835.0          2
3859.0           2
4523.0           2
972.0            2
6570.0           2
13951.0          2
3325.0           2
5527.0           2
3470.0           2
5348.0           2
6923.0           2
4334.0           2
8175.0           2
13601.0          2
8511.0           2
5617.0           2
3996.0           2
7235.0           2
5829.0           2
6965.0           2
7281.0           2
6371.0           2
4206.0           2
349.0            2
3545.0           2
4588.0           2
3498.0           2
5565.0           2
5701.0           2
3355.0           2
60000.0          2
6132.0           2
2903.0           2
5428.0           2
3194.0           2
8234.0           2
7906.0           2
3303.0           2
3292.0           2
4111.0           2
4150.0           2
11300.0          2
3495.0           2
18333.0          2
3329.0           2
9035.0           2
234.0            2
10932.0          2
4710.0           2
14909.0          2
14319.0          2
350.0            2
6072.0           2
7366071.0        2
5555555.0        2
6621.0           2
7569.0           2
2978.0           2
9393.0           2
2066.0           2
5591.0           2
3812.0           2
5572.0           2
3913.0           2
3450.0           2
14705.0          2
7660.0           2
4400000.0        2
5016.0           2
7052.0           2
20000000.0       2
5732.0           2
7978.0           2
61333.0          2
4125.0           2
3195.0           2
23650.0          2
6642.0           2
5487.0           2
12968.0          2
5866.0           2
9352.0           2
6637.0           2
13803.0          2
4888.0           2
3507.0           2
5669.0           2
1664.0           2
5666666.0        2
417.0            2
4212.0           2
6593.0           2
5894.0           2
12249.0          2
3513.0           2
5986.0           2
3680.0           2
7586.0           2
9565.0           2
9139.0           2
7153.0           2
7600.0           2
8426.0           2
5102.0           2
4539.0           2
7094.0           2
4722.0           2
6838.0           2
12086.0          2
20833.0          2
6071.0           2
6228.0           2
5642.0           2
9823.0           2
3642.0           2
6357.0           2
4636.0           2
4493.0           2
7392.0           2
4476.0           2
6366.0           2
16250.0          2
6324.0           2
6454.0           2
6499.0           2
2546.0           2
7509.0           2
5138.0           2
370.0            2
255.0            2
305.0            2
388.0            2
275000.0         2
6201.0           2
3673.0           2
12307.0          2
3085.0           2
6285.0           2
5723.0           2
13333333.0       2
10000000.0       2
12000000.0       2
3896.0           2
4199.0           2
3055.0           2
5921.0           2
5451.0           2
2906.0           2
6904.0           2
1875.0           2
7129.0           2
7155.0           2
5622.0           2
3026.0           2
395.0            2
263.0            2
4871.0           2
4907.0           2
6486.0           2
6779.0           2
4960.0           2
8527.0           2
9818.0           2
2990.0           2
8360.0           2
6109.0           2
7808.0           2
7862.0           2
2992.0           2
3034.0           2
2937.0           2
2775.0           2
7547.0           2
7040.0           2
5342.0           2
9523.0           2
8641.0           2
4785.0           2
9620.0           2
6346.0           2
4521.0           2
4305.0           2
6203.0           2
6001.0           2
3345.0           2
5595.0           2
7692.0           2
6397.0           2
3385.0           2
8139.0           2
6571.0           2
4133.0           2
8378.0           2
4897.0           2
7800.0           2
5773.0           2
4586.0           2
4432.0           2
6299.0           2
8528.0           2
12155.0          2
6226.0           2
7470.0           2
7714.0           2
8200.0           2
6557.0           2
6739.0           2
6968.0           2
298.0            2
276.0            2
331.0            2
361.0            2
178.0            2
4324.0           2
3272.0           2
4005.0           2
9740.0           2
5976.0           2
4281.0           2
3521.0           2
3548.0           2
4646.0           2
5319.0           2
4731.0           2
2439.0           2
2652.0           2
3641.0           2
2343.0           2
11259.0          2
6725.0           2
6182.0           2
5836.0           2
10571.0          2
9090.0           2
4986.0           2
4941.0           2
8056.0           2
5981.0           2
4017.0           2
9259.0           2
6715.0           2
6152.0           2
6000000.0        2
3500000.0        2
6232.0           2
7632.0           2
7333333.0        2
3644444.0        2
5111111.0        2
5789.0           2
7743.0           2
4347.0           2
4821.0           2
4205.0           2
4173.0           2
12544.0          2
4016.0           2
5760.0           2
10224.0          2
5050.0           2
5887.0           2
3125.0           2
4795.0           2
5568.0           2
3396.0           2
3796.0           2
7854.0           2
3440.0           2
80000.0          2
110000.0         2
3164.0           2
5080.0           2
5124.0           2
4772.0           2
3496.0           2
2571.0           2
4333333.0        2
3010.0           2
4880.0           2
4568.0           2
3255.0           2
4299.0           2
15128.0          2
4604.0           2
6746.0           2
4901.0           2
5925.0           2
3285.0           2
6782.0           2
4142.0           2
6341.0           2
11963.0          2
5952.0           2
9954.0           2
7826.0           2
9375.0           2
9583.0           2
10508.0          2
8108.0           2
18000.0          2
5325.0           2
4814.0           2

In [124]:
print(df.dtypes)

PREFERENCE                        str
DESCRIPTION                       str
PROPERTY_TYPE                     str
CITY                              str
TRANSACT_TYPE                 float64
OWNTYPE                         int64
BEDROOM_NUM                   float64
PRICE_PER_UNIT_AREA           float64
FURNISH                         int64
FACING                          int64
AGE                             int64
TOTAL_FLOOR                   float64
FEATURES                          str
PROP_NAME                         str
MAP_DETAILS                       str
AMENITIES                         str
AREA                              str
PRICE                             str
PROP_HEADING                      str
SECONDARY_TAGS                    str
TOTAL_LANDMARK_COUNT          float64
FORMATTED_LANDMARK_DETAILS        str
SOCIETY_NAME                      str
BUILDING_NAME                     str
location                          str
BALCONY_NUM                   float64
FLOOR_NUM                         str
PRICE_Cr                      float64
dtype: object

In [125]:
df["AREA"].value_counts()

def convert_area(area_str):
    if pd.isna(area_str):
        return None
    
    # Remove commas and unit
    area_str = str(area_str).replace(",", "").replace("sq.ft.", "").strip()
    
    # Handle ranges
    if "-" in area_str:
        parts = re.findall(r"[\d\.]+", area_str)
        if len(parts) == 2:
            return (float(parts[0]) + float(parts[1])) / 2
        else:
            return None
    
    # Single value
    num = re.findall(r"[\d\.]+", area_str)
    return float(num[0]) if num else None

# Apply to your DataFrame
df["AREA_SQFT"] = df["AREA"].apply(convert_area)

In [126]:
df.sample(2)

,PREFERENCE,DESCRIPTION,PROPERTY_TYPE,CITY,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,PRICE_PER_UNIT_AREA,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,MAP_DETAILS,AMENITIES,AREA,PRICE,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,SOCIETY_NAME,BUILDING_NAME,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT
3430,R,3bhk 2bath 1balcony with 1coverd parking flat ...,Residential Apartment,Kolkata North,NaN,0,3.0,119.0,1,5,1,24.0,"23,1,12,24,3,5,6,19,20,21",Merlin 5th Avenue,"{'LATITUDE': '22.567901', 'LONGITUDE': '88.446...","5,20,21,23,1,24,6,19,12,3,101,102,103",756 sq.ft.,"90,000",3 BHK Flat in Salt Lake,['FURNISHED'],15.0,"[{'category': 'Shopping', 'text': '4 Shoppings...",Merlin 5th Avenue,Merlin 5th Avenue,"{'CITY': '26', 'CITY_NAME': 'Kolkata North', '...",1.0,10,0.009,756.0
4132,S,A nice property in bunglow type house in good ...,Independent House/Villa,Kolkata South,1.0,1,7.0,9264705.0,2,7,3,2.0,"23,26,5,19,8",NaN,"{'LATITUDE': '22.5050813878', 'LONGITUDE': '88...","5,8,23,19,26,103",2447 sq.ft.,3.15 Cr,7 Bedroom House in Lake Gardens,"['READY TO MOVE', 'RESALE']",50.0,"[{'category': 'MetroStation', 'text': '1 Metro...",NaN,NaN,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",2.0,NaN,3.150,2447.0

In [127]:
# Assuming PRICE_Cr is your cleaned price column (in Crores)
# Convert Crores back to INR for per sqft calculation
df["PRICE_INR"] = df["PRICE_Cr"] * 1e7   # 1 Cr = 10,000,000 INR

# Recalculate price per unit area (₹ per sqft)
df["PRICE_PER_SQFT"] = df["PRICE_INR"] / df["AREA_SQFT"]

# print(df[["PRICE", "PRICE_Cr", "AREA_SQFT", "PRICE_PER_UNIT_AREA"]].head(10))
df.sample(5)

,PREFERENCE,DESCRIPTION,PROPERTY_TYPE,CITY,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,PRICE_PER_UNIT_AREA,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,MAP_DETAILS,AMENITIES,AREA,PRICE,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,SOCIETY_NAME,BUILDING_NAME,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT,PRICE_INR,PRICE_PER_SQFT
8418,S,"This beautiful 2 bhk flat in kasba siemens, ko...",Residential Apartment,Kolkata South,1.0,1,2.0,5764.0,4,8,2,3.0,"23,24,19",on request,"{'LATITUDE': '22.5158935205', 'LONGITUDE': '88...","23,24,19,103",850 sq.ft.,49 L,2 BHK Flat in Kasba Siemens,"['READY TO MOVE', 'RESALE']",50.0,"[{'category': 'ReligiousPlace', 'text': '15 Re...",on request,on request,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",1.0,1,0.490000,850.0,4900000.00,5764.705882
2506,S,On request is one of the most popular destinat...,Residential Apartment,Kolkata South,1.0,1,2.0,4200.0,2,8,1,4.0,"23,24,47,25,5,19,9,40,41,42,21,43",On Request,"{'LATITUDE': '22.484146', 'LONGITUDE': '88.416...","5,21,23,24,47,19,9,40,41,42,43,25,102,103",712 sq.ft.,29.9 L,2 BHK Flat in Nayabad,"['READY TO MOVE', 'RESALE']",26.0,"[{'category': 'ReligiousPlace', 'text': '5 Rel...",On Request,On Request,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",1.0,2,0.299000,712.0,2990000.00,4199.438202
6284,S,This 3 bhk apartment is available for sale in ...,Residential Apartment,Kolkata East,1.0,1,3.0,5034.0,1,8,1,13.0,"44,23,12,24,46,47,25,26,17,28,19,1,3,5,6,9,40,...",NCCF Sunny Fort,"{'LATITUDE': '22.6116237', 'LONGITUDE': '88.47...","17,5,20,21,44,23,24,46,47,28,19,1,6,9,40,30,41...",2185 sq.ft.,1.1 Cr,3 BHK Flat in New Town,"['READY TO MOVE', 'RESALE']",12.0,"[{'category': 'Shopping', 'text': '4 Shoppings...",NCCF Sunny Fort,NCCF Sunny Fort,"{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'L...",2.0,3,1.100000,2185.0,11000000.00,5034.324943
1941,S,"Arya Altamount is a residential project, offer...",Residential Apartment,Kolkata South,2.0,1,4.0,7500.0,0,0,5,18.0,N,Arya Altamount,"{'LATITUDE': '22.491533501249', 'LONGITUDE': '...",NaN,1548 sq.ft.,1.16 Cr,4 BHK Flat in EM Bypass,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",9.0,"[{'category': 'MetroStation', 'text': '2 Metro...",Arya Altamount,Arya Altamount,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,1.160000,1548.0,11600000.00,7493.540052
1764,S,Ascon Era offers 3 BHK apartments in Chinar Pa...,Residential Apartment,Kolkata East,2.0,1,3.0,6000.0,0,0,5,11.0,N,Ascon Era,"{'LATITUDE': '22.633414', 'LONGITUDE': '88.459...",NaN,1146-1360 sq.ft.,68.76 - 81.6 L,3 BHK Flat in Chinar Park,"['UNDER CONSTRUCTION', 'NEW BOOKING', 'RERA | ...",11.0,"[{'category': 'Shopping', 'text': '2 Shoppings...",Ascon Era,Ascon Era,"{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'L...",NaN,1,0.408003,1253.0,4080034.38,3256.212594

In [128]:
df["PRICE_PER_SQFT(INR)"] = df["PRICE_PER_SQFT"].round(2)

In [129]:
df.sample(5)

,PREFERENCE,DESCRIPTION,PROPERTY_TYPE,CITY,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,PRICE_PER_UNIT_AREA,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,MAP_DETAILS,AMENITIES,AREA,PRICE,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,SOCIETY_NAME,BUILDING_NAME,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT,PRICE_INR,PRICE_PER_SQFT,PRICE_PER_SQFT(INR)
4352,R,This is a beautiful 3 bhk flat for rent in e m...,Residential Apartment,Kolkata South,NaN,0,3.0,31.0,1,2,1,45.0,"33,23,12,24,25,26,17,28,29,19,1,3,5,6,8,9,30,2...",Urbana,"{'LATITUDE': '22.548114', 'LONGITUDE': '88.400...","17,5,8,20,21,10,32,23,24,28,29,19,1,6,9,30,42,...",2867 sq.ft.,"90,000",3 BHK Flat in EM Bypass,['FURNISHED'],15.0,"[{'category': 'MetroStation', 'text': '1 Metro...",Urbana,Urbana,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",1.0,17,0.0090,2867.0,90000.0,31.391699,31.39
3620,R,Kolkata east's most popular society tata eden ...,Residential Apartment,Kolkata East,NaN,0,2.0,21.0,2,3,1,21.0,"23,6,20,21",Tata Eden Court,"{'LATITUDE': '22.582101', 'LONGITUDE': '88.493...","20,21,23,6",945 sq.ft.,"20,000",2 BHK Flat in Action Area 2,"['FOR SINGLE MEN', 'FOR SINGLE WOMEN']",22.0,"[{'category': 'ReligiousPlace', 'text': '1 Rel...",Tata Eden Court,Tata Eden Court,"{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'L...",1.0,4,0.0020,945.0,20000.0,21.164021,21.16
5796,S,Kolkataproperties.In offers you a premium 3 bh...,Residential Apartment,Kolkata South,1.0,1,3.0,16250.0,1,0,2,45.0,"1,12,23,2,3,6,19,20,21",Urbana,"{'LATITUDE': '22.512772', 'LONGITUDE': '88.410...","2,20,21,1,23,6,19,12,3,103",2000 sq.ft.,3.25 Cr,3 BHK Flat in EM Bypass,"['READY TO MOVE', 'RESALE', 'RERA | HIRA']",15.0,"[{'category': 'MetroStation', 'text': '1 Metro...",Urbana,Urbana,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",3.0,1,3.2500,2000.0,32500000.0,16250.000000,16250.00
1019,R,Find this 3 bhk apartment for rent in narendra...,Residential Apartment,Kolkata South,NaN,0,3.0,15.0,4,8,1,7.0,"23,12,1,24,3,17,6,19,9,20,21",SGIL Gardenia,"{'LATITUDE': '22.4278792', 'LONGITUDE': '88.40...","17,20,21,23,1,24,6,19,9,12,3,103",1127 sq.ft.,"17,000",3 BHK Flat in Narendrapur,"['FOR SINGLE MEN', 'FOR SINGLE WOMEN']",15.0,"[{'category': 'Education', 'text': '3 Educatio...",SGIL Gardenia,SGIL Gardenia,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",1.0,6,0.0017,1127.0,17000.0,15.084295,15.08
7151,S,"Situated in tollygunge, kolkata south, merlin ...",Residential Apartment,Kolkata South,1.0,1,3.0,9062.0,1,0,2,12.0,"44,23,12,3,19,20,21",Merlin Manor,"{'LATITUDE': '22.503906', 'LONGITUDE': '88.344...","20,21,44,23,19,12,3,102,103",1600 sq.ft.,1.45 Cr,3 BHK Flat in Tollygunge,"['READY TO MOVE', 'RESALE']",50.0,"[{'category': 'MetroStation', 'text': '3 Metro...",Merlin Manor,Merlin Manor,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",1.0,8,1.4500,1600.0,14500000.0,9062.500000,9062.50

In [130]:
df["PRICE_INR"]

0       1.910000e+06
1       5.900001e+06
2       6.750001e+06
3       2.995008e+05
4       3.750030e+06
5       2.450022e+06
6       9.085000e+06
7       3.900000e+06
8       3.008026e+06
9       2.091521e+06
10      2.700009e+05
11      1.100000e+04
12      2.170021e+06
13      8.003000e+06
14      2.614025e+06
15      2.124018e+06
16      2.728000e+06
17      7.950001e+06
18      9.200000e+06
19      4.100024e+06
20      4.200000e+06
21      5.400001e+06
22      4.080034e+06
23      3.249027e+06
24      1.000000e+04
25      6.000000e+03
26      1.300000e+07
27      7.500001e+06
28      5.466000e+06
29      4.235000e+06
30      4.392044e+06
31      2.810028e+06
32      2.044520e+06
33      6.300001e+06
34      4.783039e+06
35      6.412000e+06
36      7.592000e+06
37      5.460000e+06
38      1.000000e+04
39      3.968502e+06
40      1.747017e+06
41      1.419013e+06
42      1.924015e+06
43      5.500000e+06
44      3.600000e+06
45      3.794000e+06
46      2.950000e+06
47      3.511035e+06
48      2.534022e+06
49      3.276000e+06
50      1.022250e+07
51      2.925528e+06
52      2.897528e+06
53      4.700000e+06
54      3.845000e+06
55      1.300011e+06
56      5.300000e+06
57      2.080021e+06
58      4.781541e+06
59      3.372529e+06
60      3.809033e+06
61      3.193023e+06
62      3.906034e+06
63      2.862524e+06
64      1.123510e+06
65      2.089521e+06
66      1.670516e+06
67      4.645000e+06
68      1.617016e+06
69      1.318512e+06
70      2.750028e+06
71      1.850018e+06
72      2.800024e+06
73      3.800000e+06
74      8.250000e+06
75      9.250000e+06
76      3.799538e+06
77      3.169532e+06
78      5.910000e+07
79      3.180000e+07
80      2.500005e+06
81      6.931000e+06
82      4.967000e+06
83      5.300001e+06
84      4.203542e+06
85      3.355033e+06
86      4.466000e+06
87      3.792000e+06
88      2.490000e+06
89      2.214021e+06
90      1.722016e+06
91      1.579513e+06
92      9.380085e+05
93      1.627015e+06
94      1.356511e+06
95      2.974527e+06
96      2.171021e+06
97      2.522022e+06
98      1.964018e+06
99      1.460000e+07
100     9.864000e+06
101     3.898035e+06
102     1.878016e+06
103     2.308018e+06
104     3.507000e+06
105     2.717000e+06
106     4.106000e+06
107     2.058000e+06
108     4.861042e+06
109     3.689036e+06
110     2.924026e+06
111     2.362520e+06
112     2.200000e+07
113     9.050001e+06
114     9.050000e+06
115     2.750026e+06
116     3.700000e+06
117     1.400000e+07
118     9.225000e+06
119     5.850000e+06
120     1.727017e+06
121     1.669513e+06
122     2.187009e+06
123     9.000000e+06
124     2.750022e+06
125     1.420000e+07
126     7.150001e+06
127     7.050001e+06
128     1.929517e+06
129     1.560011e+06
130     3.000000e+03
131     9.100000e+06
132     6.000000e+06
133     3.900000e+06
134     1.688017e+06
135     1.359512e+06
136     1.805006e+05
137     2.506022e+06
138     3.617000e+06
139     4.807524e+06
140     3.704020e+06
141     2.750027e+06
142              NaN
143     3.590525e+06
144     3.069518e+06
145     2.678000e+06
146     2.509000e+06
147     1.680000e+06
148     1.053000e+06
149     2.826020e+06
150     2.278015e+06
151     1.780010e+06
152     1.850015e+06
153     1.130010e+06
154     2.460023e+06
155     2.066515e+06
156     2.940000e+06
157     2.940000e+07
158     7.200001e+06
159     5.600001e+06
160     9.800001e+06
161     7.200001e+06
162     7.050001e+06
163     4.800045e+06
164     4.966040e+06
165     3.640033e+06
166     6.340000e+06
167     4.740000e+06
168     4.968000e+06
169     1.975016e+06
170     3.522000e+06
171     2.460000e+06
172     3.725000e+06
173     2.495000e+06
174     1.600000e+06
175     3.310000e+06
176     2.335000e+06
177     1.450000e+06
178     2.500000e+06
179     6.420000e+06
180     5.350001e+06
181     5.500001e+06
182     4.163029e+06
183     2.820523e+06
184     4.156000e+06
185     7.966000e+06
186     5.862000e+06
187     2.916025e+06
188     3.960000e+06
189     5.500000e+06
190     5.000000e+06
191     4.270000e+07
192     1.605000e+07
193     1.249510e+06
194     3.287526e+06
195     2.070017e+06
196     5.001000e+03
197     3.410000e+06
198     1.475000e+06
199     5.000000e+06
200     7.750000e+06
201     9.050000e+06
202     5.640000e+06
203     4.375000e+06
204     6.534000e+06
205     3.289526e+06
206     5.215000e+06
207     2.619519e+06
208     1.807515e+06
209     4.500000e+06
210     4.019531e+06
211     2.693523e+06
212     2.631000e+06
213     4.051536e+06
214     3.166029e+06
215     3.500000e+06
216     7.500000e+06
217     5.950001e+06
218     4.842043e+06
219     6.051000e+06
220     3.565000e+06
221     1.475512e+06
222     8.120078e+05
223     4.270000e+07
224     1.605000e+07
225     6.300000e+06
226     4.750000e+06
227     2.070020e+06
228     1.822014e+06
229     2.794517e+06
230     1.525013e+06
231     2.360018e+06
232     1.744014e+06
233     1.888019e+06
234     2.821000e+06
235     2.023000e+06
236     1.050000e+07
237     1.750000e+07
238     2.255518e+06
239     1.824005e+06
240     9.920033e+05
241     2.766523e+06
242     2.766523e+06
243     2.068017e+06
244     2.068017e+06
245     7.415000e+06
246     2.828527e+06
247     1.694517e+06
248     2.302520e+06
249     2.004518e+06
250              NaN
251     5.000000e+06
252     3.000000e+07
253     4.500038e+06
254     2.955029e+06
255     3.890036e+06
256     1.130000e+07
257     4.674540e+06
258     3.630000e+06
259     1.750000e+07
260     8.200000e+06
261     1.002000e+08
262     3.650000e+06
263     2.300000e+06
264     3.597034e+06
265     2.868022e+06
266     3.179024e+06
267     2.475020e+06
268     2.574525e+06
269     1.669514e+06
270     4.170036e+06
271     3.088524e+06
272     3.128023e+06
273     2.397019e+06
274     2.733526e+06
275     2.030520e+06
276     5.000000e+06
277     2.720000e+07
278     6.500000e+06
279     1.200000e+07
280     7.000000e+06
281     2.850000e+06
282     4.500000e+06
283     3.176030e+06
284     2.219021e+06
285     1.560516e+06
286              NaN
287     3.500000e+06
288     6.500000e+06
289     5.000000e+06
290     4.900000e+03
291     8.000000e+03
292     7.501000e+03
293     8.000000e+03
294     6.500000e+06
295     6.200000e+03
296     8.700000e+06
297     5.160000e+06
298     2.080521e+06
299     5.000000e+06
300     5.000000e+03
301     3.250000e+07
302     1.270511e+06
303     4.500000e+06
304     2.000000e+06
305     7.500000e+06
306     2.737019e+06
307     2.041518e+06
308     2.737019e+06
309     2.041518e+06
310     7.000000e+06
311     3.500000e+06
312     1.700000e+07
313     5.000000e+06
314     3.700000e+06
315     4.500000e+04
316     6.342000e+06
317     7.500000e+06
318     3.150000e+06
319     2.600000e+06
320     3.200000e+06
321     3.600000e+06
322     7.500000e+06
323     3.800000e+06
324     2.800000e+06
325     6.000000e+06
326     1.850000e+08
327     1.750000e+07
328     5.500000e+06
329     4.300000e+06
330     5.300000e+06
331     7.000001e+06
332     8.854500e+06
333     3.209529e+06
334     9.867000e+06
335     6.324000e+06
336     5.390000e+06
337     8.844000e+06
338     1.500000e+06
339     4.500000e+06
340     1.250000e+07
341     9.000000e+06
342     4.650000e+07
343     1.220000e+07
344     7.500000e+06
345     3.900000e+06
346     4.800000e+06
347     3.800000e+06
348     1.920000e+07
349     1.300000e+07
350     2.800000e+06
351     3.550000e+06
352     1.800000e+04
353     8.500000e+06
354     1.000000e+07
355     2.400000e+06
356     3.900000e+06
357     5.500000e+06
358     6.000000e+06
359     6.000000e+06
360     6.000000e+06
361     3.809033e+06
362     3.193025e+06
363     2.924026e+06
364     2.362520e+06
365     9.800001e+06
366     7.200001e+06
367     4.237532e+06
368     2.957526e+06
369     2.200000e+07
370     9.050001e+06
371     4.500038e+06
372     2.955529e+06
373     3.760000e+07
374     2.475000e+07
375     9.650001e+06
376     1.270000e+07
377     4.100024e+06
378     4.200000e+06
379     1.045000e+07
380     7.400001e+06
381     5.100000e+07
382     2.175000e+07
383     7.350001e+06
384     1.124250e+07
385     1.895000e+07
386     1.195000e+07
387     1.525000e+07
388     1.245000e+07
389     4.270000e+07
390     1.605000e+07
391     6.900000e+06
392     3.000000e+03
393     2.800000e+03
394     4.500000e+03
395     2.800000e+03
396     5.000000e+03
397     4.000000e+03
398     2.350000e+03
399     2.850000e+03
400     3.000000e+03
401     3.100000e+03
402     3.600000e+03
403     4.800000e+06
404     2.500000e+03
405     1.258012e+06
406     1.258012e+06
407     9.850000e+06
408     7.000000e+06
409     2.500000e+03
410     3.000000e+06
411     6.000000e+06
412     9.350001e+06
413     1.029500e+07
414     7.000000e+06
415     6.500000e+06
416     5.000000e+06
417     7.500000e+06
418     4.200000e+06
419     7.500000e+06
420     3.200000e+06
421     6.000000e+06
422     2.500000e+03
423     2.800000e+06
424     6.700000e+06
425     4.000000e+06
426     6.500000e+06
427     4.500000e+06
428     3.350000e+06
429     3.200000e+06
430     1.326010e+06
431     2.810000e+07
432     5.600000e+06
433     5.850001e+06
434     4.684041e+06
435     3.004027e+06
436     5.500000e+06
437     4.500000e+03
438     4.450000e+06
439     3.700000e+06
440     2.250000e+06
441     3.990000e+07
442     3.300000e+06
443     4.500000e+06
444     3.000000e+06
445     1.720000e+07
446     6.300000e+06
447     7.850000e+06
448     1.700000e+07
449     3.000000e+06
450     6.000000e+06
451     5.500000e+06
452     7.000000e+06
453     3.650000e+06
454     8.500000e+06
455     8.500000e+06
456     6.500000e+06
457     4.000000e+06
458     7.500000e+06
459     3.000000e+06
460     3.500000e+03
461     3.200000e+06
462     3.100000e+06
463     1.200000e+04
464     1.100000e+04
465     1.100000e+04
466     1.750000e+07
467     3.000000e+06
468     5.999000e+03
469     3.800000e+06
470     8.000000e+06
471     4.000000e+06
472     1.750000e+06
473     7.200000e+06
474     4.300000e+06
475     2.700000e+06
476     6.100000e+06
477     3.600000e+06
478     5.800000e+06
479     3.600000e+06
480     3.800000e+06
481     3.400000e+06
482     7.000000e+06
483     3.500000e+06
484     2.000000e+03
485     2.989000e+06
486     4.300000e+06
487     1.929518e+06
488     1.656014e+06
489     1.275000e+07
490     9.000001e+06
491     4.851047e+06
492     1.628515e+06
493     1.154510e+06
494     6.000000e+06
495     3.700000e+06
496     7.500000e+06
497     4.000000e+06
498     7.700000e+06
499     7.500000e+06
500     1.790000e+07
501     9.000000e+06
502     6.600000e+06
503     8.000000e+06
504     3.500000e+06
505     2.300000e+06
506     3.336024e+06
507     2.714523e+06
508     9.999000e+06
509     2.749521e+06
510     3.000000e+06
511     4.623043e+06
512     7.905078e+05
513     6.515060e+05
514     3.684000e+06
515     1.575014e+06
516     9.000081e+05
517     6.500000e+06
518     2.200000e+06
519     1.600000e+06
520     3.070000e+06
521     2.600000e+06
522     5.000000e+06
523     6.000000e+06
524     2.600000e+07
525     6.500000e+07
526     5.100000e+06
527     7.500000e+06
528     1.800000e+06
529     3.500000e+06
530     6.800000e+06
531     1.250000e+07
532     7.500000e+06
533     1.900000e+06
534     4.600000e+06
535     1.100000e+07
536     5.000000e+03
537     4.200000e+06
538     2.200000e+06
539     4.000000e+06
540     8.200000e+06
541     2.100016e+06
542     3.000000e+06
543     2.800000e+06
544     5.500000e+06
545     5.000000e+06
546     3.200000e+06
547     6.500000e+06
548     3.550000e+06
549     6.000000e+06
550     6.800000e+06
551     2.810000e+07
552     9.000000e+06
553     3.600000e+06
554     3.000000e+06
555     3.000000e+06
556     7.000000e+04
557     1.250000e+04
558     2.500000e+04
559     4.490000e+06
560     2.897526e+06
561     2.350023e+06
562     3.670531e+06
563     2.947526e+06
564     3.750032e+06
565     4.237532e+06
566     3.556027e+06
567     2.924026e+06
568     2.362520e+06
569     2.089521e+06
570     1.670516e+06
571     6.300000e+06
572     4.750000e+06
573     1.910000e+07
574     1.450000e+07
575     3.336024e+06
576     2.714523e+06
577     7.000000e+06
578     1.318512e+06
579     1.123510e+06
580     5.800000e+06
581     6.500000e+06
582     7.800000e+06
583     7.500000e+06
584     6.800000e+06
585     4.250040e+06
586     8.300001e+06
587     4.956000e+06
588     5.500000e+06
589     1.020000e+07
590     5.500000e+06
591     6.400001e+06
592     4.783039e+06
593     6.412000e+06
594     1.100000e+07
595     3.300000e+03
596     4.200000e+06
597     4.000000e+06
598     1.705000e+07
599     1.025000e+07
600     1.410000e+07
601     1.420000e+07
602     7.150001e+06
603     7.050001e+06
604     8.176000e+06
605     3.877029e+06
606     4.800000e+06
607     2.290000e+07
608     7.600001e+06
609     9.550000e+06
610     6.400001e+06
611     4.979539e+06
612     6.412000e+06
613     3.843034e+06
614     2.747027e+06
615     2.433024e+06
616              NaN
617     3.900035e+06
618     2.729527e+06
619     7.000100e+04
620     2.500000e+06
621     2.700000e+03
622     2.500000e+03
623     3.300000e+03
624     2.700000e+03
625     3.500000e+03
626     7.800000e+06
627     7.500000e+03
628     4.000000e+03
629     2.800000e+03
630     6.500000e+04
631     7.000000e+06
632     3.500000e+06
633     1.900000e+06
634     2.500000e+06
635     6.300000e+06
636     6.925000e+06
637     4.630000e+06
638     4.000000e+06
639     7.800000e+06
640     3.900000e+06
641     2.800000e+06
642     1.800000e+06
643     4.123530e+06
644     2.328021e+06
645     2.500000e+04
646     1.500000e+05
647     2.000000e+04
648     4.000000e+07
649     2.600000e+04
650     1.820000e+07
651     8.700000e+06
652     5.200000e+07
653     9.000000e+06
654     2.000000e+04
655     1.000000e+07
656     3.800000e+06
657     8.500000e+06
658     6.750000e+07
659     8.200000e+06
660     3.800000e+04
661     1.950000e+06
662     3.000000e+04
663     4.500038e+06
664     2.955529e+06
665     4.237532e+06
666     3.556027e+06
667     4.298037e+06
668     3.283527e+06
669     2.640521e+06
670     2.223020e+06
671     3.026000e+06
672     1.385512e+06
673     1.455650e+07
674     3.906034e+06
675     2.862525e+06
676     3.917032e+06
677     2.873525e+06
678     4.500038e+06
679     2.955029e+06
680     1.785000e+07
681     8.300001e+06
682     2.213520e+06
683     2.390000e+06
684     3.800000e+06
685     7.191000e+06
686     5.687000e+06
687     5.154000e+06
688     4.526000e+06
689     5.764000e+06
690     3.689000e+06
691     5.370000e+06
692     3.146000e+06
693     7.034000e+06
694     5.224000e+06
695     3.736000e+06
696     3.200000e+06
697     4.261000e+06
698     3.506000e+06
699     5.900000e+06
700     3.200000e+06
701     2.000000e+04
702     9.512500e+06
703     4.248023e+06
704     3.536020e+06
705     1.600000e+04
706     1.430000e+07
707     1.048650e+07
708     4.086034e+06
709     1.800000e+04
710     2.200000e+04
711     6.300000e+06
712     2.655027e+06
713     1.800000e+04
714     2.995008e+05
715     2.500005e+06
716     7.000000e+04
717     2.987527e+06
718     3.174520e+06
719     2.645021e+06
720     2.116016e+06
721     2.784523e+06
722     2.204019e+06
723     3.221028e+06
724     2.292021e+06
725     4.100000e+06
726     1.910000e+07
727     1.450000e+07
728     6.900001e+06
729     9.750000e+06
730     1.525000e+07
731     1.245000e+07
732     4.500000e+06
733     1.566014e+06
734     4.967544e+06
735     3.355533e+06
736     4.237532e+06
737     3.556026e+06
738     1.410000e+07
739     1.240000e+07
740     1.095000e+07
741     8.300001e+06
742     1.800000e+04
743     5.850000e+06
744     3.630000e+07
745     1.350000e+07
746     1.300000e+07
747     1.110000e+07
748     7.000000e+06
749     6.500000e+06
750     6.400000e+06
751     4.500038e+06
752     2.955529e+06
753     3.809033e+06
754     3.193023e+06
755     1.300000e+04
756     3.500000e+06
757     1.350000e+07
758     1.525000e+07
759     1.245000e+07
760     4.298037e+06
761     3.283527e+06
762     3.000000e+07
763     2.300000e+07
764     1.360000e+07
765     9.785000e+06
766     1.740000e+07
767     1.150000e+07
768     6.486000e+06
769     5.100000e+06
770     7.083000e+06
771     4.700000e+06
772     7.500000e+06
773     5.801000e+06
774     1.500000e+04
775     7.500000e+06
776     2.500005e+06
777     2.300100e+04
778     2.000000e+04
779     2.010000e+07
780     9.400000e+06
781     3.407030e+06
782     7.000001e+06
783     8.854500e+06
784     3.209529e+06
785     6.400001e+06
786     4.979539e+06
787     6.412000e+06
788     4.500000e+06
789     3.750030e+06
790     2.450022e+06
791     7.500001e+06
792     6.600001e+06
793     4.904039e+06
794     8.750001e+06
795     9.500001e+06
796     4.603540e+06
797     4.525034e+06
798     2.750026e+06
799     3.700000e+06
800     3.000512e+06
801     7.500000e+06
802     2.700009e+05
803     9.400001e+06
804     3.380032e+06
805     2.255518e+06
806     1.717515e+06
807     3.380032e+06
808     2.255518e+06
809     1.717515e+06
810     2.995008e+05
811     1.600000e+04
812     9.500000e+06
813     1.500000e+04
814     1.820000e+07
815     8.700000e+06
816              NaN
817     5.600000e+06
818     4.000000e+06
819     6.900000e+06
820     1.400000e+04
821     2.020000e+04
822     3.500000e+04
823     1.130000e+07
824     9.200001e+06
825     9.400001e+06
826     1.785000e+07
827     7.083000e+06
828     5.232000e+06
829     7.500000e+06
830     5.801000e+06
831     5.600000e+06
832     4.400000e+06
833     5.400000e+06
834     4.100000e+06
835     6.309000e+06
836     4.750000e+06
837     1.280000e+07
838     6.714000e+06
839     5.895000e+06
840     5.500000e+06
841     4.800000e+06
842     1.910000e+07
843     1.450000e+07
844     9.463000e+06
845     3.869533e+06
846     3.750030e+06
847     2.450022e+06
848     1.045000e+07
849     1.310012e+06
850     1.123510e+06
851     4.645000e+06
852     1.617016e+06
853     3.906534e+06
854     2.862525e+06
855     4.237532e+06
856     3.556027e+06
857     6.379000e+06
858     3.965000e+06
859     1.050000e+07
860     6.050001e+06
861     8.950001e+06
862     1.019500e+07
863     2.800028e+06
864     2.025020e+06
865     3.150030e+06
866     2.662022e+06
867     3.715000e+06
868     1.553514e+06
869     6.900001e+06
870     9.750000e+06
871     8.300001e+06
872     1.000000e+07
873     8.500000e+06
874     2.026020e+06
875     2.026020e+06
876     8.300001e+06
877     8.876000e+06
878     7.800000e+06
879     1.922518e+06
880     1.300011e+06
881     3.132025e+06
882     1.200000e+04
883     1.700000e+04
884     6.500000e+06
885     4.525034e+06
886     2.750026e+06
887     3.700000e+06
888     9.200000e+06
889     4.800000e+06
890     4.200000e+06
891     1.660000e+07
892     7.600001e+06
893     9.550000e+06
894     5.100000e+07
895     2.175000e+07
896     2.500000e+07
897     4.400544e+06
898     3.794038e+06
899     1.470000e+07
900     1.020000e+07
901     4.500038e+06
902     2.955529e+06
903     1.341600e+07
904     4.055535e+06
905     2.924026e+06
906     2.362520e+06
907     4.298037e+06
908     3.283527e+06
909     3.809033e+06
910     3.193025e+06
911     5.400000e+06
912     4.100000e+06
913     3.750030e+06
914     2.454523e+06
915     1.525000e+07
916     1.245000e+07
917     1.910000e+07
918     1.450000e+07
919     3.402026e+06
920     2.864519e+06
921     1.525000e+07
922     1.245000e+07
923     3.876530e+06
924     2.454523e+06
925     1.008500e+07
926     3.841538e+06
927     5.741000e+06
928     3.595000e+06
929     2.926000e+06
930     9.880000e+06
931     6.888000e+06
932     5.175000e+06
933     1.990000e+07
934     3.250000e+07
935     2.500000e+07
936     1.700000e+07
937     6.000000e+07
938     7.000000e+06
939     2.600000e+07
940     1.200000e+07
941     6.700000e+06
942     6.000000e+06
943     5.800000e+06
944     1.450000e+07
945     5.500000e+06
946     4.000000e+07
947     1.000000e+07
948     1.650000e+07
949     4.340000e+07
950     1.500000e+07
951     1.200000e+07

In [131]:
df["TRANSACT_TYPE"].value_counts()

TRANSACT_TYPE
1.0    5388
2.0    1670
Name: count, dtype: int64

In [132]:
df["OWNTYPE"].value_counts()

df["OWNTYPE_label"] = df["OWNTYPE"].map({
    0: "Freehold",
    1: "Cooperative Society",
    2: "Leasehold",
    3: "Power of Attorney",
    4: "Other"
})

In [133]:
df.sample(5)

,PREFERENCE,DESCRIPTION,PROPERTY_TYPE,CITY,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,PRICE_PER_UNIT_AREA,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,MAP_DETAILS,AMENITIES,AREA,PRICE,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,SOCIETY_NAME,BUILDING_NAME,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT,PRICE_INR,PRICE_PER_SQFT,PRICE_PER_SQFT(INR),OWNTYPE_label
6082,R,Explore this amicable on request of garia in k...,Residential Apartment,Kolkata South,NaN,0,3.0,13.0,4,7,1,3.0,6,On Request,"{'LATITUDE': '22.456112', 'LONGITUDE': '88.381...",6,1150 sq.ft.,"15,000",3 BHK Flat in Garia,"['FOR SINGLE MEN', 'FOR SINGLE WOMEN']",33.0,"[{'category': 'MetroStation', 'text': '2 Metro...",On Request,On Request,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",1.0,G,0.0015,1150.0,15000.0,13.043478,13.04,Freehold
5741,S,"Situated in new town, kolkata east, elita gard...",Residential Apartment,Kolkata East,1.0,1,3.0,9583.0,2,2,1,30.0,"23,24,6,19,21",Elita Garden Vista,"{'LATITUDE': '22.6006912', 'LONGITUDE': '88.46...","21,23,24,6,19,102",1200 sq.ft.,1.15 Cr,3 BHK Flat in New Town,"['READY TO MOVE', 'RESALE']",15.0,"[{'category': 'Shopping', 'text': '3 Shoppings...",Elita Garden Vista,Elita Garden Vista,"{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'L...",1.0,11,1.1500,1200.0,11500000.0,9583.333333,9583.33,Cooperative Society
3000,S,3 bhk spacious apartment with one servant quar...,Residential Apartment,Kolkata East,1.0,1,3.0,24193.0,4,2,6,23.0,"23,12,24,25,47,26,17,19,1,3,5,6,9,40,41,20,42,...",Anik One Rajarhat,"{'LATITUDE': '22.581199', 'LONGITUDE': '88.461...","17,5,20,21,23,24,47,19,1,6,9,40,41,42,12,25,26...",1891 sq.ft.,2.7 Cr,3 BHK Flat in New Town,"['READY TO MOVE', 'RESALE', 'RERA | HIRA']",15.0,"[{'category': 'MetroStation', 'text': '1 Metro...",Anik One Rajarhat,Anik One Rajarhat,"{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'L...",2.0,20,2.7000,1891.0,27000000.0,14278.159704,14278.16,Cooperative Society
7310,R,Urbana is one of kolkata south's most sought a...,Residential Apartment,Kolkata South,NaN,0,4.0,36.0,4,0,2,45.0,"23,24,17,6,19,20,21",Urbana,"{'LATITUDE': '22.512772', 'LONGITUDE': '88.410...","17,20,21,23,24,6,19",3528 sq.ft.,1.3 L,4 BHK Flat in EM Bypass,[],15.0,"[{'category': 'MetroStation', 'text': '1 Metro...",Urbana,Urbana,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",1.0,5,0.0130,3528.0,130000.0,36.848073,36.85,Freehold
7269,S,On request is one of kolkata north's most soug...,Residential Apartment,Kolkata North,1.0,1,2.0,4000.0,2,6,1,5.0,"5,17,21",on Request,"{'LATITUDE': '22.598452', 'LONGITUDE': '88.427...","5,17,21,101,102",950 sq.ft.,38 L,2 BHK Flat in Kestopur,"['READY TO MOVE', 'RESALE']",50.0,"[{'category': 'MetroStation', 'text': '3 Metro...",on Request,on Request,"{'CITY': '26', 'CITY_NAME': 'Kolkata North', '...",1.0,5,0.3800,950.0,3800000.0,4000.000000,4000.00,Cooperative Society

In [134]:
df["FURNISH"].value_counts()
df["FURNISH_label"] = df["FURNISH"].map({
    0: "Unfurnished",
    1: "Semi-furnished",
    2: "Fully furnished",
    4: "Other"
})

In [135]:
df["FACING"].value_counts()

FACING
0    2695
7    1814
2    1262
5     725
3     687
8     597
1     450
6     341
4     226
Name: count, dtype: int64

In [136]:
df["FACING_label"] = df["FACING"].map({
    0: "East",
    1: "West",
    2: "North",
    3: "South",
    4: "North-East",
    5: "South-East",
    6: "South-West",
    7: "North-West",
    8: "Other"
})

In [137]:
df["AGE"].value_counts()
df["AGE"].isnull().sum()

np.int64(0)

In [138]:
df.sample()

,PREFERENCE,DESCRIPTION,PROPERTY_TYPE,CITY,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,PRICE_PER_UNIT_AREA,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,MAP_DETAILS,AMENITIES,AREA,PRICE,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,SOCIETY_NAME,BUILDING_NAME,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT,PRICE_INR,PRICE_PER_SQFT,PRICE_PER_SQFT(INR),OWNTYPE_label,FURNISH_label,FACING_label
4716,S,Looking for a 2 bhk property for sale in kolka...,Residential Apartment,Kolkata North,1.0,1,2.0,2700.0,2,6,5,3.0,"44,23,24,25,26,19,40,41,20,21",TRINAYANI APARTMENT,"{'LATITUDE': '22.76743', 'LONGITUDE': '88.38835'}","20,21,44,23,24,19,40,41,25,26,101,102",710 sq.ft.,19.17 L,2 BHK Flat in Barrackpore,"['UNDER CONSTRUCTION', 'RESALE']",26.0,"[{'category': 'Shopping', 'text': '2 Shoppings...",TRINAYANI APARTMENT,TRINAYANI APARTMENT,"{'CITY': '26', 'CITY_NAME': 'Kolkata North', '...",1.0,1,0.1917,710.0,1917000.0,2700.0,2700.0,Cooperative Society,Fully furnished,South-West

In [139]:
df["TOTAL_FLOOR"].isnull().sum()

np.int64(52)

In [140]:
df["AMENITIES"].dtype

In [141]:
df["PROPERTY_TYPE"].value_counts()

PROPERTY_TYPE
Residential Apartment        7548
Independent House/Villa       499
Residential Land              480
Independent/Builder Floor     270
Name: count, dtype: int64

In [142]:
df["PROP_HEADING"].value_counts()

PROP_HEADING
3 BHK Flat in New Town                                                                       655
2 BHK Flat in New Town                                                                       319
2 BHK Flat in Rajarhat                                                                       296
3 BHK Flat in Rajarhat                                                                       278
3 BHK Flat in EM Bypass                                                                      177
Residential land / Plot in Joka                                                              164
3 BHK Flat in Tollygunge                                                                     160
4 BHK Flat in New Town                                                                       159
2 BHK Flat in Tollygunge                                                                     105
2 BHK Flat in Joka                                                                           104
3 BHK Flat in Narendrapur                                                                    102
3 BHK Flat in Joka                                                                            97
2 BHK Flat in Garia                                                                           97
Residential land / Plot in New Town                                                           91
4 BHK Flat in EM Bypass                                                                       79
3 BHK Flat in Garia                                                                           78
2 BHK Flat in Narendrapur                                                                     77
2 BHK Flat in EM Bypass                                                                       77
3 BHK Flat in Action Area 1                                                                   71
2 BHK Flat in Kestopur                                                                        68
2 BHK Flat in Sodepur                                                                         68
2 BHK Flat in Madhyamgram                                                                     66
3 BHK Flat in Madhyamgram                                                                     65
3 BHK Flat in Salt Lake                                                                       64
3 BHK Flat in Barasat                                                                         62
3 BHK Flat in Nayabad                                                                         62
4 BHK Flat in Tollygunge                                                                      61
2 BHK Flat in Nayabad                                                                         61
3 BHK Flat in BT Road                                                                         54
2 BHK Flat in Chinar Park                                                                     52
3 BHK Flat in Mukundapur                                                                      51
3 BHK Flat in Sodepur                                                                         46
3 BHK Flat in Action Area 2                                                                   45
3 BHK Flat in Chinar Park                                                                     43
1 BHK Flat in New Town                                                                        43
2 BHK Flat in Mukundapur                                                                      42
2 BHK Flat in Konnagar                                                                        41
3 BHK Flat in Action Area 3                                                                   39
4 BHK Flat in Rajarhat                                                                        38
2 BHK Flat in Barasat                                                                         38
Residential land / Plot in Thakurpukur                                                        38
2 BHK Flat in Nager Bazar                                                                     38
2 BHK Flat in Behala                                                                          36
2 BHK Flat in Kasba                                                                           35
3 BHK Flat in Kamalgazi                                                                       34
2 BHK Flat in BT Road                                                                         33
2 BHK Flat in Baguiati                                                                        32
Residential land / Plot in Action Area 3                                                      32
1 BHK Flat in Action Area 3                                                                   32
3 BHK Flat in Behala                                                                          29
2 BHK Flat in Parnasree Palli                                                                 28
1 BHK Flat in Rajarhat                                                                        28
4 BHK Flat in BT Road                                                                         27
3 BHK Flat in Kestopur                                                                        27
2 BHK Flat in Salt Lake                                                                       27
2 BHK Flat in Bansdroni                                                                       27
1 BHK Flat in Barasat                                                                         25
3 BHK Flat in Lake Town                                                                       25
3 BHK Flat in Ballygunge                                                                      25
2 BHK Flat in Baruipur                                                                        24
3 BHK Flat in Madurdaha                                                                       24
2 BHK Flat in Action Area 2                                                                   24
3 BHK Flat in Prince Anwar Shah Rd                                                            23
3 BHK Flat in Kasba                                                                           23
3 BHK Flat in Jessore Road                                                                    23
3 BHK Flat in New Alipore                                                                     22
2 BHK Flat in Kamalgazi                                                                       22
3 BHK Flat in Thakurpukur                                                                     22
3 BHK Flat in Kalikapur                                                                       22
3 BHK Flat in Baruipur                                                                        21
4 BHK Flat in Madhyamgram                                                                     21
5 BHK Flat in New Town                                                                        20
2 BHK Flat in Action Area 1                                                                   20
2 BHK Flat in Parnashree                                                                      20
3 BHK Flat in Parnasree Palli                                                                 20
4 BHK Flat in Alipore                                                                         20
2 BHK Flat in Teghoria                                                                        19
Residential land / Plot in Action Area 2                                                      19
3 BHK Flat in Nager Bazar                                                                     18
2 BHK Flat in Airport                                                                         18
3 BHK Flat in Dum Dum                                                                         17
2 BHK Flat in Thakurpukur                                                                     17
2 BHK Flat in Sonarpur                                                                        17
3 BHK Flat in Konnagar                                                                        17
3 BHK Flat in Entally                                                                         17
2 BHK Flat in New Garia                                                                       17
3 Bedroom House in Joka                                                                       16
4 Bedroom House in Joka                                                                       16
4 BHK Flat in Garia                                                                           16
2 BHK Flat in Action Area 3                                                                   16
3 BHK Flat in Bablatala                                                                       16
Residential land / Plot in Action Area 1                                                      16
3 BHK Flat in Bhawanipore                                                                     15
3 BHK Flat in Howrah                                                                          15
2 BHK Flat in Kalikapur                                                                       15
3 BHK Flat in Maheshtala                                                                      15
2 BHK Flat in Bablatala                                                                       15
2 BHK Flat in Barrackpore                                                                     15
3 BHK Flat in Tangra                                                                          15
2 BHK Flat in Naktala                                                                         15
2 BHK Flat in Survey Park                                                                     15
2 BHK Flat in Behala Chowrasta                                                                15
1 BHK Flat in Kestopur                                                                        15
2 BHK Flat in Dum Dum                                                                         14
4 BHK Flat in Ballygunge                                                                      14
2 BHK Flat in Lake Town                                                                       14
3 BHK Flat in Behala Chowrasta                                                                14
4 BHK Flat in Lake Town                                                                       14
3 BHK Flat in Dash Drone                                                                      14
3 BHK Flat in Lake Gardens                                                                    14
3 BHK Flat in Sonarpur                                                                        13
2 BHK Flat in Maheshtala                                                                      13
2 BHK Flat in Uttarpara                                                                       13
3 BHK Flat in Serampore                                                                       13
2 BHK Flat in Kaikhali                                                                        13
2 BHK Flat in New Alipore                                                                     13
2 BHK Flat in Jadavpur                                                                        13
4 BHK Flat in Prince Anwar Shah Rd                                                            13
3 BHK Flat in Alipore                                                                         13
4 Bedroom House in New Town                                                                   12
4 BHK Flat in Chinar Park                                                                     12
2 BHK Flat in Howrah                                                                          12
2 BHK Flat in Serampore                                                                       12
2 BHK Flat in Lake Gardens                                                                    12
2 BHK Flat in Baguihati                                                                       12
4 BHK Flat in Tangra                                                                          12
2 BHK Flat in Khardah                                                                         12
4 BHK Flat in New Alipore                                                                     12
2 BHK Flat in Patuli                                                                          12
2 BHK Flat in Dum Dum Cantt                                                                   12
2 BHK Flat in New Barrakpur                                                                   11
3 BHK Flat in Baguiati                                                                        11
4 BHK Flat in Kankurgachi                                                                     11
3 BHK Flat in Airport                                                                         11
1 BHK Flat in Mukundapur                                                                      11
2 BHK Flat in Haridevpur                                                                      11
3 BHK Flat in Barrackpore                                                                     11
3 BHK Flat in Southern Avenue                                                                 11
3 BHK Flat in Action Area 2B                                                                  11
4 BHK Flat in Narkeldanga                                                                     10
3 BHK Flat in Rajpur                                                                          10
2 BHK Flat in Rajpur                                                                          10
2 BHK Flat in Boral                                                                           10
3 BHK Flat in Chingrighata                                                                    10
3 BHK Flat in Kaikhali                                                                        10
3 BHK Flat in Picnic Garden                                                                   10
3 BHK Flat in Jadavpur                                                                        10
2 BHK Independent Builder Floor in Garia                                                      10
Residential land / Plot in Thakurpukur Bazar                                                  10
2 BHK Flat in Ballygunge                                                                      10
2 BHK Flat in Sarsuna                                                                         10
3 BHK Flat in New Town Action Area 1C                                                         10
3 BHK Flat in Kasba Siemens                                                                   10
2 BHK Flat in Dum Dum Park                                                                     9
1 BHK Flat in Madhyamgram                                                                      9
1 BHK Flat in Serampore                                                                        9
3 BHK Flat in Dunlop                                                                           9
3 BHK Flat in Naktala                                                                          9
3 Bedroom House in Barasat                                                                     9
5 BHK Flat in EM Bypass                                                                        9
1 BHK Flat in Sodepur                                                                          9
2 BHK Flat in Jodhpur Park                                                                     9
3 BHK Flat in Natunpara                                                                        9
2 BHK Flat in Dash Drone                                                                       9
2 BHK Flat in Chak Garia                                                                       9
3 BHK Flat in Golf Green                                                                       9
1 BHK Flat in Garia                                                                            8
3 BHK Flat in Uttarpara                                                                        8
2 BHK Flat in Dunlop                                                                           8
4 BHK Flat in Entally                                                                          8
2 BHK Flat in Jyangra                                                                          8
Residential land / Plot in Sonarpur                                                            8
3 BHK Flat in Patuli                                                                           8
3 BHK Flat in Phoolbagan                                                                       8
4 BHK Flat in Bhawanipore                                                                      8
3 BHK Flat in New Garia                                                                        8
2 BHK Flat in Madurdaha                                                                        8
2 BHK Flat in Prince Anwar Shah Rd                                                             8
2 BHK Flat in Garia Station                                                                    8
3 BHK Flat in Gariahat                                                                         8
2 BHK Flat in Mahamayatala                                                                     8
3 BHK Flat in Ballygunge Circular Road                                                         8
2 BHK Flat in Kudghat                                                                          8
3 BHK Flat in Sarat Bose Road                                                                  8
3 BHK Flat in Narkeldanga                                                                      7
3 BHK Flat in Dum Dum Park                                                                     7
4 BHK Flat in Chingrighata                                                                     7
2 Bedroom House in Joka                                                                        7
5 Bedroom House in Joka                                                                        7
1 BHK Flat in Joka                                                                             7
2 BHK Flat in Sakher Bazar                                                                     7
3 BHK Flat in Chak Garia                                                                       7
3 Bedroom House in Sector 2 Salt Lake                                                          7
3 Bedroom House in EM Bypass                                                                   7
4 BHK Flat in Southern Avenue                                                                  7
3 BHK Flat in Mahamayatala                                                                     7
3 BHK Independent Builder Floor in Action Area 1                                               7
3 BHK Flat in Bansdroni                                                                        7
4 BHK Flat in Action Area 1                                                                    6
3 BHK Flat in Bangur                                                                           6
3 Bedroom House in New Town                                                                    6
3 BHK Flat in Ultadanga                                                                        6
2 BHK Flat in Durganagar                                                                       6
4 BHK Flat in Narendrapur                                                                      6
2 Bedroom House in Jadavpur                                                                    6
4 BHK Flat in Howrah                                                                           6

In [143]:
df["MAP_DETAILS"].value_counts()

MAP_DETAILS
{'LATITUDE': '22.6006912', 'LONGITUDE': '88.4694535'}                              419
{'LATITUDE': '22.4439029807', 'LONGITUDE': '88.2978736068'}                        148
{'LATITUDE': '22.5', 'LONGITUDE': '88.35'}                                         129
{'LATITUDE': '88.35469', 'LONGITUDE': '22.536025'}                                 101
{'LATITUDE': '22.548114', 'LONGITUDE': '88.4004968'}                                85
{'LATITUDE': '22.581047', 'LONGITUDE': '88.462231'}                                 75
{'LATITUDE': '22.569', 'LONGITUDE': '88.510296'}                                    74
{'LATITUDE': '22.4658051', 'LONGITUDE': '88.384625'}                                64
{'LATITUDE': '22.536025', 'LONGITUDE': '88.35469'}                                  59
{'LATITUDE': '22.60134', 'LONGITUDE': '88.471506'}                                  57
{'LATITUDE': '22.581199', 'LONGITUDE': '88.461896'}                                 54
{'LATITUDE': '22.440158', 'LONGITUDE': '88.294329'}                                 53
{'LATITUDE': '22.715388', 'LONGITUDE': '88.378133'}                                 49
{'LATITUDE': '22.570637', 'LONGITUDE': '88.4617767'}                                48
{'LATITUDE': '22.407335', 'LONGITUDE': '88.413744'}                                 47
{'LATITUDE': '22.537122', 'LONGITUDE': '88.522544'}                                 45
{'LATITUDE': '22.69924', 'LONGITUDE': '88.38115'}                                   44
{'LATITUDE': '22.562087130058', 'LONGITUDE': '88.50552839754'}                      43
{'LATITUDE': '22.730184', 'LONGITUDE': '88.455814'}                                 41
{'LATITUDE': '22.625582', 'LONGITUDE': '88.490761'}                                 40
{'LATITUDE': '22.4606071', 'LONGITUDE': '88.3129969'}                               39
{'LATITUDE': '22.6235821', 'LONGITUDE': '88.4410411'}                               38
{'LATITUDE': '22.481623', 'LONGITUDE': '88.324648'}                                 36
{'LATITUDE': '22.4978086', 'LONGITUDE': '88.3093517'}                               36
{'LATITUDE': '22.48234', 'LONGITUDE': '88.41252'}                                   36
{'LATITUDE': '22.5539607', 'LONGITUDE': '88.3710407'}                               36
{'LATITUDE': '22.567901', 'LONGITUDE': '88.446208'}                                 36
{'LATITUDE': '22.512772', 'LONGITUDE': '88.410254'}                                 34
{'LATITUDE': '22.441052', 'LONGITUDE': '88.289201'}                                 34
{'LATITUDE': '22.48192', 'LONGITUDE': '88.3255'}                                    34
{'LATITUDE': '22.626586', 'LONGITUDE': '88.453086'}                                 33
{'LATITUDE': '22.4927324733', 'LONGITUDE': '88.403800425'}                          33
{'LATITUDE': '22.5026325', 'LONGITUDE': '88.3664528'}                               32
{'LATITUDE': '22.564633', 'LONGITUDE': '88.510995'}                                 31
{'LATITUDE': '22.558639', 'LONGITUDE': '88.394022'}                                 30
{'LATITUDE': '22.5811785', 'LONGITUDE': '88.4961337'}                               30
{'LATITUDE': '22.587219', 'LONGITUDE': '88.502793'}                                 29
{'LATITUDE': '88.378133', 'LONGITUDE': '22.715388'}                                 29
{'LATITUDE': '22.586413', 'LONGITUDE': '88.486072'}                                 29
{'LATITUDE': '22.632642', 'LONGITUDE': '88.479143'}                                 28
{'LATITUDE': '22.533', 'LONGITUDE': '88.359'}                                       28
{'LATITUDE': '22.519587', 'LONGITUDE': '88.376107'}                                 28
{'LATITUDE': '22.645631', 'LONGITUDE': '88.382354'}                                 28
{'LATITUDE': '22.58172', 'LONGITUDE': '88.46404'}                                   27
{'LATITUDE': '22.610332', 'LONGITUDE': '88.376545'}                                 27
{'LATITUDE': '22.624123', 'LONGITUDE': '88.504297'}                                 26
{'LATITUDE': '22.582263', 'LONGITUDE': '88.490696'}                                 26
{'LATITUDE': '22.495', 'LONGITUDE': '88.372'}                                       26
{'LATITUDE': '22.44792', 'LONGITUDE': '88.40389'}                                   26
{'LATITUDE': '22.440427', 'LONGITUDE': '88.401162'}                                 25
{'LATITUDE': '22.5599444', 'LONGITUDE': '88.4957689'}                               25
{'LATITUDE': '22.44213', 'LONGITUDE': '88.29551'}                                   24
{'LATITUDE': '22.509326', 'LONGITUDE': '88.301471'}                                 24
{'LATITUDE': '22.76743', 'LONGITUDE': '88.38835'}                                   24
{'LATITUDE': '22.567407', 'LONGITUDE': '88.517945'}                                 24
{'LATITUDE': '22.627375', 'LONGITUDE': '88.446056'}                                 23
{'LATITUDE': '22.5050813878', 'LONGITUDE': '88.3544763969'}                         22
{'LATITUDE': '22.70124', 'LONGITUDE': '88.47059'}                                   22
{'LATITUDE': '22.489445', 'LONGITUDE': '88.337073'}                                 22
{'LATITUDE': '22.6174760274', 'LONGITUDE': '88.4163038726'}                         21
{'LATITUDE': '22.47069', 'LONGITUDE': '88.36166'}                                   21
{'LATITUDE': '22.567405', 'LONGITUDE': '88.517943'}                                 21
{'LATITUDE': '22.737313', 'LONGITUDE': '88.351235'}                                 20
{'LATITUDE': '22.492559', 'LONGITUDE': '88.339088'}                                 20
{'LATITUDE': '22.589872923653', 'LONGITUDE': '88.45280587272'}                      20
{'LATITUDE': '22.582182', 'LONGITUDE': '88.487992'}                                 20
{'LATITUDE': '22.615992', 'LONGITUDE': '88.47667'}                                  20
{'LATITUDE': '0.0', 'LONGITUDE': '0.0'}                                             19
{'LATITUDE': '22.439576', 'LONGITUDE': '88.435783'}                                 19
{'LATITUDE': '22.49194', 'LONGITUDE': '88.393071'}                                  19
{'LATITUDE': '22.4869926', 'LONGITUDE': '88.3131558'}                               18
{'LATITUDE': '22.4982976', 'LONGITUDE': '88.394025'}                                18
{'LATITUDE': '22.612664', 'LONGITUDE': '88.377414'}                                 18
{'LATITUDE': '22.397196465335', 'LONGITUDE': '88.289029675315'}                     18
{'LATITUDE': '22.586873', 'LONGITUDE': '88.48828'}                                  18
{'LATITUDE': '22.570171', 'LONGITUDE': '88.447571'}                                 18
{'LATITUDE': '22.39216', 'LONGITUDE': '88.41722'}                                   17
{'LATITUDE': '22.59131', 'LONGITUDE': '88.42342'}                                   17
{'LATITUDE': '22.5363984', 'LONGITUDE': '88.3576624'}                               17
{'LATITUDE': '22.53566', 'LONGITUDE': '88.33917'}                                   17
{'LATITUDE': '22.5840276', 'LONGITUDE': '88.4154683'}                               17
{'LATITUDE': '22.578154', 'LONGITUDE': '88.460627'}                                 17
{'LATITUDE': '22.573977', 'LONGITUDE': '88.398249'}                                 16
{'LATITUDE': '22.364731', 'LONGITUDE': '88.439948'}                                 16
{'LATITUDE': '22.557147', 'LONGITUDE': '88.398467'}                                 16
{'LATITUDE': '22.560778290614', 'LONGITUDE': '88.369603303025'}                     16
{'LATITUDE': '22.5323', 'LONGITUDE': '88.34227'}                                    16
{'LATITUDE': '22.5143577', 'LONGITUDE': '88.3251456'}                               16
{'LATITUDE': '22.55484', 'LONGITUDE': '88.389641'}                                  16
{'LATITUDE': '22.582101', 'LONGITUDE': '88.493805'}                                 16
{'LATITUDE': '22.584146', 'LONGITUDE': '88.450439'}                                 16
{'LATITUDE': '22.404246', 'LONGITUDE': '88.412689'}                                 15
{'LATITUDE': '22.632918', 'LONGITUDE': '88.470518'}                                 15
{'LATITUDE': '22.694737', 'LONGITUDE': '88.452862'}                                 15
{'LATITUDE': '22.579337', 'LONGITUDE': '88.500056'}                                 15
{'LATITUDE': '22.597569', 'LONGITUDE': '88.433155'}                                 15
{'LATITUDE': '22.5058175', 'LONGITUDE': '88.3639986'}                               15
{'LATITUDE': '22.629392', 'LONGITUDE': '88.456195'}                                 14
{'LATITUDE': '22.585785', 'LONGITUDE': '88.46386'}                                  14
{'LATITUDE': '22.453029883464', 'LONGITUDE': '88.302563285637'}                     14
{'LATITUDE': '22.583537', 'LONGITUDE': '88.494279'}                                 13
{'LATITUDE': '22.45365', 'LONGITUDE': '88.38791'}                                   13
{'LATITUDE': '22.4788135', 'LONGITUDE': '88.3090479'}                               13
{'LATITUDE': '88.450763', 'LONGITUDE': '22.632687'}                                 13
{'LATITUDE': '22.447584', 'LONGITUDE': '88.299034'}                                 13
{'LATITUDE': '22.547378', 'LONGITUDE': '88.393846'}                                 13
{'LATITUDE': '22.5133969', 'LONGITUDE': '88.356058'}                                13
{'LATITUDE': '22.6998045', 'LONGITUDE': '88.3111348'}                               12
{'LATITUDE': '22.567199', 'LONGITUDE': '88.466205'}                                 12
{'LATITUDE': '22.6342671', 'LONGITUDE': '88.4550798'}                               12
{'LATITUDE': '22.449487', 'LONGITUDE': '88.395542'}                                 12
{'LATITUDE': '22.6189317', 'LONGITUDE': '88.4300897'}                               12
{'LATITUDE': '22.638311', 'LONGITUDE': '88.465164'}                                 12
{'LATITUDE': '22.679944', 'LONGITUDE': '88.455308'}                                 12
{'LATITUDE': '22.509854', 'LONGITUDE': '88.331069'}                                 12
{'LATITUDE': '22.579684', 'LONGITUDE': '88.496334'}                                 12
{'LATITUDE': '22.501139', 'LONGITUDE': '88.406038'}                                 12
{'LATITUDE': '22.49236', 'LONGITUDE': '88.40865'}                                   12
{'LATITUDE': '22.485966', 'LONGITUDE': '88.396453'}                                 12
{'LATITUDE': '22.495292096178', 'LONGITUDE': '88.345985000063'}                     11
{'LATITUDE': '22.621845669308', 'LONGITUDE': '88.380510050037'}                     11
{'LATITUDE': '22.708474', 'LONGITUDE': '88.378311'}                                 11
{'LATITUDE': '22.497595', 'LONGITUDE': '88.333489'}                                 11
{'LATITUDE': '22.627955', 'LONGITUDE': '88.457437'}                                 11
{'LATITUDE': '22.46376', 'LONGITUDE': '88.30718'}                                   11
{'LATITUDE': '22.452311', 'LONGITUDE': '88.39475'}                                  11
{'LATITUDE': '22.561937', 'LONGITUDE': '88.491503'}                                 11
{'LATITUDE': '22.632687', 'LONGITUDE': '88.450763'}                                 11
{'LATITUDE': '22.654268', 'LONGITUDE': '88.4549'}                                   11
{'LATITUDE': '22.457216', 'LONGITUDE': '88.298579'}                                 11
{'LATITUDE': '22.632527', 'LONGITUDE': '88.464186'}                                 11
{'LATITUDE': '22.5158935205', 'LONGITUDE': '88.3850566337'}                         11
{'LATITUDE': '22.47636', 'LONGITUDE': '88.38565'}                                   11
{'LATITUDE': '22.609528', 'LONGITUDE': '88.441345'}                                 11
{'LATITUDE': '22.572646', 'LONGITUDE': '88.36389499999'}                            10
{'LATITUDE': '22.64148', 'LONGITUDE': '88.471821'}                                  10
{'LATITUDE': '22.473451', 'LONGITUDE': '88.368155'}                                 10
{'LATITUDE': '22.636815', 'LONGITUDE': '88.412077'}                                 10
{'LATITUDE': '22.62127', 'LONGITUDE': '88.39289'}                                   10
{'LATITUDE': '22.735015', 'LONGITUDE': '88.387798'}                                 10
{'LATITUDE': '22.596618080885', 'LONGITUDE': '88.262425366419'}                     10
{'LATITUDE': '22.61631', 'LONGITUDE': '88.40235'}                                   10
{'LATITUDE': '22.59112', 'LONGITUDE': '88.40403'}                                   10
{'LATITUDE': '22.680012843035', 'LONGITUDE': '88.461431938766'}                     10
{'LATITUDE': '22.5796842', 'LONGITUDE': '88.414312'}                                10
{'LATITUDE': '22.42735', 'LONGITUDE': '88.26948'}                                   10
{'LATITUDE': '22.6030366', 'LONGITUDE': '88.4040291'}                               10
{'LATITUDE': '22.630198', 'LONGITUDE': '88.48166'}                                  10
{'LATITUDE': '22.498705', 'LONGITUDE': '88.41619'}                                  10
{'LATITUDE': '22.637897', 'LONGITUDE': '88.456113'}                                 10
{'LATITUDE': '22.64271', 'LONGITUDE': '88.466433'}                                  10
{'LATITUDE': '22.565252', 'LONGITUDE': '88.35891'}                                  10
{'LATITUDE': '22.580456024324', 'LONGITUDE': '88.496737179445'}                      9
{'LATITUDE': '22.633414', 'LONGITUDE': '88.459187'}                                  9
{'LATITUDE': '22.44019', 'LONGITUDE': '88.2942'}                                     9
{'LATITUDE': '22.736686', 'LONGITUDE': '88.344729'}                                  9
{'LATITUDE': '22.440842', 'LONGITUDE': '88.298127'}                                  9
{'LATITUDE': '22.5148038', 'LONGITUDE': '88.3688527'}                                9
{'LATITUDE': '22.51986', 'LONGITUDE': '88.23969'}                                    9
{'LATITUDE': '22.48213', 'LONGITUDE': '88.350328'}                                   9
{'LATITUDE': '22.384982', 'LONGITUDE': '88.4186'}                                    9
{'LATITUDE': '22.705223', 'LONGITUDE': '88.459968'}                                  9
{'LATITUDE': '22.601544', 'LONGITUDE': '88.39748'}                                   9
{'LATITUDE': '22.49435', 'LONGITUDE': '88.31612'}                                    9
{'LATITUDE': '22.571168', 'LONGITUDE': '88.448828'}                                  9
{'LATITUDE': '22.592746', 'LONGITUDE': '88.467191'}                                  9
{'LATITUDE': '22.5726552', 'LONGITUDE': '88.3953393'}                                9
{'LATITUDE': '22.4765842969', 'LONGITUDE': '88.3369841946'}                          9
{'LATITUDE': '22.431361', 'LONGITUDE': '88.396724'}                                  9
{'LATITUDE': '22.483811', 'LONGITUDE': '88.329373'}                                  9
{'LATITUDE': '22.51', 'LONGITUDE': '88.23'}                                          9
{'LATITUDE': '22.6352532', 'LONGITUDE': '88.4594179'}                                9
{'LATITUDE': '20.60288', 'LONGITUDE': '88.39774'}                                    9
{'LATITUDE': '22.735636', 'LONGITUDE': '88.463418'}                                  9
{'LATITUDE': '22.49368', 'LONGITUDE': '88.36312'}                                    9
{'LATITUDE': '22.5375144', 'LONGITUDE': '88.331826'}                                 9
{'LATITUDE': '22.634078', 'LONGITUDE': '88.467922'}                                  8
{'LATITUDE': '22.446764', 'LONGITUDE': '88.409807'}                                  8
{'LATITUDE': '22.436182784529', 'LONGITUDE': '88.400077077669'}                      8
{'LATITUDE': '22.62739', 'LONGITUDE': '88.44606'}                                    8
{'LATITUDE': '22.7358049', 'LONGITUDE': '88.4616753'}                                8
{'LATITUDE': '22.691457', 'LONGITUDE': '88.336009'}                                  8
{'LATITUDE': '22.70267', 'LONGITUDE': '88.472819'}                                   8
{'LATITUDE': '22.484581', 'LONGITUDE': '88.389555'}                                  8
{'LATITUDE': '22.57334', 'LONGITUDE': '88.41373'}                                    8
{'LATITUDE': '22.6968663', 'LONGITUDE': '88.4127157'}                                8
{'LATITUDE': '22.70615', 'LONGITUDE': '88.34746'}                                    8
{'LATITUDE': '22.5667378', 'LONGITUDE': '88.3929875'}                                8
{'LATITUDE': '22.615187', 'LONGITUDE': '88.28766'}                                   8
{'LATITUDE': '22.6683782', 'LONGITUDE': '88.384625'}                                 8
{'LATITUDE': '22.6315862', 'LONGITUDE': '88.4294838'}                                8
{'LATITUDE': '22.423411', 'LONGITUDE': '88.264561'}                                  8
{'LATITUDE': '22.628549', 'LONGITUDE': '88.417697'}                                  8
{'LATITUDE': '22.577629', 'LONGITUDE': '88.393108'}                                  8
{'LATITUDE': '22.527656', 'LONGITUDE': '88.389844'}                                  8
{'LATITUDE': '22.548158', 'LONGITUDE': '88.382573'}                                  8
{'LATITUDE': '22.691452', 'LONGITUDE': '88.336'}                                     8
{'LATITUDE': '22.4956601', 'LONGITUDE': '88.3480203'}                                8
{'LATITUDE': '22.44872', 'LONGITUDE': '88.40675'}                                    8
{'LATITUDE': '22.61852', 'LONGITUDE': '88.44082'}                                    8
{'LATITUDE': '22.6226495', 'LONGITUDE': '88.4294838'}                                8
{'LATITUDE': '22.641998', 'LONGITUDE': '88.466071'}                                  8
{'LATITUDE': '22.61059', 'LONGITUDE': '88.41494'}                                    8
{'LATITUDE': '22.440462', 'LONGITUDE': '88.253225'}                                  8
{'LATITUDE': '22.5696', 'LONGITUDE': '88.509926'}                                    8
{'LATITUDE': '22.627717', 'LONGITUDE': '88.44796'}                                   8
{'LATITUDE': '22.489539', 'LONGITUDE': '88.396706'}                                  8
{'LATITUDE': '22.52439', 'LONGITUDE': '88.38114'}                                    8
{'LATITUDE': '22.499905', 'LONGITUDE': '88.360697'}                                  8
{'LATITUDE': '22.633556', 'LONGITUDE': '88.463352'}                                  8
{'LATITUDE': '22.51446', 'LONGITUDE': '88.4093'}                                     8
{'LATITUDE': '22.491352', 'LONGITUDE': '88.361898'}                                  8
{'LATITUDE': '22.626212', 'LONGITUDE': '88.46577'}                                   8
{'LATITUDE': '22.596258', 'LONGITUDE': '88.431366'}                                  8
{'LATITUDE': '22.457914', 'LONGITUDE': '88.3707'}                                    8
{'LATITUDE': '22.465895', 'LONGITUDE': '88.37548'}                                   8
{'LATITUDE': '22.411118', 'LONGITUDE': '88.249644'}                                  7
{'LATITUDE': '22.728398287336', 'LONGITUDE': '88.483555133462'}                      7
{'LATITUDE': '22.649895', 'LONGITUDE': '88.379299'}                                  7
{'LATITUDE': '22.45142485865', 'LONGITUDE': '88.302085970769'}                       7
{'LATITUDE': '22.49179', 'LONGITUDE': '88.346288'}                                   7
{'LATITUDE': '22.434568', 'LONGITUDE': '88.402079'}                                  7
{'LATITUDE': '22.740226', 'LONGITUDE': '88.483812'}                                  7
{'LATITUDE': '22.52025', 'LONGITUDE': '88.34664'}                                    7
{'LATITUDE': '22.698023', 'LONGITUDE': '88.438331'}                                  7
{'LATITUDE': '22.49937', 'LONGITUDE': '88.41354'}                                    7
{'LATITUDE': '22.59077', 'LONGITUDE': '88.39231'}                                    7
{'LATITUDE': '22.5283976', 'LONGITUDE': '88.3527483'}                                7
{'LATITUDE': '22.465168', 'LONGITUDE': '88.334203'}                                  7

In [144]:
df["MAP_DETAILS"].isnull().sum()

np.int64(0)

In [145]:
import ast

# Convert string dict to actual Python dict
df["MAP_DETAILS"] = df["MAP_DETAILS"].apply(lambda x: ast.literal_eval(str(x)))

# Extract latitude and longitude
df["LATITUDE"] = df["MAP_DETAILS"].apply(lambda x: float(x.get("LATITUDE")))
df["LONGITUDE"] = df["MAP_DETAILS"].apply(lambda x: float(x.get("LONGITUDE")))

In [146]:
df.sample()

,PREFERENCE,DESCRIPTION,PROPERTY_TYPE,CITY,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,PRICE_PER_UNIT_AREA,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,MAP_DETAILS,AMENITIES,AREA,PRICE,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,SOCIETY_NAME,BUILDING_NAME,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT,PRICE_INR,PRICE_PER_SQFT,PRICE_PER_SQFT(INR),OWNTYPE_label,FURNISH_label,FACING_label,LATITUDE,LONGITUDE
8224,S,Nav ratan coop. Housing society ltd. Is one of...,Residential Apartment,Kolkata East,1.0,3,3.0,6405.0,2,2,5,4.0,"44,33,47,21",NAV RATAN COOP. HOUSING SOCIETY LTD.,"{'LATITUDE': '22.6006912', 'LONGITUDE': '88.46...","21,44,47,33,101,102",1249 sq.ft.,80 L,3 BHK Flat in New Town,"['UNDER CONSTRUCTION', 'RESALE']",35.0,"[{'category': 'ReligiousPlace', 'text': '2 Rel...",NAV RATAN COOP. HOUSING SOCIETY LTD.,NAV RATAN COOP. HOUSING SOCIETY LTD.,"{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'L...",2.0,3,0.8,1249.0,8000000.0,6405.124099,6405.12,Power of Attorney,Fully furnished,North,22.600691,88.469454

In [147]:
df.drop(columns = ["PRICE_PER_SQFT", "PRICE_INR", "MAP_DETAILS", "PRICE_PER_UNIT_AREA"], inplace  = True)

In [148]:
df.columns

Index(['PREFERENCE', 'DESCRIPTION', 'PROPERTY_TYPE', 'CITY', 'TRANSACT_TYPE',
       'OWNTYPE', 'BEDROOM_NUM', 'FURNISH', 'FACING', 'AGE', 'TOTAL_FLOOR',
       'FEATURES', 'PROP_NAME', 'AMENITIES', 'AREA', 'PRICE', 'PROP_HEADING',
       'SECONDARY_TAGS', 'TOTAL_LANDMARK_COUNT', 'FORMATTED_LANDMARK_DETAILS',
       'SOCIETY_NAME', 'BUILDING_NAME', 'location', 'BALCONY_NUM', 'FLOOR_NUM',
       'PRICE_Cr', 'AREA_SQFT', 'PRICE_PER_SQFT(INR)', 'OWNTYPE_label',
       'FURNISH_label', 'FACING_label', 'LATITUDE', 'LONGITUDE'],
      dtype='str')

In [149]:
df.head(5)

,PREFERENCE,DESCRIPTION,PROPERTY_TYPE,CITY,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,AMENITIES,AREA,PRICE,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,SOCIETY_NAME,BUILDING_NAME,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT,PRICE_PER_SQFT(INR),OWNTYPE_label,FURNISH_label,FACING_label,LATITUDE,LONGITUDE
0,S,Book your 2 BHK flat in Srijan Star Swapno Pur...,Residential Apartment,Kolkata South,2.0,1,2.0,0,0,5,3.0,N,Srijan Star Swapno Puron,NaN,518-623 sq.ft.,19.1 L Onwards,2 BHK Flat in Amtala,"['UNDER CONSTRUCTION', 'NEW BOOKING', 'RERA | ...",2.0,"[{'category': 'Shopping', 'text': '1 Shopping'...",Srijan Star Swapno Puron,Srijan Star Swapno Puron,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.191000,570.5,3347.94,Cooperative Society,Unfurnished,East,22.364447,88.274642
1,S,Make Natural Quest your next home. This projec...,Residential Apartment,Kolkata South,2.0,1,3.0,0,0,5,11.0,N,Natural Quest,NaN,1110-1121 sq.ft.,1.17 - 1.18 Cr,3 BHK Flat in EM Bypass,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",9.0,"[{'category': 'MetroStation', 'text': '1 Metro...",Natural Quest,Natural Quest,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.590000,1115.5,5289.11,Cooperative Society,Unfurnished,East,22.518795,88.388439
2,S,"Book your 3 BHK apartment in Garia, Kolkata So...",Residential Apartment,Kolkata South,2.0,1,3.0,0,0,5,20.0,N,Ganguly 4Sight Eminence,NaN,1376-1516 sq.ft.,1.22 - 1.35 Cr,3 BHK Flat in Garia,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",6.0,"[{'category': 'Shopping', 'text': '1 Shopping'...",Ganguly 4Sight Eminence,Ganguly 4Sight Eminence,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.675000,1446.0,4668.05,Cooperative Society,Unfurnished,East,22.513765,88.366680
3,S,"Dev bhumi in joka, kolkata south by ocean land...",Residential Land,Kolkata South,2.0,1,NaN,0,0,0,0.0,N,Dev Bhumi,NaN,720-2880 sq.ft.,1.5 - 5.99 L,Residential land / Plot in Joka,"['READY TO MOVE', 'NEW BOOKING']",13.0,"[{'category': 'MetroStation', 'text': '2 Metro...",Dev Bhumi,Dev Bhumi,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,NaN,0.029950,1800.0,166.39,Cooperative Society,Unfurnished,East,22.453830,88.249572
4,S,Let your dream of owning a flat come true with...,Residential Apartment,Kolkata South,2.0,1,3.0,0,0,5,19.0,N,DTC Sojon,NaN,1130-1460 sq.ft.,60 - 75 L,3 BHK Flat in Joka,"['UNDER CONSTRUCTION', 'NEW BOOKING']",11.0,"[{'category': 'MetroStation', 'text': '1 Metro...",DTC Sojon,DTC Sojon,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.375003,1295.0,2895.78,Cooperative Society,Unfurnished,East,22.442130,88.295510

In [150]:
df[["DESCRIPTION", "PROPERTY_TYPE", "PROP_NAME", "PROP_HEADING", "SOCIETY_NAME", "BUILDING_NAME"]].head()

,DESCRIPTION,PROPERTY_TYPE,PROP_NAME,PROP_HEADING,SOCIETY_NAME,BUILDING_NAME
0,Book your 2 BHK flat in Srijan Star Swapno Pur...,Residential Apartment,Srijan Star Swapno Puron,2 BHK Flat in Amtala,Srijan Star Swapno Puron,Srijan Star Swapno Puron
1,Make Natural Quest your next home. This projec...,Residential Apartment,Natural Quest,3 BHK Flat in EM Bypass,Natural Quest,Natural Quest
2,"Book your 3 BHK apartment in Garia, Kolkata So...",Residential Apartment,Ganguly 4Sight Eminence,3 BHK Flat in Garia,Ganguly 4Sight Eminence,Ganguly 4Sight Eminence
3,"Dev bhumi in joka, kolkata south by ocean land...",Residential Land,Dev Bhumi,Residential land / Plot in Joka,Dev Bhumi,Dev Bhumi
4,Let your dream of owning a flat come true with...,Residential Apartment,DTC Sojon,3 BHK Flat in Joka,DTC Sojon,DTC Sojon

In [151]:
df["BUILDING_NAME"].shape

(8797,)

In [176]:
df[df["PROP_NAME"] != df["SOCIETY_NAME"]][["DESCRIPTION", "PROP_NAME", "SOCIETY_NAME", "BUILDING_NAME"]].head()
df[df["PROP_NAME"] != df["SOCIETY_NAME"]]["DESCRIPTION"]
# df[df["PROP_NAME"] != df["BUILDING_NAME"]].shape

38      Well maintained & secured pg/paying guest in k...
130     Pg for boy availaible for rent, market is 2 mi...
196                This area is very homely and peaceful.
236     Two minutes walking distance from prince anwar...
237     Stunning independent house villa for sale in m...
282     It is a 2 storey building having 2 bedrooms, 1...
288     A fully renovated. Stylish interiors, excellen...
291     Independent/builder floor is available for pg....
293     Pg for girls in jadavpur- Food and wifi is inc...
295     Double sharring/ single room pg for girls at k...
300     Government registered pg for females and highl...
312     Stunning independent house villa for sale in k...
317     We have a house/villa available for sale in ra...
326     Residential land available for sale in dover t...
341     An impeccable opportunity is here for those wh...
346     This spacious builder floor apartment is locat...
352     My property is in prime location . 1 min walk ...
359     Spacious rooms,nearby railway station and mark...
393     Pg is located in a very serene area.Rooms are ...
394     A tidy, clean girls' pg is available near kabi...
395     Nandi ladies pg, dum dum station, near bandhu ...
396     This is a gents stay facility\n2 out of 4 room...
397     A decent semi-Furnished pg/paying guest in bha...
398     Near to masterda surya sen metro station , ban...
399     Nandi ladies pg, 4 shearing bed available, dum...
401     My property is situated beside the main road a...
402     At prof.S home pg accommodation for male stude...
403     2bhk builder floor apartment for resale in tol...
408     Pollution free locality , 790 mter from bhadre...
411     It is a very good place for residential purpos...
422     Calm and cool residential area with full of gr...
426     Check out this 4 bhk builder floor in behala. ...
428     Best in class property available at kabardanga...
436     Looking for magnificent 3 bhk builder floors i...
437     Centrally located property near sovabazar metr...
439                      Good location near nangi station
441     We are proud owners of house/villa available f...
445     South-East facing well maintained independent ...
451     Very nice property. And every thing is allrigh...
457     Discover smartly planned 2 bhk builder floor i...
459     1 bath, unfurnished, ground floor (Of 3), over...
478     Best in class property available at kasba loca...
481     Best in class property available at rajpur son...
483     Best in class property available at jadavpur l...
500     Location - Rajarhat, kolkata east\nStatus - Rr...
502     Enjoy nature in urban area. Buy your dream hou...
525     Do you wish to buy an independent house in gar...
529     My property is near by sakherbazar metro stati...
535     Plot of land with a 2-Storey house; 4 bedrooms...
542     Best in class property available at jadavpur l...
546     Independent/builder floor is available for sel...
551     Prime posh residential area , metro stn, bus s...
556     Prime location\nGood quality interior\nPremium...
557     Location is on the ground floor , well connect...
577     Experience luxury living in a newly built, spa...
595     Maa ashirbad boys and girls pg at ruby kalikap...
596                 Near sodhpur market, decent locality,
622     24 hours water supply and market and hospital ...
624     There are multiple rooms available for student...
625     Strategically located pg/paying guest in dum d...
627     If you are looking for pg/paying guest in sect...
628     Single room: 5500 per bed\nDouble sharing: 450...
629     4th shearing bed available, nandi ladies pg, d...
630     Well maintained & secured pg/paying guest in k...
633     Independent floor available for sale in belgha...
639     An impeccable opportunity is here for those wh...
640     Residential plot for resale in thakurpukur baz...
701     This beautiful 2 bhk builder floor for rent in...
705     It is situated on main road, it has seperate e...
812     Residential land that will help you to live in...
934     Newly renovated, best class interior, ample of...
936     Recently renovated the two storied building. C...
937     An aesthetically built 3 storied house is for ...
942     This is a 15 cottah property located on kp mon...
946     4 bhk builder floor in deshapriya park enjoys ...
948     This property is an independent , stand alone ...
949     Best in class property available at tollygunge...
1011    This 12 bhk house for sale in new town action ...
1017    All within couple of minutes ..... Peerless ho...
1020    The property is inside a gated complex with li...
1025    Spacious room, well condition. Totally interfe...
1027    Agents/ brokers/ time wasters strictly excused...
1096    Best in class property available at sinthi loc...
1107    Land at patuli with approved g+3 residential s...
1108    Best in class property available at shobha baz...
1109    Planning to buy an individual house in west be...
1112    Chetla is one of kolkata south's most sought a...
1123    Very close to santragachi railway station and ...
1129    2 bath, semifurnished, 3rd floor (Of 5), overl...
1195    It's a bigger land to make any ware house, or ...
1198    Land is 1/2 km from katatala bus-Stop, water e...
1203    East facing main road. East-South-West three s...
1204    Airy 3 sided open luxurious flat equipped with...
1207    Elias road, near pathagar, agarpara, kolkata -...
1303    A newly constructed 3 storied independent bung...
1313    Residential land available for sale in chit ka...
1314    Check out this 3 bhk house for sale in golf cl...
1335    This 5 bhk house for sale in batanagar is an i...
1338    Fully furnished flat. Interested people plz co...
1370    Very nice and peaceful locality. Very good nei...
1373    Looking for magnificent 4 bhk floors in naktal...
1385    The property is located to the nearest railway...
1386    2 minutes from durgapur road, 5 minutes from d...
1391    Interested to sell independent house.It has sp...
1410    Garden facing flat in swiss park near rabindra...
1473    Carefully laid out in the prime location of ko...
1479    Planning to purchase a plot in kolkata south? ...
1514    This property is available in prime location. ...
1515    A lovely 3 bhk house for rent in ballygunge is...
1551    Fantastic location, close to metro connection,...
1552    Dum dum metro, m c garden road, independent/bu...
1555    3bhk multistorey apartment for resale in sukch...
1568    Carefully laid out in the prime location of ko...
1569    On a prime location at laketown jessore road m...
1591    Prime location and on the main street, with th...
1599    Totally separate entrance.. Taotal marbel floo...
1605    Just 3.2 kms from thakurpukur bazar at bakhrah...
1684    Best in class property available at netaji nag...
1685    This plot is beside of southern bypass 2nd plo...
1686                Near noapara metro station 2 km away.
1687    Looking for magnificent 2 bhk builder floors i...
1688    Master bedroom with attached bathroom along wi...
1690    In a green environment with east and south per...
1693    South east west facing bastu compliant propert...
1777    Communication is very good.It is near bansdron...
1796    Very well maintained, neat and clean, spacious...
1804    We have a house/villa available for sale in sh...
1820    Best in class property available at sodepur lo...
1828    This house is situated at a 5 mins walking dis...
1834    One the road. Peaceful area. Near by market an...
1843    It newly constructed. 24 hrs electricity and w...
1855    House/villa available for rent in garfa, kolka...
1862    Approved by hdfc bank. Regent park is one of t...
1895        Schools, colleges and hospitals are all there
1900    This project is very modern in south kolkata n...
1901    This project is very beautiful project . Raspu...
1902    Raspunja city project is residential township ...
1903    This project is very beautiful, nice and immed...
1908    Residential land available for sale in baruipu...
1911        1st floor property facing the road kabardanga
1912    Fully painted with false ceiling and led light...
1920    Hidco allotted residential individual 4.5 kath...
1930    Beside mankundu station . Cesc area.All papers ok
1956    The plot is 4 to 5 minutes walking from biren ...
1964    Near diamond plaza,jossore road and vip road b...
1989    Property located on 30 ft wide road near phool...
1991    Only 5-7 min walking distance from piali stati...
2132    Find this 2 bhk house for rent in kasba, kolka...
2136    Hidco allotted residential individual 2 sides ...
2159    Hidco allotted residential individual 4.5 kath...
2160    Hidco allotted residential individual 2.24 cor...
2167    Vargin and new house (Unused) very nice good q...
2178    This 2 bhk house for sale in khardah, a well p...
2234    This house is having total four floors and thi...
2236    Mutation,conversion completed....Plan is compl...
2237    This independent floor is a spacious home desi...
2239    Property in ganguly bagan, ready to sell each ...
2240    House/villa available for rent in maheshtala, ...
2244    This building have 1 bedroom, 1 bathroom, open...
2261    Foresighted residential land that will help yo...
2305    It is peaceful residential area with all moder...
2306    Fully furnished mess for girls with all amenit...
2320    Appealingly designed, this 2bhk apartment loca...
2322    5 min walking distance from vip road.10 min fr...
2323    In a hidco allotted 4.5 kattha plot, an under ...
2325       This project very nice and near by joka metro.
2326    This project is very beautiful, nice and immed...
2327    Raspunja city is a fast growing real estate pr...
2328    Ground floor property of an independent house....
2330    Market, bus/auto stand, school, college, bank,...
2331    Good location rent and good condition\n Additi...
2334    Property comes with a good construction qualit...
2335    South west open, south faced balcony, ample ai...
2343    This 6 bhk house for sale in sector 2 salt lak...
2346    1bhk multistorey apartment for resale in sakhe...
2347    2 cottah residential land in an amazingly peac...
2354    Brand new high quality construction with marbl...
2396    Hidco allotted residential individual freehold...
2409    Semi furnished .Auto stand near .Market near.S...
2473    I want to rent out my property.My flat is well...
2474    Near rail station and colony more\n Additional...
2488                 Nice property and good location rent
2490    1bedroom,1 dinning, 2 bathroom, semi-Furnished...
2495    Action area 3 newtown hidco allowed plot 2.24 ...
2526    Corner plot 2.24 kattha 3 side open individual...
2527    Corner plot 4.5 kattha 3 side open individual ...
2598    It is walking distance from baruipur 4 no. Pla...
2599    It is located 10 mins walking from dum dum sta...
2607    Bastu, corner property, free parking, metro rail.
2667    This 2 bhk house for rent in purbachal, is ava...
2679    3katha freehold hidco land for sale in near ro...
2690    Vastu approved land north east corner plot bot...
2702    Check out this plot for sale in action area 3,...
2703    Planning to build residence in kolkata east? T...
2705    This beautiful 3 bhk builder floor for rent in...
2747    Hidco allotted residential individual 4.5 kath...
2759    We are proud owners of land available for sale...
2783    Walking distance from bishorepara kodalia rail...
2787    3 bhk duplex villa with 2.5 katha land covered...
2790    Big & well-Ventilated rooms, high ceiling, ver...
2793    House/villa available for rent in sodepur, kol...
2833    A premium resort themed residential project lo...
2834    New town is an ideal location for buying resid...
2894    Close to patipukur and dumdum rail station, re...
2908    2 bhk well decorated furnished flat near tolly...
2913    Kolkataproperties.In offers you a north facing...
2937    This land where you must set up your new home....
2964    This is a independent house with 3 different p...
2967    3bhk residential house for rent in ultadanga c...
2983    Good condition and good location rent\n Additi...
2985                Good condition and good location rent
2987                Good condition and good location rent
2993                      Nice property and good location
2995       The house is located one of the best location.
3037       Residential plot for resale in barasat barasat
3039    Check out this 4 bhk house for sale in behala ...
3040    House with spacious room with well maintained ...
3055    G4 building (House) total 2600sft for sell eac...
3066    Located in prime locality with all modern day ...
3136       Independent builder floor available in nayabad
3184    3 bhk modern villa sale on great developed are...
3186    Description of project on sankharipota,, near-...
3196    Looking for a plot in a prime location of kolk...
3201    To build a splendid residence, this plot in jo...
3202    Joka is an ideal location for buying residenti...
3203    Spacious, ready to build plot in joka, kolkata...
3204    Joka is an ideal location for buying residenti...
3205    Plot for sale in joka is available in kolkata ...
3206    To build a splendid residence, this plot in jo...
3207    This project is very good,istant possition , e...
3210    Raspunja city is a fast growing real estate pr...
3212    Raspunja city offers you residential township ...
3213    This project is very modern in south kolkata n...
3214    This project is very modern in south kolkata n...
3216    This project is very modern in south kolkata n...
3217    This project is very beautiful project . Raspu...
3218    Raspunja city project is residential township ...
3224    All paper upto date loanable property with res...
3225    All paper upto date loanable property with res...
3232    Very near to anandapur police station with g p...
3233    Very near to anandapur police station with lan...
3236    Very near to anandapur police station with lan...
3244    3 khatha land with g+3 plan sanction on 40ft w...
3264    Good location and good qualities rent\n Additi...
3265    Good condition and good location rent\n Additi...
3266                Good condition and good location rent
3267                Good condition and good location rent
3292    Are you planning to buy your dream home? You c...
3293    This 5 bhk house for sale in sector 2 salt lak...
3294    This 5 bhk house for sale in sector 3 salt lak...
3295    Are you planning to buy your dream home? You c...
3296    Wishing to settle down in an individual house ...
3297    This builder floor for rent in sector 2 salt l...
3298    Do you wish to buy an independent house in sec...
3299    This 4 bhk house for sale in sector 3 salt lak...
3300    Do you wish to buy an independent house in sec...
3301    Planning to buy an individual house in kolkata...
3302    This 5 bhk house for sale in sector 2 salt lak...
3303    Do you wish to buy an independent house in sec...
3304    Carefully laid out in the prime location of ko...
3308    Explore this spacious builder floor for rent i...
3315    Are you planning to buy your dream home? You c...
3372    2 storied ready to move independent house in b...
3396    This builder floor for rent in kalikapur, kolk...
3418    Good location and good condition rent\n Additi...
3429                Good location and good condition rent
3455    A 4 floor pent-House measuring 6025sqft availa...
3463    Land for sale for investment purpose in new to...
3464    Land for sale for investment purpose in new to...
3465    Land for sale for investment purpose in new to...
3466    Land for sale for investment purpose in new to...
3467    Project smart village 2k, 2.5, 3k, 5k availabl...
3468    Land for sale for investment purpose in new to...
3469               Land for sale in newtown, kolkata east
3473    Why contact any dalal ???? Contact company dir...
3477    Why contact any dalal ???? Contact company dir...
3478    Why contact any dalal ???? Contact company dir...
3479    Why contact any dalal ???? Contact company dir...
3480    Why contact any dalal ???? Contact company dir...
3481    Why contact any dalal ???? Contact company dir...
3482    Why contact any dalal ???? Contact company dir...
3483    Why contact any dalal ???? Contact company dir...
3485    Why contact any dalal ???? Contact company dir...
3495    Our company is a young, dynamic & vibrant land...
3500    Our company is a young, dynamic & vibrant land...
3507    School \n1. Childrens academy 0.5 km\n2. Ss ac...
3511    Why contact any dalal contact directly company...
3523    3 bhk sale in action area 1c 3 room 2 bathroom...
3563    2 bhk well maintained flat with big dining and...
3565    6 bedroom, 3 kitchen, 4 bathroom, 1 cover park...
3573    Good property for sale in birati in good condi...
3617    Check out this well-Constructed builder floor ...
3618    3 bhk flat available for sale near dlf\n Addit...
3980    Plot for sale in new town is available in kolk...
3984    This plot in new town provides you great oppor...
3986    Premium resort themed residential project loca...
3987    Plot for sale in new town is available in kolk...
3988    Fresco fountain city of vriddhi landmart is a ...
3991    A premium resort themed residential project lo...
3992    Tar roads underground drainage system, water a...
3993    A premium resort themed residential project lo...
3995    A 125 acre integrated with residential, commer...
3998    A 125 acre integrated with residential, commer...
3999    Looking for a plot in a prime location of kolk...
4004    Looking for a plot in a prime location of kolk...
4008    This plot in new town provides you great oppor...
4014    Very low price residential plot available near...
4111    Land for sale for investment purpose in new to...
4129    Entire house available for rent in location li...
4132    A nice property in bunglow type house in good ...
4139    Plot for sale near kheyadah high school, 6 km ...
4142    It's a 2katha and above land with construction...
4180    Since the beginning of time, green has signifi...
4194    Development free, agency charge free, nearest ...
4226              10 kottah plot near joka metro for sale
4405    24 bed room 24 bathroom full firnished gust ho...
4406    Corner plot 2.24 katha just opposite to bangla...
4407    Hidco land freehold 2.25 katha for sale in nea...
4425    2.25 katha hidco allotted residential plot for...
4428    Hidco plot resonable price for sell 3 katha in...
4429    3 katha freehold hidco land for sale in near r...
4449    Freehold 2.25 katha hidco land for sale in nea...
4453    2 side open hidco plot for sale in near 21 no ...
4459    3 bhk new flat sell in near just back side to ...
4460    3 katha freehold plot hidco alloted for sale i...
4470    Hidco allotted residential 2.25 katha plot for...
4471    4.48 katha hidco allooted freehold plot for sa...
4478    Good location 3 katha freehold hidco alloted p...
4483    4.48 katha hidco alloted freehold plot for sal...
4507    2.25 katha hidco alloted freehold plot for sal...
4509    Best location 4.48 katha hidco land freehold p...
4515    Hidco land 4.50 katha good position, ce block ...
4521    Beautiful house ground plus 2 storied on 3 kat...
4555    This is a banglow bari fir sale in good condit...
4577    Plot for sale in new town action area 1 is ava...
4578    Check out this plot for sale in action area 3,...
4579                 Main road good location and locality
4594    Explore this spacious builder floor for rent i...
4663    Action area 1 is an ideal location for buying ...
4664    Plot for sale in action area 3 is available in...
4665    Check out this plot for sale in action area 3,...
4666    Planning to build residence in kolkata east? T...
4667    Planning to build residence in kolkata east? T...
4668    Plot for sale in new town action area 1a is av...

In [164]:
(df["PROP_NAME"] == df["SOCIETY_NAME"]).all()
# (df["PROP_NAME"] == df["building_name"]).all()

np.False_

In [177]:
df.drop(columns=["SOCIETY_NAME", "BUILDING_NAME"], inplace= True)

In [159]:
idx = df[(df["BUILDING_NAME"].isnull()) & (~df["SOCIETY_NAME"].isnull()) & (~df["PROP_NAME"].isnull())].index

# idx = df[
#     (df["BUILDING_NAME"].isnull()) &
#     (~df["SOCIETY_NAME"].isnull()) &
#     (~df["PROP_NAME"].isnull())
# ].index


df.iloc[idx].head()

,PREFERENCE,DESCRIPTION,PROPERTY_TYPE,CITY,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,AMENITIES,AREA,PRICE,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,SOCIETY_NAME,BUILDING_NAME,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT,PRICE_PER_SQFT(INR),OWNTYPE_label,FURNISH_label,FACING_label,LATITUDE,LONGITUDE
3101,S,Zero brokerage this subh apartment is in one o...,Residential Apartment,Kolkata North,1.0,1,3.0,4,7,5,4.0,",2,,5,,20,,21,,23,,24,,25,,40,,41,,47,",subh apartment,NaN,1007 sq.ft.,43 L,3 BHK Flat in Baguiati,"['UNDER CONSTRUCTION', 'RESALE', 'POSSESSION I...",NaN,NaN,subh apartment,NaN,"{'CITY': '26', 'CITY_NAME': 'Kolkata North', '...",1.0,2,0.4300,1007.0,4270.11,Cooperative Society,Other,North-West,22.618932,88.430090
3755,S,"This beautiful 3 bhk flat in madhyamgram, kolk...",Residential Apartment,Kolkata North,1.0,1,3.0,2,5,5,11.0,",1,,2,,3,,4,,5,,6,,9,,12,,17,,19,,20,,21,,23,,...",new booking,NaN,1150 sq.ft.,52 L,3 BHK Flat in Madhyamgram,"['UNDER CONSTRUCTION', 'RESALE', 'POSSESSION I...",NaN,NaN,new booking,NaN,"{'CITY': '26', 'CITY_NAME': 'Kolkata North', '...",1.0,1,0.5200,1150.0,4521.74,Cooperative Society,Fully furnished,South-East,22.694737,88.452862
3921,S,Check out this 3 bhk apartment for sale in bin...,Residential Apartment,Kolkata East,1.0,3,3.0,2,3,5,4.0,",4,,21,,33,,42,,47,",binoba coop. housing society ltd.,NaN,1450 sq.ft.,61 L,3 BHK Flat in New Town,"['UNDER CONSTRUCTION', 'RESALE', 'POSSESSION I...",NaN,NaN,binoba coop. housing society ltd.,NaN,"{'CITY': '28', 'CITY_NAME': 'Kolkata East', 'L...",2.0,4,0.6100,1450.0,4206.90,Power of Attorney,Fully furnished,South,22.600691,88.469454
4255,S,"This 4 bhk flat is located in on request, whic...",Residential Apartment,Kolkata South,1.0,1,4.0,2,2,1,5.0,",2,,4,,5,,6,,17,,19,,20,,21,,23,,24,",on request,NaN,2395 sq.ft.,3.95 Cr,4 BHK Flat in Southern Avenue,"['READY TO MOVE', 'RESALE']",NaN,NaN,on request,NaN,"{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",1.0,3,3.9500,2395.0,16492.69,Cooperative Society,Fully furnished,North,22.514070,88.360856
6010,S,"This 2 bhk flat is located in on request, whic...",Residential Apartment,Kolkata North,1.0,1,2.0,2,5,1,6.0,",4,,5,,19,,21,,23,",on request,NaN,953 sq.ft.,42.89 L,2 BHK Flat in Teghoria,"['READY TO MOVE', 'RESALE']",NaN,NaN,on request,NaN,"{'CITY': '26', 'CITY_NAME': 'Kolkata North', '...",1.0,1,0.4289,953.0,4500.52,Cooperative Society,Fully furnished,South-East,22.624557,88.434250

In [161]:
df["BUILDING_NAME"] = df["BUILDING_NAME"].str.lower()

In [155]:
df["PROP_NAME"].fillna("") + " " + df["SOCIETY_NAME"].fillna("") + " " + df["BUILDING_NAME"].fillna("")

0       Srijan Star Swapno Puron Srijan Star Swapno Pu...
1               Natural Quest Natural Quest Natural Quest
2       Ganguly 4Sight Eminence Ganguly 4Sight Eminenc...
3                           Dev Bhumi Dev Bhumi Dev Bhumi
4                           DTC Sojon DTC Sojon DTC Sojon
5                           DTC Sojon DTC Sojon DTC Sojon
6               The Signature The Signature The Signature
7         Bhawani Bandhan Bhawani Bandhan Bhawani Bandhan
8       Symphony Proxima Symphony Proxima Symphony Pro...
9       Symphony Proxima Symphony Proxima Symphony Pro...
10      Speedland Raspunja Township Speedland Raspunja...
11      Ganga Jamuna Apartment Ganga Jamuna Apartment ...
12      Magnolia Sunshine Magnolia Sunshine Magnolia S...
13      Eden Spring Villas Eden Spring Villas Eden Spr...
14      Ganguly 4Sight Desire Ganguly 4Sight Desire Ga...
15      Ganguly 4Sight Desire Ganguly 4Sight Desire Ga...
16      Ganguly 4Sight Desire Ganguly 4Sight Desire Ga...
17           Newtown Villas Newtown Villas Newtown Villas
18      DTC Capital City DTC Capital City DTC Capital ...
19      DTC Capital City DTC Capital City DTC Capital ...
20      DTC Capital City DTC Capital City DTC Capital ...
21                          Ascon Era Ascon Era Ascon Era
22                          Ascon Era Ascon Era Ascon Era
23                          Ascon Era Ascon Era Ascon Era
24      Bhariravi apartment  Bhariravi apartment  Bhar...
25      Vijay Lakshmi Apartments Vijay Lakshmi Apartme...
26      Prasad Rare Earth Prasad Rare Earth Prasad Rar...
27      Prasad Rare Earth Prasad Rare Earth Prasad Rar...
28                 Sai Sarovaar Sai Sarovaar Sai Sarovaar
29                 Sai Sarovaar Sai Sarovaar Sai Sarovaar
30                       Midtown 63 Midtown 63 Midtown 63
31      Joyville Western Height Joyville Western Heigh...
32      Joyville Western Height Joyville Western Heigh...
33           Merlin Serenia Merlin Serenia Merlin Serenia
34           Merlin Serenia Merlin Serenia Merlin Serenia
35           Merlin Serenia Merlin Serenia Merlin Serenia
36      Sunday On The House Sunday On The House Sunday...
37      Sunday On The House Sunday On The House Sunday...
38
39      Ariyan Housing Complex Ariyan Housing Complex ...
40              Happy Homes V Happy Homes V Happy Homes V
41              Happy Homes V Happy Homes V Happy Homes V
42      PD Kasturi Heights PD Kasturi Heights PD Kastu...
43           Harbour Greens Harbour Greens Harbour Greens
44           Harbour Greens Harbour Greens Harbour Greens
45      Spotlight Countryside Spotlight Countryside Sp...
46      Spotlight Countryside Spotlight Countryside Sp...
47                    Tirath Guru Tirath Guru Tirath Guru
48              SGIL Gardenia SGIL Gardenia SGIL Gardenia
49              SGIL Gardenia SGIL Gardenia SGIL Gardenia
50      Oswal Orchard Amritaya Oswal Orchard Amritaya ...
51      Oswal Orchard Amritaya Oswal Orchard Amritaya ...
52           Merlin Skygaze Merlin Skygaze Merlin Skygaze
53           Merlin Skygaze Merlin Skygaze Merlin Skygaze
54                 Merlin Oikyo Merlin Oikyo Merlin Oikyo
55                 Merlin Oikyo Merlin Oikyo Merlin Oikyo
56                    Merlin Rise Merlin Rise Merlin Rise
57                    Merlin Rise Merlin Rise Merlin Rise
58      Ganguly 4Sight Vivante Ganguly 4Sight Vivante ...
59      Ganguly 4Sight Vivante Ganguly 4Sight Vivante ...
60      Urban Vista Phase 1 Urban Vista Phase 1 Urban ...
61      Urban Vista Phase 1 Urban Vista Phase 1 Urban ...
62      Loharuka Green Heights Phase 2 Loharuka Green ...
63      Loharuka Green Heights Phase 2 Loharuka Green ...
64      Atri Surya Toron Atri Surya Toron Atri Surya T...
65                          Atri Rays Atri Rays Atri Rays
66                          Atri Rays Atri Rays Atri Rays
67                          Atri Aqua Atri Aqua Atri Aqua
68                          Atri Aqua Atri Aqua Atri Aqua
69      Atri Surya Toron Atri Surya Toron Atri Surya T...
70        Bhawani Sunrise Bhawani Sunrise Bhawani Sunrise
71        Bhawani Sunrise Bhawani Sunrise Bhawani Sunrise
72      Natural City Madhyamgram Natural City Madhyamg...
73      Natural City Madhyamgram Natural City Madhyamg...
74      Greenland The Eco Village Greenland The Eco Vi...
75      Greenland The Eco Village Greenland The Eco Vi...
76           Southern Woods Southern Woods Southern Woods
77           Southern Woods Southern Woods Southern Woods
78                                   Urbana Urbana Urbana
79                                   Urbana Urbana Urbana
80      Swapnabhumi Shantiniketan Swapnabhumi Shantini...
81      Bhawani Tridev Garden 2 Bhawani Tridev Garden ...
82      Bhawani Tridev Garden 2 Bhawani Tridev Garden ...
83                       Kalim Zeus Kalim Zeus Kalim Zeus
84                       Kalim Zeus Kalim Zeus Kalim Zeus
85      Signature The Landmark Signature The Landmark ...
86      Signature The Landmark Signature The Landmark ...
87      Tilottama Natural City Tilottama Natural City ...
88      Tilottama Natural City Tilottama Natural City ...
89              Metro Heights Metro Heights Metro Heights
90              Metro Heights Metro Heights Metro Heights
91      Eden Tolly Court Eden Tolly Court Eden Tolly C...
92      Eden Tolly Court Eden Tolly Court Eden Tolly C...
93      Magnolia Fantasia Magnolia Fantasia Magnolia F...
94      Magnolia Fantasia Magnolia Fantasia Magnolia F...
95      Magnolia Merlion Magnolia Merlion Magnolia Mer...
96      Magnolia Merlion Magnolia Merlion Magnolia Mer...
97      Magnolia Signature Magnolia Signature Magnolia...
98      Magnolia Signature Magnolia Signature Magnolia...
99              Natural Quest Natural Quest Natural Quest
100                Eden Luxuria Eden Luxuria Eden Luxuria
101                Eden Luxuria Eden Luxuria Eden Luxuria
102     GPS Meena Fortuna GPS Meena Fortuna GPS Meena ...
103             Nirman Aalaya Nirman Aalaya Nirman Aalaya
104     Spotlight Rainbow Spotlight Rainbow Spotlight ...
105     Spotlight Rainbow Spotlight Rainbow Spotlight ...
106       Plezers Habitat Plezers Habitat Plezers Habitat
107       Plezers Habitat Plezers Habitat Plezers Habitat
108     Urban Greens Phase 2B Urban Greens Phase 2B Ur...
109     Urban Greens Phase 2B Urban Greens Phase 2B Ur...
110                   Merlin Rise Merlin Rise Merlin Rise
111                   Merlin Rise Merlin Rise Merlin Rise
112                               PS Jiva PS Jiva PS Jiva
113                               PS Jiva PS Jiva PS Jiva
114     Merlin Lakescape Merlin Lakescape Merlin Lakes...
115     Merlin Lakescape Merlin Lakescape Merlin Lakes...
116     Merlin Lakescape Merlin Lakescape Merlin Lakes...
117                Merlin Avana Merlin Avana Merlin Avana
118                Merlin Avana Merlin Avana Merlin Avana
119                Merlin Avana Merlin Avana Merlin Avana
120       Skyline Imperia Skyline Imperia Skyline Imperia
121       Skyline Imperia Skyline Imperia Skyline Imperia
122     Dimitra Shantineer Dimitra Shantineer Dimitra ...
123     Dimitra Shantineer Dimitra Shantineer Dimitra ...
124     Dimitra Shantineer Dimitra Shantineer Dimitra ...
125             Bhawani Inara Bhawani Inara Bhawani Inara
126             Bhawani Inara Bhawani Inara Bhawani Inara
127             Bhawani Inara Bhawani Inara Bhawani Inara
128     Green View Residency Green View Residency Gree...
129     Green View Residency Green View Residency Gree...
130
131     OAS Lake Life Township OAS Lake Life Township ...
132     OAS Lake Life Township OAS Lake Life Township ...
133     OAS Lake Life Township OAS Lake Life Township ...
134     Squaremark Mohorkoonjo Squaremark Mohorkoonjo ...
135     Squaremark Mohorkoonjo Squaremark Mohorkoonjo ...
136       Southern Valley Southern Valley Southern Valley
137             Prabha Aikyam Prabha Aikyam Prabha Aikyam
138             Prabha Aikyam Prabha Aikyam Prabha Aikyam
139             Purti Flowers Purti Flowers Purti Flowers
140             Purti Flowers Purti Flowers Purti Flowers
141                         Woodwinds Woodwinds Woodwinds
142                         Woodwinds Woodwinds Woodwinds
143     Sapnil Residencydd Sapnil Residencydd Sapnil R...
144     Sapnil Residencydd Sapnil Residencydd Sapnil R...
145     Sapnil Residencydd Sapnil Residencydd Sapnil R...
146     Larica Garden Residence Larica Garden Residenc...
147     Larica Garden Residence Larica Garden Residenc...
148     Larica Garden Residence Larica Garden Residenc...
149     Eden Willow Estate Eden Willow Estate Eden Wil...
150     Eden Willow Estate Eden Willow Estate Eden Wil...
151     Eden Willow Estate Eden Willow Estate Eden Wil...
152       Eden Meghbalika Eden Meghbalika Eden Meghbalika
153       Eden Meghbalika Eden Meghbalika Eden Meghbalika
154       Magnolia Empire Magnolia Empire Magnolia Empire
155       Magnolia Empire Magnolia Empire Magnolia Empire
156       Magnolia Empire Magnolia Empire Magnolia Empire
157                            Amantran Amantran Amantran
158                            Amantran Amantran Amantran
159                            Amantran Amantran Amantran
160     Orbit Urban Park Orbit Urban Park Orbit Urban ...
161     Orbit Urban Park Orbit Urban Park Orbit Urban ...
162                      Sun Sumukh Sun Sumukh Sun Sumukh
163                      Sun Sumukh Sun Sumukh Sun Sumukh
164             Nirman Vistaa Nirman Vistaa Nirman Vistaa
165             Nirman Vistaa Nirman Vistaa Nirman Vistaa
166       Value Charulata Value Charulata Value Charulata
167       Value Charulata Value Charulata Value Charulata
168     Value Meghbalika Value Meghbalika Value Meghba...
169     Value Meghbalika Value Meghbalika Value Meghba...
170     Shriram Grand City Shriram Grand City Shriram ...
171     Shriram Grand City Shriram Grand City Shriram ...
172                Solaris Joka Solaris Joka Solaris Joka
173                Solaris Joka Solaris Joka Solaris Joka
174                Solaris Joka Solaris Joka Solaris Joka
175     Solaris City Serampore Solaris City Serampore ...
176     Solaris City Serampore Solaris City Serampore ...
177     Solaris City Serampore Solaris City Serampore ...
178     Simoco Sanhita Housing Complex Simoco Sanhita ...
179     Swapnabhumi Township Swapnabhumi Township Swap...
180     Swapnabhumi Township Swapnabhumi Township Swap...
181     Swapnabhumi Township Swapnabhumi Township Swap...
182     Swapnabhumi Township Swapnabhumi Township Swap...
183     Aditya Sky Park Residency Aditya Sky Park Resi...
184     Aditya Sky Park Residency Aditya Sky Park Resi...
185     Natural Aqua Waves Natural Aqua Waves Natural ...
186     Natural Aqua Waves Natural Aqua Waves Natural ...
187     Sureka Sunrise Aura Sureka Sunrise Aura Sureka...
188     Sureka Sunrise Aura Sureka Sunrise Aura Sureka...
189                               The 102 The 102 The 102
190                               The 102 The 102 The 102
191                                  Vaanya Vaanya Vaanya
192                                  Vaanya Vaanya Vaanya
193     GS Tridhara Residency GS Tridhara Residency GS...
194     Hive Pinnacle Residency Hive Pinnacle Residenc...
195     Hive Pinnacle Residency Hive Pinnacle Residenc...
196
197     Srijan Star Swapno Puron Srijan Star Swapno Pu...
198     Srijan Star Swapno Puron Srijan Star Swapno Pu...
199     Team Taurus Kabya Team Taurus Kabya Team Tauru...
200                Varada Moana Varada Moana Varada Moana
201     Merlin Lakescape Merlin Lakescape Merlin Lakes...
202     Subarna Renukana Subarna Renukana Subarna Renu...
203     Subarna Renukana Subarna Renukana Subarna Renu...
204                   Saket Nagar Saket Nagar Saket Nagar
205                   Saket Nagar Saket Nagar Saket Nagar
206                   Saket Nagar Saket Nagar Saket Nagar
207     GPS Meena Aurum Phase 2 GPS Meena Aurum Phase ...
208     GPS Meena Aurum Phase 2 GPS Meena Aurum Phase ...
209     Eden City Maheshtala Eden City Maheshtala Eden...
210     Kappa White House Kappa White House Kappa Whit...
211     Kappa White House Kappa White House Kappa Whit...
212     Kappa White House Kappa White House Kappa Whit...
213             Nirman Greens Nirman Greens Nirman Greens
214             Nirman Greens Nirman Greens Nirman Greens
215                Baisnabghata Baisnabghata Baisnabghata
216     MOANA BY VARADA GROUP MOANA BY VARADA GROUP MO...
217                                     Priva Priva Priva
218                                     Priva Priva Priva
219                                     Priva Priva Priva
220          MKBD Mck Tulip MKBD Mck Tulip MKBD Mck Tulip
221          MKBD Mck Tulip MKBD Mck Tulip MKBD Mck Tulip
222          MKBD Mck Tulip MKBD Mck Tulip MKBD Mck Tulip
223                                  Vaanya Vaanya Vaanya
224                                  Vaanya Vaanya Vaanya
225     Orchard Godrej Se7en Orchard Godrej Se7en Orch...
226     Orchard Godrej Se7en Orchard Godrej Se7en Orch...
227       Mereit Gardenia Mereit Gardenia Mereit Gardenia
228       Mereit Gardenia Mereit Gardenia Mereit Gardenia
229     Realtech Rajmahal Realtech Rajmahal Realtech R...
230     Realtech Rajmahal Realtech Rajmahal Realtech R...
231          Realtech Astha Realtech Astha Realtech Astha
232          Realtech Astha Realtech Astha Realtech Astha
233                      Sun Nectar Sun Nectar Sun Nectar
234                      Sun Nectar Sun Nectar Sun Nectar
235                      Sun Nectar Sun Nectar Sun Nectar
236
237
238                      RBJ Orchid RBJ Orchid RBJ Orchid
239                      RBJ Orchid RBJ Orchid RBJ Orchid
240                      RBJ Orchid RBJ Orchid RBJ Orchid
241     Master Orchard Estate Master Orchard Estate Ma...
242     Master Orchard Estate Master Orchard Estate Ma...
243     Master Orchard Estate Master Orchard Estate Ma...
244     Master Orchard Estate Master Orchard Estate Ma...
245     The Banyan Tree Rosetta The Banyan Tree Rosett...
246     The Banyan Tree Rosetta The Banyan Tree Rosett...
247     The Banyan Tree Rosetta The Banyan Tree Rosett...
248     Sapnil Residency Sapnil Residency Sapnil Resid...
249     Sapnil Residency Sapnil Residency Sapnil Resid...
250     Sapnil Residency Sapnil Residency Sapnil Resid...
251     Lake Gardens Chs Lake Gardens Chs Lake Gardens...
252     The Vedic Village The Vedic Village The Vedic ...
253             Rishi Pranaya Rishi Pranaya Rishi Pranaya
254             Rishi Pranaya Rishi Pranaya Rishi Pranaya
255                Varada Moana Varada Moana Varada Moana
256     Chitrakut Mansion Chitrakut Mansion Chitrakut ...
257     Chitrakut Mansion Chitrakut Mansion Chitrakut ...
258     Vinayak Golden Acres Vinayak Golden Acres Vina...
259     Silveroak Estate Silveroak Estate Silveroak Es...
260     Siddha Happyville Siddha Happyville Siddha Hap...
261     Forum Footprints Forum Footprints Forum Footpr...
262     Rishi Enclave Apartment Rishi Enclave Apartmen...
263     Bristy Apartment Bristy Apartment Bristy Apart...
264       GM Meena Orchid GM Meena Orchid GM Meena Orchid
265       GM Meena Orchid GM Meena Orchid GM Meena Orchid
266             GM Meena Icon GM Meena Icon GM Meena Icon
267             GM Meena Icon GM Meena Icon GM Meena Icon
268          GM Meena Flora GM Meena Flora GM Meena Flora
269          GM Meena Flora GM Meena Flora GM Meena Flora
270     GM Meena Eco Vista GM Meena Eco Vista GM Meena...
271     GM Meena Eco Vista GM Meena Eco Vista GM Meena...
272     GM Meena Paradise GM Meena Paradise GM Meena P...
273     GM Meena Paradise GM Meena Paradise GM Meena P...
274     Realmark Seasonss Realmark Seasonss Realmark S...
275     Realmark Seasonss Realmark Seasonss Realmark S...
276     Ashray Residency Ashray Residency Ashray Resid...
277                      Mani Vista Mani Vista Mani Vista
278     CC2 Realtech Nirman CC2 Realtech Nirman CC2 Re...
279     Golf Green Urban Complex Golf Green Urban Comp...
280                MJ Moti Kunj MJ Moti Kunj MJ Moti Kunj
281          panihati pride panihati pride panihati pride
282
283       Prudent Pragati Prudent Pragati Prudent Pragati
284       Prudent Pragati Prudent Pragati Prudent Pragati
285       Prudent Pragati Prudent Pragati Prudent Pragati
286       Prudent Pragati Prudent Pragati Prudent Pragati
287       Unique Fountain Unique Fountain Unique Fountain
288
289       Greenfield City Greenfield City Greenfield City
290       New Town Tower  New Town Tower  New Town Tower
291
292             Bangur Avenue Bangur Avenue Bangur Avenue
293
294     Puja Apartment Kasba Puja Apartment Kasba Puja...
295
296     Joyville Western Heights Joyville Western Heig...
297                               Pratham Pratham Pratham
298                               Pratham Pratham Pratham
299     Shanti Niketan Complex Shanti Niketan Complex ...
300
301                      Onex Privy Onex Privy Onex Privy
302     Lord Jagannath Arcade Lord Jagannath Arcade Lo...
303     Bengal Shelter Sisirkunja Bengal Shelter Sisir...
304     Hiland Calcutta Riverside Hiland Calcutta Rive...
305       Titas Apartment Titas Apartment Titas Apartment
306       Fortune Heights Fortune Heights Fortune Heights
307       Fortune Heights Fortune Heights Fortune Heights
308       Fortune Heights Fortune Heights Fortune Heights
309       Fortune Heights Fortune Heights Fortune Heights
310                         Indraloke Indraloke Indraloke
311             Sahanagar CHS Sahanagar CHS Sahanagar CHS
312
313             Aster Gardens Aster Gardens Aster Gardens
314       Madhavi manjuri Madhavi manjuri Madhavi manjuri
315     Signum  Windmere Signum  Windmere Signum  Wind...
316          GM Meena Ganga GM Meena Ganga GM Meena Ganga
317
318                   Siddha Town Siddha Town Siddha Town
319     Sananda Apartment Sananda Apartment Sananda Ap...
320                            Dhakuria Dhakuria Dhakuria
321     Eden City Maheshtala Eden City Maheshtala Eden...
322     Signum  Windmere Signum  Windmere Signum  Wind...
323                Sucasa Twins Sucasa Twins Sucasa Twins
324     Pramila Niwas Apartment Pramila Niwas Apartmen...
325     Perfect Sharanya Enclave Perfect Sharanya Encl...
326
327                      On request On request On request
328     Sai Baba Apartment Sai Baba Apartment Sai Baba...
329     Merujeen housing Complex Merujeen housing Comp...
330     Upohar The Condoville Upohar The Condoville Up...
331                Merlin Avana Merlin Avana Merlin Avana
332                Merlin Avana Merlin Avana Merlin Avana
333                Merlin Avana Merlin Avana Merlin Avana
334     Bengal Abasan Urban Sabujayan Bengal Abasan Ur...
335     Bengal Abasan Urban Sabujayan Bengal Abasan Ur...
336     Bengal Abasan Urban Sabujayan Bengal Abasan Ur...
337     Rajwada Altitude Rajwada Altitude Rajwada Alti...
338     Sri Sai Home Ujaan Nagar Sri Sai Home Ujaan Na...
339     Tara Maa Apartment Tara Maa Apartment Tara Maa...
340          East Kamalapur East Kamalapur East Kamalapur
341
342     Merlin Woodlands High Merlin Woodlands High Me...
343                   Hiland Park Hiland Park Hiland Park
344                               Diganta Diganta Diganta
345     Team Taurus Kabya Team Taurus Kabya Team Tauru...
346
347                         kalikapur kalikapur kalikapur
348                               PS Jiva PS Jiva PS Jiva
349     The Orchid Grandeur The Orchid Grandeur The Or...
350     Multiple Rai Bahadur Bhaban Multiple Rai Bahad...
351                            Srijoyee Srijoyee Srijoyee
352
353     Uttarayan cooperative housing society Uttaraya...
354                            HB block HB block HB block
355     Shantiniketan Apartment Shantiniketan Apartmen...
356             Maya Enclave  Maya Enclave  Maya Enclave
357     Alcove New Kolkata Sangam Alcove New Kolkata S...
358     Dakshini Apartment  Dakshini Apartment  Dakshi...
359
360          Merlin Maximus Merlin Maximus Merlin Maximus

In [178]:
df.columns

Index(['PREFERENCE', 'DESCRIPTION', 'PROPERTY_TYPE', 'CITY', 'TRANSACT_TYPE',
       'OWNTYPE', 'BEDROOM_NUM', 'FURNISH', 'FACING', 'AGE', 'TOTAL_FLOOR',
       'FEATURES', 'PROP_NAME', 'AMENITIES', 'AREA', 'PRICE', 'PROP_HEADING',
       'SECONDARY_TAGS', 'TOTAL_LANDMARK_COUNT', 'FORMATTED_LANDMARK_DETAILS',
       'location', 'BALCONY_NUM', 'FLOOR_NUM', 'PRICE_Cr', 'AREA_SQFT',
       'PRICE_PER_SQFT(INR)', 'OWNTYPE_label', 'FURNISH_label', 'FACING_label',
       'LATITUDE', 'LONGITUDE'],
      dtype='str')

In [179]:
df["PROP_NAME"].isnull().sum()

np.int64(635)

In [180]:
df.head()

,PREFERENCE,DESCRIPTION,PROPERTY_TYPE,CITY,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,AMENITIES,AREA,PRICE,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT,PRICE_PER_SQFT(INR),OWNTYPE_label,FURNISH_label,FACING_label,LATITUDE,LONGITUDE
0,S,Book your 2 BHK flat in Srijan Star Swapno Pur...,Residential Apartment,Kolkata South,2.0,1,2.0,0,0,5,3.0,N,srijan star swapno puron,NaN,518-623 sq.ft.,19.1 L Onwards,2 BHK Flat in Amtala,"['UNDER CONSTRUCTION', 'NEW BOOKING', 'RERA | ...",2.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.191000,570.5,3347.94,Cooperative Society,Unfurnished,East,22.364447,88.274642
1,S,Make Natural Quest your next home. This projec...,Residential Apartment,Kolkata South,2.0,1,3.0,0,0,5,11.0,N,natural quest,NaN,1110-1121 sq.ft.,1.17 - 1.18 Cr,3 BHK Flat in EM Bypass,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",9.0,"[{'category': 'MetroStation', 'text': '1 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.590000,1115.5,5289.11,Cooperative Society,Unfurnished,East,22.518795,88.388439
2,S,"Book your 3 BHK apartment in Garia, Kolkata So...",Residential Apartment,Kolkata South,2.0,1,3.0,0,0,5,20.0,N,ganguly 4sight eminence,NaN,1376-1516 sq.ft.,1.22 - 1.35 Cr,3 BHK Flat in Garia,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",6.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.675000,1446.0,4668.05,Cooperative Society,Unfurnished,East,22.513765,88.366680
3,S,"Dev bhumi in joka, kolkata south by ocean land...",Residential Land,Kolkata South,2.0,1,NaN,0,0,0,0.0,N,dev bhumi,NaN,720-2880 sq.ft.,1.5 - 5.99 L,Residential land / Plot in Joka,"['READY TO MOVE', 'NEW BOOKING']",13.0,"[{'category': 'MetroStation', 'text': '2 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,NaN,0.029950,1800.0,166.39,Cooperative Society,Unfurnished,East,22.453830,88.249572
4,S,Let your dream of owning a flat come true with...,Residential Apartment,Kolkata South,2.0,1,3.0,0,0,5,19.0,N,dtc sojon,NaN,1130-1460 sq.ft.,60 - 75 L,3 BHK Flat in Joka,"['UNDER CONSTRUCTION', 'NEW BOOKING']",11.0,"[{'category': 'MetroStation', 'text': '1 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.375003,1295.0,2895.78,Cooperative Society,Unfurnished,East,22.442130,88.295510

In [183]:
# df.drop(columns=["AREA"], inplace= True)
df.drop(columns=["PRICE"], inplace= True)

In [184]:
df.head()

,PREFERENCE,DESCRIPTION,PROPERTY_TYPE,CITY,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,FURNISH,FACING,AGE,TOTAL_FLOOR,FEATURES,PROP_NAME,AMENITIES,PROP_HEADING,SECONDARY_TAGS,TOTAL_LANDMARK_COUNT,FORMATTED_LANDMARK_DETAILS,location,BALCONY_NUM,FLOOR_NUM,PRICE_Cr,AREA_SQFT,PRICE_PER_SQFT(INR),OWNTYPE_label,FURNISH_label,FACING_label,LATITUDE,LONGITUDE
0,S,Book your 2 BHK flat in Srijan Star Swapno Pur...,Residential Apartment,Kolkata South,2.0,1,2.0,0,0,5,3.0,N,srijan star swapno puron,NaN,2 BHK Flat in Amtala,"['UNDER CONSTRUCTION', 'NEW BOOKING', 'RERA | ...",2.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.191000,570.5,3347.94,Cooperative Society,Unfurnished,East,22.364447,88.274642
1,S,Make Natural Quest your next home. This projec...,Residential Apartment,Kolkata South,2.0,1,3.0,0,0,5,11.0,N,natural quest,NaN,3 BHK Flat in EM Bypass,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",9.0,"[{'category': 'MetroStation', 'text': '1 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.590000,1115.5,5289.11,Cooperative Society,Unfurnished,East,22.518795,88.388439
2,S,"Book your 3 BHK apartment in Garia, Kolkata So...",Residential Apartment,Kolkata South,2.0,1,3.0,0,0,5,20.0,N,ganguly 4sight eminence,NaN,3 BHK Flat in Garia,"['UNDER CONSTRUCTION', 'NEW LAUNCH', 'NEW BOOK...",6.0,"[{'category': 'Shopping', 'text': '1 Shopping'...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.675000,1446.0,4668.05,Cooperative Society,Unfurnished,East,22.513765,88.366680
3,S,"Dev bhumi in joka, kolkata south by ocean land...",Residential Land,Kolkata South,2.0,1,NaN,0,0,0,0.0,N,dev bhumi,NaN,Residential land / Plot in Joka,"['READY TO MOVE', 'NEW BOOKING']",13.0,"[{'category': 'MetroStation', 'text': '2 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,NaN,0.029950,1800.0,166.39,Cooperative Society,Unfurnished,East,22.453830,88.249572
4,S,Let your dream of owning a flat come true with...,Residential Apartment,Kolkata South,2.0,1,3.0,0,0,5,19.0,N,dtc sojon,NaN,3 BHK Flat in Joka,"['UNDER CONSTRUCTION', 'NEW BOOKING']",11.0,"[{'category': 'MetroStation', 'text': '1 Metro...","{'CITY': '27', 'CITY_NAME': 'Kolkata South', '...",NaN,1,0.375003,1295.0,2895.78,Cooperative Society,Unfurnished,East,22.442130,88.295510

In [186]:
new_df =df.to_csv("D:\\CODING\\Virtual_py\\PROJECTS\\real_estate_ml\\backend\\kolkata.csv\\kolkata_cleaned_v1.csv", index = False)